UsingFaustWithROS.pdf : UsingFaustWithROS.tex chapters/*.tex
	pdflatex UsingFaustWithROS.tex
	rail UsingFaustWithROS
	pdflatex UsingFaustWithROS.tex
	
clean :
	rm -f *.out *.toc *.pdf *.aux *.dvi *.rai *.rao *.log *~
	
	
