/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package faust_dsp;

public class faust_dsp {
  public static SWIGTYPE_p_int new_intArray(int nelements) {
    long cPtr = faust_dspJNI.new_intArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intArray(SWIGTYPE_p_int ary) {
    faust_dspJNI.delete_intArray(SWIGTYPE_p_int.getCPtr(ary));
  }

  public static int intArray_getitem(SWIGTYPE_p_int ary, int index) {
    return faust_dspJNI.intArray_getitem(SWIGTYPE_p_int.getCPtr(ary), index);
  }

  public static void intArray_setitem(SWIGTYPE_p_int ary, int index, int value) {
    faust_dspJNI.intArray_setitem(SWIGTYPE_p_int.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_float new_floatArray(int nelements) {
    long cPtr = faust_dspJNI.new_floatArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static void delete_floatArray(SWIGTYPE_p_float ary) {
    faust_dspJNI.delete_floatArray(SWIGTYPE_p_float.getCPtr(ary));
  }

  public static float floatArray_getitem(SWIGTYPE_p_float ary, int index) {
    return faust_dspJNI.floatArray_getitem(SWIGTYPE_p_float.getCPtr(ary), index);
  }

  public static void floatArray_setitem(SWIGTYPE_p_float ary, int index, float value) {
    faust_dspJNI.floatArray_setitem(SWIGTYPE_p_float.getCPtr(ary), index, value);
  }

  public static String new_charArray(int nelements) {
    return faust_dspJNI.new_charArray(nelements);
  }

  public static void delete_charArray(String ary) {
    faust_dspJNI.delete_charArray(ary);
  }

  public static char charArray_getitem(String ary, int index) {
    return faust_dspJNI.charArray_getitem(ary, index);
  }

  public static void charArray_setitem(String ary, int index, char value) {
    faust_dspJNI.charArray_setitem(ary, index, value);
  }

}
