/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package faust_dsp;

public class faust_dspJNI {

  static {
    try {
        java.lang.System.loadLibrary("faust_dsp");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native long new_intArray(int jarg1);
  public final static native void delete_intArray(long jarg1);
  public final static native int intArray_getitem(long jarg1, int jarg2);
  public final static native void intArray_setitem(long jarg1, int jarg2, int jarg3);
  public final static native long new_floatArray(int jarg1);
  public final static native void delete_floatArray(long jarg1);
  public final static native float floatArray_getitem(long jarg1, int jarg2);
  public final static native void floatArray_setitem(long jarg1, int jarg2, float jarg3);
  public final static native String new_charArray(int jarg1);
  public final static native void delete_charArray(String jarg1);
  public final static native char charArray_getitem(String jarg1, int jarg2);
  public final static native void charArray_setitem(String jarg1, int jarg2, char jarg3);
  public final static native void Para_cnt_set(long jarg1, Para jarg1_, int jarg2);
  public final static native int Para_cnt_get(long jarg1, Para jarg1_);
  public final static native void Para_cntLay_set(long jarg1, Para jarg1_, int jarg2);
  public final static native int Para_cntLay_get(long jarg1, Para jarg1_);
  public final static native void Para_typeLay_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_typeLay_get(long jarg1, Para jarg1_);
  public final static native void Para_labelLayPos_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_labelLayPos_get(long jarg1, Para jarg1_);
  public final static native void Para_labelLay_set(long jarg1, Para jarg1_, String jarg2);
  public final static native String Para_labelLay_get(long jarg1, Para jarg1_);
  public final static native void Para_type_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_type_get(long jarg1, Para jarg1_);
  public final static native void Para_layoutEl_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_layoutEl_get(long jarg1, Para jarg1_);
  public final static native void Para_zone_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_zone_get(long jarg1, Para jarg1_);
  public final static native void Para_labelPos_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_labelPos_get(long jarg1, Para jarg1_);
  public final static native void Para_label_set(long jarg1, Para jarg1_, String jarg2);
  public final static native String Para_label_get(long jarg1, Para jarg1_);
  public final static native void Para_init_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_init_get(long jarg1, Para jarg1_);
  public final static native void Para_min_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_min_get(long jarg1, Para jarg1_);
  public final static native void Para_max_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_max_get(long jarg1, Para jarg1_);
  public final static native void Para_step_set(long jarg1, Para jarg1_, long jarg2);
  public final static native long Para_step_get(long jarg1, Para jarg1_);
  public final static native long new_Para();
  public final static native void delete_Para(long jarg1);
  public final static native long faust_initFaust(long jarg1, faust jarg1_);
  public final static native void faust_startAudio(long jarg1, faust jarg1_);
  public final static native void faust_processDSP(long jarg1, faust jarg1_);
  public final static native void faust_setParam(long jarg1, faust jarg1_, long jarg2);
  public final static native void faust_stopAudio(long jarg1, faust jarg1_);
  public final static native long new_faust();
  public final static native void delete_faust(long jarg1);
}
