#!/bin/bash

# message colors
red='\e[1;31m'
green='\e[1;32m'
NC='\e[0m' # No Color

OPTIONS="$1 $2"

SCRIPTS=../../tools/faust2appls/faust2*
rm -rf sandbox
rm -f LOG
for f in *.dsp; do
	echo "test file $f"
	for s in $SCRIPTS; do
		echo -n "compile $f with script $s $OPTIONS  : "
		(($s $OPTIONS $f  >> ../LOG 2>&1) && echo -e "${green}PASSED${NC}" ) || echo -e "${red}FAILED${NC}"
	done
done
		
		
