
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"tester2\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"262236\",\"inputs\":\"0\",\"outputs\":\"2\",\"meta\":[{\"author\":\"Grame\"},{\"basics.lib/name\":\"Faust Basic Element Library\"},{\"basics.lib/version\":\"0.0\"},{\"copyright\":\"(c)GRAME 2014\"},{\"license\":\"BSD\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"tester2\"},{\"noises.lib/name\":\"Faust Noise Generator Library\"},{\"noises.lib/version\":\"0.0\"},{\"oscillators.lib/name\":\"Faust Oscillator Library\"},{\"oscillators.lib/version\":\"0.0\"},{\"signals.lib/name\":\"Faust Signal Routing Library\"},{\"signals.lib/version\":\"0.0\"},{\"version\":\"1.0\"}],\"ui\":[{\"type\":\"vgroup\",\"label\":\"Stereo Audio Tester\",\"items\":[{\"type\":\"hslider\",\"label\":\"freq\",\"address\":\"/Stereo_Audio_Tester/freq\",\"index\":\"262184\",\"meta\":[{\"1\":\"\"},{\"scale\":\"log\"},{\"unit\":\"Hz\"}],\"init\":\"440\",\"min\":\"40\",\"max\":\"20000\",\"step\":\"1\"},{\"type\":\"hslider\",\"label\":\"volume\",\"address\":\"/Stereo_Audio_Tester/volume\",\"index\":\"262148\",\"meta\":[{\"2\":\"\"},{\"unit\":\"dB\"}],\"init\":\"-96\",\"min\":\"-96\",\"max\":\"0\",\"step\":\"1\"},{\"type\":\"hslider\",\"label\":\"signal\",\"address\":\"/Stereo_Audio_Tester/signal\",\"index\":\"262172\",\"meta\":[{\"3\":\"\"},{\"style\":\"menu{'white noise':0;'pink noise':1;'sine':2}\"}],\"init\":\"0\",\"min\":\"0\",\"max\":\"2\",\"step\":\"1\"},{\"type\":\"hslider\",\"label\":\"channel\",\"address\":\"/Stereo_Audio_Tester/channel\",\"index\":\"262160\",\"meta\":[{\"4\":\"\"},{\"style\":\"radio{'none':0;'left':1;'right':2;'both':3}\"}],\"init\":\"0\",\"min\":\"0\",\"max\":\"3\",\"step\":\"1\"}]}]}";
}
