
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"dbmeter\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"136\",\"inputs\":\"8\",\"outputs\":\"8\",\"meta\":[{\"author\":\"Grame\"},{\"basics.lib/name\":\"Faust Basic Element Library\"},{\"basics.lib/version\":\"0.0\"},{\"copyright\":\"(c)GRAME 2006\"},{\"license\":\"BSD\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"dbmeter\"},{\"version\":\"1.0\"}],\"ui\":[{\"type\":\"hgroup\",\"label\":\"8 channels dB meter\",\"items\":[{\"type\":\"vgroup\",\"label\":\"0\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7fd145708fd0\",\"address\":\"/8_channels_dB_meter/0/0x7fd145708fd0\",\"index\":\"16\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"1\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7fd14570d6b0\",\"address\":\"/8_channels_dB_meter/1/0x7fd14570d6b0\",\"index\":\"32\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"2\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7fd145711d90\",\"address\":\"/8_channels_dB_meter/2/0x7fd145711d90\",\"index\":\"48\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"3\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7fd145716520\",\"address\":\"/8_channels_dB_meter/3/0x7fd145716520\",\"index\":\"64\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"4\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7fd14571ad60\",\"address\":\"/8_channels_dB_meter/4/0x7fd14571ad60\",\"index\":\"80\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"5\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7fd14571f650\",\"address\":\"/8_channels_dB_meter/5/0x7fd14571f650\",\"index\":\"96\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"6\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7fd145723ff0\",\"address\":\"/8_channels_dB_meter/6/0x7fd145723ff0\",\"index\":\"112\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"7\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7fd145728a40\",\"address\":\"/8_channels_dB_meter/7/0x7fd145728a40\",\"index\":\"128\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]}]}]}";
}
