#!/bin/bash

. faustpath
. faustoptflags

#-------------------------------------------------------------------
# Analyze command arguments :
# faust options                 -> OPTIONS
# existing *.dsp files          -> FILES
#

for p in $@; do
    if [ $p = "-osc" ]; then
	 OSCDEFS="-DOSCCTRL -L$FAUSTLIB -lOSCFaust -loscpack"
    elif [ $p = "-httpd" ]; then
	 HTTPDEFS="-DHTTPCTRL -L$FAUSTLIB -lHTTPDFaust -lmicrohttpd"
    elif [ ${p:0:1} = "-" ]; then
	    OPTIONS="$OPTIONS $p"
	elif [[ -e "$p" ]]; then
	    FILES="$FILES $p"
	else
	    OPTIONS="$OPTIONS $p"        
	fi
done

#-------------------------------------------------------------------
# compile the *.dsp files
#
for f in $FILES; do
    faust -lang java -cn ${f%.dsp} -a java-swing.java $OPTIONS $f -o ${f%.dsp}.java
    javac ${f%.dsp}.java
    jar cvfe ${f%.dsp}.jar ${f%.dsp} *.class
    rm ${f%.dsp}*.class UI*.class Meta.class FaustVarAccess.class Sound*PlayThread.class Sound.class dsp.class ${f%.dsp}.java
done
