/*                                                                             *
*   SPDX-FileCopyrightText: 2026 GRAME, Centre National de Creation Musicale   *
*   SPDX-License-Identifier: LGPL-2.1-or-later                                 *
*                                                                             */

/** @file compiler/generator/mojo/mojo_instructions_vec.cpp **/

// mojo
#include "mojo_instructions.hh"

// Mojo vectorial instruction visitor implementation.

inline namespace mojo {

using VecVisitor  = MojoVecInstVisitor;
using BaseVisitor = MojoInstVisitor;
using MojoDType   = VecVisitor::MojoDType;

MojoVecInstVisitor::MojoVecInstVisitor(OStream* out, String const& structName, s32 tab)
    : BaseVisitor(out, structName, tab)
{   resetLoopContext();   }

MojoVecInstVisitor::~MojoVecInstVisitor()
{}

void VecVisitor::visit(IfInst* inst)
{   /* do not generate remaining frames */   }

void VecVisitor::visit(Int32NumInst* inst)
{
    mj_simd_emit_check(); *fOut << (gSIMDHalf ? "S32Hec(" : "S32Vec(") << inst->fNum << ")";
}

void VecVisitor::visit(BoolNumInst* inst)
{
    mj_simd_emit_check(); *fOut << (gSIMDHalf ? "S32Hec(" : "S32Vec(") << checkFloat(inst->fNum) << ")";
}

void VecVisitor::visit(FloatNumInst* inst)
{
    mj_simd_emit_check(); *fOut << (gSIMDHalf ? "F32Hec(" : "F32Vec(") << checkFloat(inst->fNum) << ")";
}

void VecVisitor::visit(DoubleNumInst* inst)
{
    mj_simd_emit_check(); *fOut << "F64Vec(" << checkDouble(inst->fNum) << ")";
}

void VecVisitor::visit(DeclareVarInst* inst)
{
    if (inst->getName().find("vsize") != String::npos) {
        return;  // explicitly generated by the `MojoVecCodeContainer`
    }
    BaseVisitor::visit(inst);
}

void VecVisitor::visit(NamedAddress* inst)
{
    if (inst->isLoop()) {
        mj_scalar_visit(inst);
        return;
    }
    BaseVisitor::visit(inst);
}

void VecVisitor::visit(Select2Inst* inst)
{
    mj_simd_emit_check();
    if (isScalarValue(inst->fCond)) {
        *fOut << "(";
        BaseVisitor::visit(inst);
        *fOut << ")";
        return;
    }

    *fOut << "(";
    inst->fCond->accept(this);
    *fOut << ").ne(0).select(";
    visitBinopOperand(inst->fThen);
    *fOut << ", ";
    visitBinopOperand(inst->fElse);
    *fOut << ")";
}

void VecVisitor::visit(LoadVarInst* inst)
{
    if (not gCurGraph.empty() && inst->getName() == gCurGraph) {
        IB::genLoadArrayStackVar(
            gCurGraph + "_vec", IB::genLoadLoopVar(gCurIndex->getName())
        )->accept(this);
        return;
    }

    MojoDType cur_load_dtype = getMojoDType(inst);
    b32 join_load_f64 = gCurLhsDT == MojoDType_faust
                        && cur_load_dtype == MojoDType_f64;
    b32 split_load_f64 = gCurLhsDT == MojoDType_f64
                         && (cur_load_dtype == MojoDType_s32 || cur_load_dtype == MojoDType_faust);

    if (join_load_f64 || split_load_f64) {
        gSIMDHalf = true;
    }

    BaseVisitor::visit(inst);
}

void VecVisitor::visit(CastInst* inst)
{
    mj_simd_emit_check();
    Typed::VarType type = inst->fType->getType();
    if (auto* binop = dycast(BinopInst*, inst->fInst);
        binop && type == Typed::kInt32 && isBoolOpcode(binop->fOpcode)) {
        inst->fInst->accept(this);
        return;
    }
    *fOut << "(";
    inst->fInst->accept(this);
    switch (type) {
        case Typed::kFloatMacro: *fOut << ").cast[dfaust]()"; break;
        case Typed::kFloat:      *fOut << ").cast[f32]()";    break;
        case Typed::kDouble:     *fOut << ").cast[f64]()";    break;
        case Typed::kInt32:      *fOut << ").cast[s32]()";    break;
        default:
            mj_panic(false, "`inst` has unexpected type " << Typed::gTypeString[type]);
    }
}

void VecVisitor::visit(IndexedAddress* inst)
{
    mj_simd_emit_check();
    Address* addr = inst->fAddress;
    String name = snakeCase(addr->getName());
    name = addr->isStruct() || addr->isStaticStruct() ? "dsp." + name : name;
    String func = gSIMDHalf ? "vload[H]" : "vload";
    *fOut << func << "(" << name;
    b32 has_index = visitIndex(inst->getIndex());
    if (gSIMDHigh) {
        *fOut << (has_index ? " + hsize" : ", hsize");
    }
    *fOut << ")";
}

void VecVisitor::visit(BinopInst* inst)
{
    mj_simd_emit_check();

    s32 opc = inst->fOpcode;
    b32 is_cmp = isBoolOpcode(opc);

    *fOut << (is_cmp ? "((" : "(");
    visitBinopOperand(inst->fInst1);

    if (is_cmp) {
        *fOut << ")";
        switch (opc) {
            case kGT: *fOut << ".gt("; break;
            case kLT: *fOut << ".lt("; break;
            case kGE: *fOut << ".ge("; break;
            case kLE: *fOut << ".le("; break;
            case kEQ: *fOut << ".eq("; break;
            case kNE: *fOut << ".ne("; break;
            default:
                mj_panic(false, "Unexpected opcode: " << gBinOpTable[opc]->fName);
        }
    } else {
        *fOut << ") " << gBinOpTable[opc]->fName << " (";
    }

    visitBinopOperand(inst->fInst2);
    *fOut << ")";

    if (is_cmp) {
        *fOut << ".cast[s32]())";
    }
}

void VecVisitor::visit(ForLoopInst* inst)
{
    if (inst->fCode->size() == 0) {
        return;
    }

    if (inst->fInit->getName().find("vindex") != String::npos) {
        return visitMain(inst);
    }

    if (inst->fIsRecursive) {
        return visitScalar(inst);
    }

    auto* ini_inst = dycast(DeclareVarInst*, inst->fInit);
    mj_panic(ini_inst, "Expected `inst` to be `DeclareVarInst`");
    gCurIndex = ini_inst->fAddress;

    auto* first_store = dycast(StoreVarInst*, inst->fCode->front());
    if (inst->fCode->size() == 2 && not isBargraphStore(first_store)) {
        visitScalar(inst);  // Table case, typically with wrapped index
        resetLoopContext();
        return;
    }

    if (inst->fCode->size() == 2) {
        visitBargraphUpdate(inst);
    }
    if (inst->fCode->size() > 2) {
        visitBargraphMulti(inst);
    }

    auto* store = dycast(StoreVarInst*, inst->fCode->back());
    mj_panic(store, "Expected final instruction to be a `StoreVarInst`");

    prepareLoop(store);
    visitLoopStore(inst, store);
    finishLoop();
}

void VecVisitor::visitMain(ForLoopInst* inst)
{
    *fOut << "while vindex <= end:" << wnextl(fTab += 1);
    inst->fCode->accept(this);
    fTab -= 1;
}

void VecVisitor::visitScalar(ForLoopInst* inst)
{
    *fOut << "comptime for i in range(vsize):" << wnextl(fTab += 1);
    mj_scalar_accept(inst->fCode);
    fTab -= 1;
    wrewind(fOut);
}

void VecVisitor::prepareLoop(StoreVarInst* inst)
{
    Address* lhs = inst->fAddress;
    gCurAddrs = snakeCase(lhs->getName());
    gCurAddrs = lhs->isStruct() || lhs->isStaticStruct() ? "dsp." + gCurAddrs : gCurAddrs;
    gCurLhsDT = getMojoDType(inst->fValue);
}

void VecVisitor::visitLoopStore(ForLoopInst* loop, StoreVarInst* store)
{
    Address*   lhs = store->fAddress;
    ValueInst* rhs = store->fValue;

    if (not isVectorizable(lhs)) {
        return visitScalar(loop);
    }
    if (isScalarValue(rhs)) {
        return visitBroadcast(store);
    }
    if (not isVectorizable(rhs)) {
        return visitScalar(loop);
    }
    if (gCurLhsDT == MojoDType_f64 || (gCurLhsDT == MojoDType_s32 && hasF64Value(rhs))) {
        return visitSplit(store);
    }

    MojoDType rhs_dtype = getMojoDType(stripCasts(rhs));
    if (rhs_dtype == MojoDType_f64 || (gCurLhsDT == MojoDType_faust && hasF64Value(rhs))) {
        return visitJoin(store);
    }
    visitStore(store);
}

void VecVisitor::finishLoop()
{
    *fOut << wnextl(fTab);
    resetLoopContext();
}

void VecVisitor::resetLoopContext()
{
    gSIMDEmit = false;
    gSIMDHigh = false;
    gSIMDHalf = false;
    gCurLhsDT = MojoDType_none;
    gCurAddrs.clear();
    gCurIndex = nullptr;
    gCurGraph.clear();
}

void VecVisitor::visitBargraphUpdate(ForLoopInst* inst)
{
    auto* store_1 = dycast(StoreVarInst*, inst->fCode->front());
    auto* store_2 = dycast(StoreVarInst*, inst->fCode->back());
    mj_panic(store_1 && store_2, "Expected two store instructions");

    String tmp = store_1->getName() + "_vec";
    String index = gCurIndex->getName();

    IB::genDecStackVar(tmp, IB::genArrayTyped(IB::genFloatMacroTyped(), gGlobal->gVecSize))
        ->accept(this);

    auto* code = IB::genBlockInst();
    code->pushBackInst(store_1);
    code->pushBackInst(IB::genStoreArrayStackVar(
        tmp, IB::genLoadLoopVar(index), IB::genLoadVarInst(store_1->fAddress)));

    *fOut << "comptime for " << snakeCase(index) << " in range(vsize):" << wnextl(fTab += 1);
    mj_scalar_accept(code);
    fTab -= 1;
    wrewind(fOut, 1);

    // Redirect bargraph loads only while lowering the final store.
    gCurGraph = store_1->getName();
}

void VecVisitor::visitBargraphMulti(ForLoopInst* inst)
{
    Arr<StoreVarInst*> bars;
    auto* store = dycast(StoreVarInst*, inst->fCode->back());
    mj_panic(store, "Expected final instruction to be a `StoreVarInst`");
    for (auto* line : *inst->fCode) {
        auto* sv_inst = dycast(StoreVarInst*, line);
        mj_panic(sv_inst, "Expected each loop instruction to be a `StoreVarInst`");
        if (isBargraphStore(sv_inst)) {
            bars.push_back(sv_inst);
        }
    }
    mj_panic(bars.size() > 1, "Expected at least two bargraph instructions");
    *fOut << "comptime for i in range(S32(0), vsize):" << wnextl(fTab += 1);
    for (auto* bar : bars) {
        mj_scalar_visit(bar);
    }
    fTab -= 1;
    wrewind(fOut, 1);
}

void VecVisitor::visitBroadcast(StoreVarInst* inst)
{
    *fOut << "vstore[wfaust](" << gCurAddrs << ", ";
    mj_simd_emit_accept(inst->fValue);
    *fOut << ")";
}

void VecVisitor::visitSplit(StoreVarInst* inst)
{
    mj_simd_emit_set(true);
    gSIMDHalf = true;
    *fOut << "vstore(" << gCurAddrs << ", ";
    inst->fValue->accept(this);
    *fOut << ")" << wnextl(fTab) << "vstore(" << gCurAddrs << ", ";
    mj_simd_high_accept(inst->fValue);
    *fOut << ", hsize)";
    mj_simd_emit_restore();
}

void VecVisitor::visitJoin(StoreVarInst* inst)
{
    mj_simd_emit_set(true);
    gSIMDHalf = true;
    *fOut << "vstore(" << gCurAddrs << ", (";
    inst->fValue->accept(this);
    *fOut << ").join(";
    mj_simd_high_accept(inst->fValue);
    *fOut << "))";
    mj_simd_emit_restore();
}

void VecVisitor::visitStore(StoreVarInst* inst)
{
    *fOut << "vstore(" << gCurAddrs << ", ";
    mj_simd_emit_accept(inst->fValue);
    *fOut << ")";
}

void VecVisitor::visitBinopOperand(ValueInst* inst)
{
    // Bargraph updates bypass store classification; keep their scalar operands unwrapped.
    if (gCurLhsDT == MojoDType_none || not isScalarValue(inst)) {
        inst->accept(this);
        return;
    }

    MojoDType dtype = getMojoDType(inst);
    b32       wec   = gSIMDHalf || gCurLhsDT == MojoDType_f64;

    switch (dtype) {
        case MojoDType_s32:
        case MojoDType_bool:
            *fOut << (wec ? "S32Hec(" : "S32Vec("); break;

        case MojoDType_f32:
        case MojoDType_faust:
            *fOut << (wec ? "F32Hec(" : "F32Vec("); break;

        case MojoDType_f64:
            *fOut << "F64Vec("; break;

        default:
            mj_panic(false, "Unexpected scalar operand dtype");
    }

    mj_scalar_accept(inst);
    *fOut << ")";
}

b32 VecVisitor::visitIndex(ValueInst* inst)
{
    if (auto* load = dycast(LoadVarInst*, inst);
        load && load->fAddress->getName() == gCurIndex->getName()) {
        return false;
    }
    if (auto* binop = dycast(BinopInst*, inst)) {
        String opc = gBinOpTable[binop->fOpcode]->fName;
        auto* lhs = dycast(LoadVarInst*, binop->fInst1);
        auto* rhs = dycast(LoadVarInst*, binop->fInst2);
        if (lhs && lhs->fAddress->getName() == gCurIndex->getName()) {
            *fOut << ", " << (opc == "-" ? "- " : "");
            mj_scalar_accept(binop->fInst2);
            return true;
        }
        if (rhs && rhs->fAddress->getName() == gCurIndex->getName()) {
            *fOut << ", ";
            mj_scalar_accept(binop->fInst1);
            return true;
        }
    }
    *fOut << ", ";
    mj_scalar_accept(inst);
    return true;
}

b32 VecVisitor::isBargraphStore(StoreVarInst* inst)
{
    return inst && inst->getName().find("bargraph") != String::npos;
}

b32 VecVisitor::hasWrappedIndex(Address* addr)
{
    auto* indexed = dycast(IndexedAddress*, addr);
    mj_panic(indexed, "Expected `addr` to be `IndexedAddress`");
    if (indexed->fIndices.size() != 1) {
        return true;
    }
    return isWrappedIndexExpr(indexed->getIndex());
}

b32 VecVisitor::hasWrappedIndex(ValueInst* inst)
{
    if (auto* cast_inst = dycast(CastInst*, inst)) {
        return hasWrappedIndex(cast_inst->fInst);
    }
    if (auto* neg_inst = dycast(NegInst*, inst)) {
        return hasWrappedIndex(neg_inst->fInst);
    }
    if (auto* binop_inst = dycast(BinopInst*, inst)) {
        return hasWrappedIndex(binop_inst->fInst1) || hasWrappedIndex(binop_inst->fInst2);
    }
    if (auto* select_inst = dycast(Select2Inst*, inst)) {
        return hasWrappedIndex(select_inst->fCond)
               || hasWrappedIndex(select_inst->fThen)
               || hasWrappedIndex(select_inst->fElse);
    }
    if (auto* call_inst = dycast(FunCallInst*, inst)) {
        for (auto* arg : call_inst->fArgs) {
            if (hasWrappedIndex(arg)) {
                return true;
            }
        }
    }
    if (auto* load_inst = dycast(LoadVarInst*, inst)) {
        if (isScalarAddress(load_inst->fAddress)) {
            return false;
        }
        return hasWrappedIndex(load_inst->fAddress);
    }
    return false;
}

b32 VecVisitor::isWrappedIndexExpr(ValueInst* inst)
{
    if (auto* cast_inst = dycast(CastInst*, inst)) {
        return isWrappedIndexExpr(cast_inst->fInst);
    }
    if (auto* lv_inst = dycast(LoadVarInst*, inst)) {
        return lv_inst->getName() == gCurGraph || not lv_inst->isSimpleValue();
    }
    if (auto* binop_inst = dycast(BinopInst*, inst)) {
        s32 opcode = binop_inst->fOpcode;
        if (not (opcode == kAdd || opcode == kSub)) {
            return true;
        }
        return isWrappedIndexExpr(binop_inst->fInst1)
               || isWrappedIndexExpr(binop_inst->fInst2);
    }
    if (dycast(FunCallInst*, inst)) {
        return true;  // NOTE:(manu) currently gather (e.g. `A[f(x)]`) is defaulted to scalar
    }
    return false;
}

b32 VecVisitor::isScalarValue(ValueInst* inst)
{
    ValueInst* value = stripCasts(inst);
    if (auto* neg_inst = dycast(NegInst*, value)) {
        return isScalarValue(neg_inst->fInst);
    }
    auto* lv_inst = dycast(LoadVarInst*, value);
    return lv_inst && lv_inst->getName() != gCurGraph && lv_inst->isSimpleValue();
}

b32 VecVisitor::isScalarAddress(Address* addr)
{
    return not dycast(IndexedAddress*, addr);
}

b32 VecVisitor::isVectorizable(Address* addr)
{
    if (isScalarAddress(addr)) {
        return false;
    }
    return not hasWrappedIndex(addr);
}

b32 VecVisitor::isVectorizable(ValueInst* inst)
{
    return not hasWrappedIndex(inst);
}

ValueInst* VecVisitor::stripCasts(ValueInst* inst)
{
    while (auto* cast_inst = dycast(CastInst*, inst)) {
        inst = cast_inst->fInst;
    }
    return inst;
}

b32 VecVisitor::hasF64Value(ValueInst* inst)
{
    if (getMojoDType(inst) == MojoDType_f64) {
        return true;
    }
    if (auto* cast_inst = dycast(CastInst*, inst)) {
        return hasF64Value(cast_inst->fInst);
    }
    if (auto* neg_inst = dycast(NegInst*, inst)) {
        return hasF64Value(neg_inst->fInst);
    }
    if (auto* binop_inst = dycast(BinopInst*, inst)) {
        return hasF64Value(binop_inst->fInst1) || hasF64Value(binop_inst->fInst2);
    }
    if (auto* call_inst = dycast(FunCallInst*, inst)) {
        for (auto* args : call_inst->fArgs) {
            if (hasF64Value(args)) {
                return true;
            }
        }
    }
    if (auto* select_inst = dycast(Select2Inst*, inst)) {
        return hasF64Value(select_inst->fCond)
               || hasF64Value(select_inst->fThen)
               || hasF64Value(select_inst->fElse);
    }
    return false;
}

MojoDType VecVisitor::getMojoDType(ValueInst* inst)
{
    Typed::VarType type = TypingVisitor::getType(inst);
    if (Typed::isPtrType(type)) {
        type = Typed::getTypeFromPtr(type);
    }
    if (Typed::isVecType(type)) {
        type = Typed::getTypeFromVec(type);
    }
    switch (type) {
        case Typed::kInt32:      return MojoDType_s32;
        case Typed::kFloat:      return MojoDType_f32;
        case Typed::kDouble:     return MojoDType_f64;
        case Typed::kFloatMacro: return MojoDType_faust;
        case Typed::kBool:       return MojoDType_bool;
        default:
            mj_panic(false, "Unexpected `rhs` type " << Typed::gTypeString[type]);
    }
}

} // namespace mojo
