/************************************************************************
 ************************************************************************
    FAUST compiler
    Copyright (C) 2021 GRAME, Centre National de Creation Musicale
    ---------------------------------------------------------------------
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation; either version 2.1 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 ************************************************************************
 ************************************************************************/

/** @file compiler/generator/mojo/mojo_vec_instructions.cpp **/

// mojo
#include "mojo_instructions.hh"

// Mojo vectorial instruction visitor implementation. 

inline namespace mojo {

using namespace std;

using VecVisitor  = MojoVecInstVisitor;
using BaseVisitor = MojoInstVisitor;
using DType       = VecVisitor::DType;

MojoVecInstVisitor::MojoVecInstVisitor(OStream* out, String const& structName, int tab)
    : BaseVisitor(out, structName, tab)
{
    gSIMDEmit = false;
    gSIMDWide = false;
    gSIMDSize = gGlobal->gVecSize;
    gCurAddrs = "";
    gCurWidth = "";
    gCurIndex = nullptr;
    gUseWidth = false;
}

MojoVecInstVisitor::~MojoVecInstVisitor() {}

void VecVisitor::visit(IfInst* inst)
{   /* do not generate remaining frames */   }

void VecVisitor::visit(Int32NumInst* inst)
{
    mj_simd_emit_check(); *fOut << "S32Vec(" << inst->fNum << ")";
}

void VecVisitor::visit(BoolNumInst* inst)
{
    mj_simd_emit_check(); *fOut << "S32Vec(" << checkFloat(inst->fNum) << ")";
}

void VecVisitor::visit(DoubleNumInst* inst)
{
    mj_simd_emit_check(); *fOut << "F64Vec(" << checkDouble(inst->fNum) << ")";
}

void VecVisitor::visit(FloatNumInst* inst)
{
    mj_simd_emit_check(); *fOut << "F32Vec(" << checkFloat(inst->fNum) << ")";
}

void VecVisitor::visit(DeclareVarInst* inst)
{
    if (inst->getName().find("vsize") != String::npos) {
        return;  // explicitly generated by the `MojoVecCodeContainer`
    }
    BaseVisitor::visit(inst);
}

void VecVisitor::visit(NamedAddress* inst)
{
    if (inst->isLoop()) {
        mj_scalar_visit(inst); return; // NOTE:(manu) #1 Here using `visit(inst)`
    }
    BaseVisitor::visit(inst);
}

void VecVisitor::visit(CastInst* inst)
{
    mj_simd_emit_check();
    Typed::VarType type = inst->fType->getType();
    if (auto* binop = dycast(BinopInst*, inst->fInst)) {
        if (isBoolOpcode(binop->fOpcode)) {
            inst->fInst->accept(this);
            return;
        }
    }
    *fOut << "(";
    inst->fInst->accept(this);
    switch (type) {
        case Typed::kFloatMacro: *fOut << ").cast[dfaust]()"; break;
        case Typed::kFloat:      *fOut << ").cast[f32]()";    break;
        case Typed::kDouble:     *fOut << ").cast[f64]()";    break;
        case Typed::kInt32:      *fOut << ").cast[s32]()";    break;
        default:
            mj_panic(false, "`inst` has unexpected type " << Typed::gTypeString[type]);
    }
}

void VecVisitor::visit(BinopInst* inst)
{
    mj_simd_emit_check();
    b32 is_cmp = isBoolOpcode(inst->fOpcode);
    if (is_cmp) {
        *fOut << "S32Vec(";
    }
    *fOut << "(";
    inst->fInst1->accept(this);
    *fOut << ") " << gBinOpTable[inst->fOpcode]->fName << " (";
    inst->fInst2->accept(this);
    *fOut << ")";
    if (is_cmp) {
        *fOut << ")";
    }
}

b32 VecVisitor::visitIndex(ValueInst* inst)
{
    if (auto* load = dycast(LoadVarInst*, inst)) {
        if (load->fAddress->getName() == gCurIndex->getName()) return false;
    }
    if (auto* binop = dycast(BinopInst*, inst)) {
        String opc = gBinOpTable[binop->fOpcode]->fName;
        auto* lhs = dycast(LoadVarInst*, binop->fInst1);
        auto* rhs = dycast(LoadVarInst*, binop->fInst2);
        if (lhs && lhs->fAddress->getName() == gCurIndex->getName()) {
            *fOut << ", " << (opc == "-" ? "- " : "");
            mj_scalar_accept(binop->fInst2);
            return true;
        }
        if (rhs && rhs->fAddress->getName() == gCurIndex->getName()) {
            *fOut << ", ";
            mj_scalar_accept(binop->fInst1);
            return true;
        }
    }
    *fOut << ", ";
    mj_scalar_accept(inst);
    return true;
}

void VecVisitor::visit(IndexedAddress* inst)
{
    mj_simd_emit_check();
    Address* addr = inst->fAddress;
    String name = snakeCase(addr->getName());
    name = addr->isStruct() ? "dsp." + name : name;
    String func = "vload" + (gUseWidth  ? "[" + gCurWidth + "]" : "");
    *fOut << func << "(" << name;
    b32 has_index = visitIndex(inst->getIndex());
    if (gSIMDWide) {
        *fOut << (has_index ? " + wsize" : ", wsize");
    }
    *fOut << ")";
}

void VecVisitor::visit(ForLoopInst* inst)
{
    if (inst->fCode->size() == 0) {
        return;
    }

    if (inst->fInit->getName().find("vindex") != String::npos) {
        return visitMain(inst);
    }

    if (inst->fIsRecursive) {
        return visitScalar(inst);
    }

    auto* ini_inst = dycast(DeclareVarInst*, inst->fInit);
    mj_panic(ini_inst, "Expected `inst` to be `DeclareVarInst`");
    gCurIndex = ini_inst->fAddress;

    if (inst->fCode->size() == 2) {
        visitBargraphUpdate(inst);
        return;
    }

    if (inst->fCode->size() > 2) {
        visitBargraphMulti(inst);
    }

    auto* store = dycast(StoreVarInst*, inst->fCode->back());
    mj_panic(store, "Expected final instruction to be a `StoreVarInst`");

    Address* lhs = store->fAddress;
    ValueInst* rhs = store->fValue;
    gCurAddrs = snakeCase(lhs->getName());
    gCurAddrs = lhs->isStruct() ? "dsp." + gCurAddrs : gCurAddrs;
    DType lhs_type = getMojoDType(rhs);
    DType rhs_type = lhs_type;
    if (auto* cast_inst = dycast(CastInst*, rhs)) {
        rhs_type = getMojoDType(cast_inst->fInst);
    }

    if (not isVectorizable(lhs)) {
        visitScalar(inst);
        goto End_Loop;
    }

    if (isScalarValue(rhs)) {
        visitBroadcast(store);
        goto End_Loop;
    }

    if (not isVectorizable(rhs)) {
        visitScalar(inst);
        goto End_Loop;
    }

    if (lhs_type == DType_f64) {
        visitSplit(store);
        goto End_Loop;
    }

    if (rhs_type == DType_f64) {
        visitJoin(store);
        goto End_Loop;
    }

    visitStore(store);

End_Loop:
    *fOut << wnextl(fTab);
    gCurIndex = nullptr;
    gCurAddrs.clear();
    gCurWidth.clear();
}

void VecVisitor::visitStore(StoreVarInst* inst)
{
    *fOut << "vstore(" << gCurAddrs << ", ";
    mj_simd_emit_accept(inst->fValue);
    *fOut << ")";
}

void MojoVecInstVisitor::visitMain(ForLoopInst* inst)
{
    *fOut << "while vindex <= end:" << wnextl(fTab += 1);
    inst->fCode->accept(this);
    fTab -= 1;
}

void MojoVecInstVisitor::visitScalar(ForLoopInst* inst)
{
    *fOut << "comptime for i in range(vsize):" << wnextl(fTab += 1);
    mj_scalar_accept(inst->fCode);
    fTab -= 1;
    wrewind(fOut);
}

void VecVisitor::visitBroadcast(StoreVarInst* inst)
{
    *fOut << "vstore[wfaust](" << gCurAddrs << ", ";
    mj_simd_emit_accept(inst->fValue);
    *fOut << ")";
}

void VecVisitor::visitBargraphUpdate(ForLoopInst* inst)
{
    auto* store_1 = dycast(StoreVarInst*, inst->fCode->front());
    auto* store_2 = dycast(StoreVarInst*, inst->fCode->back());
    String bar = snakeCase(store_1->fAddress->getName());
    String out = snakeCase(store_2->fAddress->getName());
    DType lhs_type = getMojoDType(store_2->fValue);
    ValueInst* value = store_1->fValue;

    mj_simd_emit_set(true);
    if (lhs_type == DType_f64) {
        auto* cast_inst = dycast(CastInst*, value);
        mj_panic(cast_inst, "Expected bargraph value to be a `CastInst`");
        value = cast_inst->fInst;
        *fOut << "vstore(" << out << ", ";
        value->accept(this);
        *fOut << ")" << wnextl(fTab) << "vstore(" << out << ", ";
        mj_simd_wide_accept(value);
        *fOut << ", wsize)" << wnextl(fTab);
        *fOut << "dsp." << bar << " = FaustFloat(" << out << "[vsize - S32(1)])" << wnextl(fTab);
        goto End_Loop;
    }

    *fOut << "vstore(" << out << ", ";
    value->accept(this);
    *fOut << ")" << wnextl(fTab);
    *fOut << "dsp." << bar << " = " << out << "[vsize - S32(1)]" << wnextl(fTab);

End_Loop:
    mj_simd_emit_restore();
    gCurIndex = nullptr;
}

void VecVisitor::visitBargraphMulti(ForLoopInst* inst)
{
    Arr<StoreVarInst*> bars;
    auto* store = dycast(StoreVarInst*, inst->fCode->back());
    mj_panic(store, "Expected final instruction to be a `StoreVarInst`");
    for (auto* line : *inst->fCode) {
        auto* sv_inst = dycast(StoreVarInst*, line);
        mj_panic(sv_inst, "Expected each loop instruction to be a `StoreVarInst`");
        if (sv_inst->fAddress->getName().find("bargraph") != String::npos) {
            bars.push_back(sv_inst);
        }
    }
    mj_panic(bars.size() > 1, "Expected at least two bargraph instruction");
    *fOut << "comptime for i in range(S32(0), vsize):" << wnextl(fTab += 1);
    for (auto* bar : bars) {
        mj_scalar_visit(bar);
    }
    fTab -= 1;
    wrewind(fOut, 1);
}

void VecVisitor::visitJoin(StoreVarInst* inst)
{
    mj_simd_emit_set(true);
    gCurWidth = "W";
    *fOut << "lo = ";
    inst->fValue->accept(this);
    *fOut << wnextl(fTab) << "hi = ";
    mj_simd_wide_accept(inst->fValue);
    *fOut << wnextl(fTab) << "vstore(" << gCurAddrs << ", lo.join(hi))";
    mj_simd_emit_restore();
}

// yes W
// 'rhs' cannot be converted from 'SIMD[s32, simd_width_of[s32]()]' to 'SIMD[s32, simd_width_of[f64]()]' 
// so 'lhs' is SIMD[s32, simd_width_of[f64]()]

// no W
// 'rhs' cannot be converted from 'SIMD[f64, simd_width_of[s32]()]' to 'SIMD[f64, simd_width_of[f64]()]' 
// so 'lhs' is SIMD[f64, simd_width_of[f64]()]

void VecVisitor::visitSplit(StoreVarInst* inst)
{
    mj_simd_emit_set(true);
    gCurWidth = "W";
    *fOut << "vstore(" << gCurAddrs << ", ";
    inst->fValue->accept(this);
    *fOut << ")" << wnextl(fTab) << "vstore(" << gCurAddrs << ", ";
    mj_simd_wide_accept(inst->fValue);
    *fOut << ", wsize)";
    mj_simd_emit_restore();
}

b32 VecVisitor::hasWrappedIndex(Address* addr)
{
    auto* indexed = dycast(IndexedAddress*, addr);
    mj_panic(indexed, "Expected `addr` to be `IndexedAddress`");
    if (indexed->fIndices.size() != 1) {
        return true;
    }
    return isWrappedIndexExpr(indexed->getIndex());
}

b32 VecVisitor::hasWrappedIndex(ValueInst* inst)
{
    if (auto* cast_inst = dycast(CastInst*, inst)) {
        return hasWrappedIndex(cast_inst->fInst);
    }
    if (auto* binop_inst = dycast(BinopInst*, inst)) {
        return hasWrappedIndex(binop_inst->fInst1) || hasWrappedIndex(binop_inst->fInst2);
    }
    if (auto* load_inst = dycast(LoadVarInst*, inst)) {
        if (isScalarAddress(load_inst->fAddress)) {
            return false;
        }
        return hasWrappedIndex(load_inst->fAddress);
    }
    return false;
}

b32 VecVisitor::isWrappedIndexExpr(ValueInst* inst)
{
    if (auto* cast_inst = dycast(CastInst*, inst)) {
        return isWrappedIndexExpr(cast_inst->fInst);
    }
    if (auto* lv_inst = dycast(LoadVarInst*, inst)) {
        return not lv_inst->isSimpleValue();
    }
    if (auto* binop_inst = dycast(BinopInst*, inst)) {
        s32 opcode = binop_inst->fOpcode;
        if (not (opcode == kAdd || opcode == kSub)) {
            return true;
        }
        return isWrappedIndexExpr(binop_inst->fInst1) || isWrappedIndexExpr(binop_inst->fInst2);
    }
    return false;
}

b32 VecVisitor::isScalarValue(ValueInst* inst)
{
    ValueInst* value = inst;
    while (auto cast_inst = dycast(CastInst*, value)) {
       value = cast_inst->fInst;
    }
    auto* lv_inst = dycast(LoadVarInst*, value);
    return lv_inst && lv_inst->isSimpleValue();
}

b32 VecVisitor::isScalarAddress(Address* addr)
{ 
    return not dycast(IndexedAddress*, addr);
}

b32 VecVisitor::isVectorizable(Address* addr)
{
    if (isScalarAddress(addr)) {
        return false;
    }
    return not hasWrappedIndex(addr);
}

b32 VecVisitor::isVectorizable(ValueInst* inst)
{
    return not hasWrappedIndex(inst);
}

DType VecVisitor::getMojoDType(ValueInst* inst)
{
    Typed::VarType type = TypingVisitor::getType(inst);
    if (Typed::isPtrType(type)) {
        type = Typed::getTypeFromPtr(type);
    }
    if (Typed::isVecType(type)) {
        type = Typed::getTypeFromVec(type);
    }
    switch (type) {
        case Typed::kInt32:      return DType_s32;
        case Typed::kFloat:      return DType_f32;
        case Typed::kDouble:     return DType_f64;
        case Typed::kFloatMacro: return DType_dfaust;

        case Typed::kBool:
            mj_debug_fir(std::cerr, inst, "kBool");
            return DType_bool;

        default:
            mj_panic(false, "Unexpected `rhs` type " << Typed::gTypeString[type]);
    }
}

} // namespace mojo
