###############################################################
#
#
#			Android Faust plugin for Unity
#
#
###############################################################


android :
	@~/Documents/Android/ndk-build NDK_PROJECT_PATH=. NDK_APPLICATION_MK=Application.mk FILE=$(FILE)

