#!/bin/bash

for p in $@; do
	if [ $p = "-help" ] || [ $p = "-h" ]; then
		echo "Just run it! It will automatically look for all the .lib files and generate the corresponding documentation in /doc."
		exit 1
	fi
done

FILES="analyzer.lib basic.lib delay.lib misceffect.lib compressor.lib vaeffect.lib phafla.lib reverb.lib envelope.lib miscfilter.lib miscoscillator.lib noise.lib hoa.lib miscmath.lib pm.lib signal.lib route.lib spat.lib synth.lib demo.lib"

for p in $FILES; do
	faust2md $p > doc/${p%.lib}.md
done