======= Container "mydsp" ==========

======= Sub container begin ==========

======= Sub container end ==========

======= User Interface ==========

BlockInst 
	OpenVerticalBox("Tapiir")
	OpenTabBox("0x00")
	OpenHorizontalBox("Tap 0")
	AddVerticalSlider("delay (sec)", fVslider11, 0.0f, 0.0f, 5.0f, 0.00999999978f)
	AddVerticalSlider("gain", fVslider2, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 0", fVslider9, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 1", fVslider10, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 0", fVslider3, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 1", fVslider4, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 2", fVslider5, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 3", fVslider6, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 4", fVslider7, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 5", fVslider8, 0.0f, 0.0f, 1.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Tap 1")
	AddVerticalSlider("delay (sec)", fVslider21, 0.0f, 0.0f, 5.0f, 0.00999999978f)
	AddVerticalSlider("gain", fVslider12, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 0", fVslider19, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 1", fVslider20, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 0", fVslider13, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 1", fVslider14, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 2", fVslider15, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 3", fVslider16, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 4", fVslider17, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 5", fVslider18, 0.0f, 0.0f, 1.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Tap 2")
	AddVerticalSlider("delay (sec)", fVslider31, 0.0f, 0.0f, 5.0f, 0.00999999978f)
	AddVerticalSlider("gain", fVslider22, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 0", fVslider29, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 1", fVslider30, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 0", fVslider23, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 1", fVslider24, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 2", fVslider25, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 3", fVslider26, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 4", fVslider27, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 5", fVslider28, 0.0f, 0.0f, 1.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Tap 3")
	AddVerticalSlider("delay (sec)", fVslider41, 0.0f, 0.0f, 5.0f, 0.00999999978f)
	AddVerticalSlider("gain", fVslider32, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 0", fVslider39, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 1", fVslider40, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 0", fVslider33, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 1", fVslider34, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 2", fVslider35, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 3", fVslider36, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 4", fVslider37, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 5", fVslider38, 0.0f, 0.0f, 1.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Tap 4")
	AddVerticalSlider("delay (sec)", fVslider51, 0.0f, 0.0f, 5.0f, 0.00999999978f)
	AddVerticalSlider("gain", fVslider42, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 0", fVslider49, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 1", fVslider50, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 0", fVslider43, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 1", fVslider44, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 2", fVslider45, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 3", fVslider46, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 4", fVslider47, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 5", fVslider48, 0.0f, 0.0f, 1.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Tap 5")
	AddVerticalSlider("delay (sec)", fVslider61, 0.0f, 0.0f, 5.0f, 0.00999999978f)
	AddVerticalSlider("gain", fVslider52, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 0", fVslider59, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 1", fVslider60, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 0", fVslider53, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 1", fVslider54, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 2", fVslider55, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 3", fVslider56, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 4", fVslider57, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 5", fVslider58, 0.0f, 0.0f, 1.0f, 0.100000001f)
	CloseboxInst
	CloseboxInst
	OpenVerticalBox("outputs")
	OpenHorizontalBox("output 0")
	AddVerticalSlider("gain", fVslider0, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 0", fVslider67, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 1", fVslider68, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 0", fVslider1, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 1", fVslider62, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 2", fVslider63, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 3", fVslider64, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 4", fVslider65, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 5", fVslider66, 0.0f, 0.0f, 1.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("output 1")
	AddVerticalSlider("gain", fVslider69, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 0", fVslider76, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("input 1", fVslider77, 1.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 0", fVslider70, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 1", fVslider71, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 2", fVslider72, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 3", fVslider73, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 4", fVslider74, 0.0f, 0.0f, 1.0f, 0.100000001f)
	AddVerticalSlider("tap 5", fVslider75, 0.0f, 0.0f, 1.0f, 0.100000001f)
	CloseboxInst
	CloseboxInst
	CloseboxInst
	EndBlock

======= Global declarations ==========

BlockInst 
	DeclareFunInst("float", "max_f", "float", dummy0, "float", dummy1)
	DeclareFunInst("float", "min_f", "float", dummy0, "float", dummy1)
	EndBlock

======= Declarations ==========

BlockInst 
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider0)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider1)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider2)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider3)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider4)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider5)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider6)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider7)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider8)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider9)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider10)
	DeclareVarInst(struct, "int", IOTA)
	DeclareVarInst(struct, float, fVec0[1048576])
	DeclareVarInst(struct, "int", fSamplingFreq)
	DeclareVarInst(struct, "float", fConst0)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider11)
	DeclareVarInst(struct, float, fRec0[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider12)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider13)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider14)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider15)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider16)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider17)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider18)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider19)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider20)
	DeclareVarInst(struct, float, fVec1[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider21)
	DeclareVarInst(struct, float, fRec1[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider22)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider23)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider24)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider25)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider26)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider27)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider28)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider29)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider30)
	DeclareVarInst(struct, float, fVec2[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider31)
	DeclareVarInst(struct, float, fRec2[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider32)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider33)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider34)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider35)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider36)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider37)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider38)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider39)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider40)
	DeclareVarInst(struct, float, fVec3[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider41)
	DeclareVarInst(struct, float, fRec3[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider42)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider43)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider44)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider45)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider46)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider47)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider48)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider49)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider50)
	DeclareVarInst(struct, float, fVec4[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider51)
	DeclareVarInst(struct, float, fRec4[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider52)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider53)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider54)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider55)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider56)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider57)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider58)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider59)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider60)
	DeclareVarInst(struct, float, fVec5[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider61)
	DeclareVarInst(struct, float, fRec5[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider62)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider63)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider64)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider65)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider66)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider67)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider68)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider69)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider70)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider71)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider72)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider73)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider74)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider75)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider76)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider77)
	EndBlock

DeclareFunInst("int", "getNumInputs")
	BlockInst 
		RetInst(Int32(2))
		EndBlock
	EndDeclare

DeclareFunInst("int", "getNumOutputs")
	BlockInst 
		RetInst(Int32(2))
		EndBlock
	EndDeclare

DeclareFunInst("int", "getInputRate", "int", channel)
	BlockInst 
		DeclareVarInst(stack, "int", rate)
		SwitchInst LoadVarInst(kFunArgs, channel)
			Case 0
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 1
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Default 
				BlockInst 
					StoreVarInst(stack, rate, Int32(-1))
					EndBlock
				EndCase
			EndSWitch
		RetInst(LoadVarInst(stack, rate))
		EndBlock
	EndDeclare

DeclareFunInst("int", "getOutputRate", "int", channel)
	BlockInst 
		DeclareVarInst(stack, "int", rate)
		SwitchInst LoadVarInst(kFunArgs, channel)
			Case 0
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 1
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Default 
				BlockInst 
					StoreVarInst(stack, rate, Int32(-1))
					EndBlock
				EndCase
			EndSWitch
		RetInst(LoadVarInst(stack, rate))
		EndBlock
	EndDeclare

======= Init ==========

BlockInst 
	StoreVarInst(struct, fSamplingFreq, LoadVarInst(kFunArgs, samplingFreq))
	StoreVarInst(struct, fConst0, FunCallInst("min_f", Float(192000.0f), FunCallInst("max_f", Float(1.0f), CastInst("float", LoadVarInst(struct, fSamplingFreq)))))
	EndBlock

======= ResetUI ==========

BlockInst 
	StoreVarInst(struct, fVslider0, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider1, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider2, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider3, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider4, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider5, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider6, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider7, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider8, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider9, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider10, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider11, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider12, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider13, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider14, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider15, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider16, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider17, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider18, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider19, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider20, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider21, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider22, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider23, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider24, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider25, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider26, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider27, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider28, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider29, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider30, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider31, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider32, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider33, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider34, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider35, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider36, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider37, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider38, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider39, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider40, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider41, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider42, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider43, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider44, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider45, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider46, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider47, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider48, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider49, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider50, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider51, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider52, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider53, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider54, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider55, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider56, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider57, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider58, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider59, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider60, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider61, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider62, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider63, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider64, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider65, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider66, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider67, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider68, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider69, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider70, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider71, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider72, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider73, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider74, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider75, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider76, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider77, CastInst("FAUSTFLOAT", Double(1.0f)))
	EndBlock

======= Clear ==========

BlockInst 
	StoreVarInst(struct, IOTA, Int32(0))
	ForLoopInst 
		DeclareVarInst(loop, "int", l0, Int32(0))
		BinopInst("<", LoadVarInst(loop, l0), Int32(1048576))
		StoreVarInst(loop, l0, BinopInst("+", LoadVarInst(loop, l0), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec0[LoadVarInst(loop, l0)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l1, Int32(0))
		BinopInst("<", LoadVarInst(loop, l1), Int32(2))
		StoreVarInst(loop, l1, BinopInst("+", LoadVarInst(loop, l1), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec0[LoadVarInst(loop, l1)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l2, Int32(0))
		BinopInst("<", LoadVarInst(loop, l2), Int32(1048576))
		StoreVarInst(loop, l2, BinopInst("+", LoadVarInst(loop, l2), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec1[LoadVarInst(loop, l2)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l3, Int32(0))
		BinopInst("<", LoadVarInst(loop, l3), Int32(2))
		StoreVarInst(loop, l3, BinopInst("+", LoadVarInst(loop, l3), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec1[LoadVarInst(loop, l3)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l4, Int32(0))
		BinopInst("<", LoadVarInst(loop, l4), Int32(1048576))
		StoreVarInst(loop, l4, BinopInst("+", LoadVarInst(loop, l4), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec2[LoadVarInst(loop, l4)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l5, Int32(0))
		BinopInst("<", LoadVarInst(loop, l5), Int32(2))
		StoreVarInst(loop, l5, BinopInst("+", LoadVarInst(loop, l5), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec2[LoadVarInst(loop, l5)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l6, Int32(0))
		BinopInst("<", LoadVarInst(loop, l6), Int32(1048576))
		StoreVarInst(loop, l6, BinopInst("+", LoadVarInst(loop, l6), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec3[LoadVarInst(loop, l6)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l7, Int32(0))
		BinopInst("<", LoadVarInst(loop, l7), Int32(2))
		StoreVarInst(loop, l7, BinopInst("+", LoadVarInst(loop, l7), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec3[LoadVarInst(loop, l7)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l8, Int32(0))
		BinopInst("<", LoadVarInst(loop, l8), Int32(1048576))
		StoreVarInst(loop, l8, BinopInst("+", LoadVarInst(loop, l8), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec4[LoadVarInst(loop, l8)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l9, Int32(0))
		BinopInst("<", LoadVarInst(loop, l9), Int32(2))
		StoreVarInst(loop, l9, BinopInst("+", LoadVarInst(loop, l9), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec4[LoadVarInst(loop, l9)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l10, Int32(0))
		BinopInst("<", LoadVarInst(loop, l10), Int32(1048576))
		StoreVarInst(loop, l10, BinopInst("+", LoadVarInst(loop, l10), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec5[LoadVarInst(loop, l10)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l11, Int32(0))
		BinopInst("<", LoadVarInst(loop, l11), Int32(2))
		StoreVarInst(loop, l11, BinopInst("+", LoadVarInst(loop, l11), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec5[LoadVarInst(loop, l11)], Float(0.0f))
			EndBlock
		EndForLoop
	EndBlock

======= Compute control ==========

Instructions complexity
Load = 88
Store = 0
Binop = 6
Numbers = 12
Declare = 82
Cast = 84
Select = 0
Loop = 0
Funcall = 12

BlockInst 
	DeclareVarInst(stack, FAUSTFLOAT*, input0, LoadVarInst(kFunArgs, inputs[Int32(0)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input1, LoadVarInst(kFunArgs, inputs[Int32(1)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output0, LoadVarInst(kFunArgs, outputs[Int32(0)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output1, LoadVarInst(kFunArgs, outputs[Int32(1)]))
	DeclareVarInst(stack, "float", fSlow0, CastInst("float", LoadVarInst(struct, fVslider0)))
	DeclareVarInst(stack, "float", fSlow1, CastInst("float", LoadVarInst(struct, fVslider1)))
	DeclareVarInst(stack, "float", fSlow2, CastInst("float", LoadVarInst(struct, fVslider2)))
	DeclareVarInst(stack, "float", fSlow3, CastInst("float", LoadVarInst(struct, fVslider3)))
	DeclareVarInst(stack, "float", fSlow4, CastInst("float", LoadVarInst(struct, fVslider4)))
	DeclareVarInst(stack, "float", fSlow5, CastInst("float", LoadVarInst(struct, fVslider5)))
	DeclareVarInst(stack, "float", fSlow6, CastInst("float", LoadVarInst(struct, fVslider6)))
	DeclareVarInst(stack, "float", fSlow7, CastInst("float", LoadVarInst(struct, fVslider7)))
	DeclareVarInst(stack, "float", fSlow8, CastInst("float", LoadVarInst(struct, fVslider8)))
	DeclareVarInst(stack, "float", fSlow9, CastInst("float", LoadVarInst(struct, fVslider9)))
	DeclareVarInst(stack, "float", fSlow10, CastInst("float", LoadVarInst(struct, fVslider10)))
	DeclareVarInst(stack, "int", iSlow11, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider11)))))))
	DeclareVarInst(stack, "float", fSlow12, CastInst("float", LoadVarInst(struct, fVslider12)))
	DeclareVarInst(stack, "float", fSlow13, CastInst("float", LoadVarInst(struct, fVslider13)))
	DeclareVarInst(stack, "float", fSlow14, CastInst("float", LoadVarInst(struct, fVslider14)))
	DeclareVarInst(stack, "float", fSlow15, CastInst("float", LoadVarInst(struct, fVslider15)))
	DeclareVarInst(stack, "float", fSlow16, CastInst("float", LoadVarInst(struct, fVslider16)))
	DeclareVarInst(stack, "float", fSlow17, CastInst("float", LoadVarInst(struct, fVslider17)))
	DeclareVarInst(stack, "float", fSlow18, CastInst("float", LoadVarInst(struct, fVslider18)))
	DeclareVarInst(stack, "float", fSlow19, CastInst("float", LoadVarInst(struct, fVslider19)))
	DeclareVarInst(stack, "float", fSlow20, CastInst("float", LoadVarInst(struct, fVslider20)))
	DeclareVarInst(stack, "int", iSlow21, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider21)))))))
	DeclareVarInst(stack, "float", fSlow22, CastInst("float", LoadVarInst(struct, fVslider22)))
	DeclareVarInst(stack, "float", fSlow23, CastInst("float", LoadVarInst(struct, fVslider23)))
	DeclareVarInst(stack, "float", fSlow24, CastInst("float", LoadVarInst(struct, fVslider24)))
	DeclareVarInst(stack, "float", fSlow25, CastInst("float", LoadVarInst(struct, fVslider25)))
	DeclareVarInst(stack, "float", fSlow26, CastInst("float", LoadVarInst(struct, fVslider26)))
	DeclareVarInst(stack, "float", fSlow27, CastInst("float", LoadVarInst(struct, fVslider27)))
	DeclareVarInst(stack, "float", fSlow28, CastInst("float", LoadVarInst(struct, fVslider28)))
	DeclareVarInst(stack, "float", fSlow29, CastInst("float", LoadVarInst(struct, fVslider29)))
	DeclareVarInst(stack, "float", fSlow30, CastInst("float", LoadVarInst(struct, fVslider30)))
	DeclareVarInst(stack, "int", iSlow31, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider31)))))))
	DeclareVarInst(stack, "float", fSlow32, CastInst("float", LoadVarInst(struct, fVslider32)))
	DeclareVarInst(stack, "float", fSlow33, CastInst("float", LoadVarInst(struct, fVslider33)))
	DeclareVarInst(stack, "float", fSlow34, CastInst("float", LoadVarInst(struct, fVslider34)))
	DeclareVarInst(stack, "float", fSlow35, CastInst("float", LoadVarInst(struct, fVslider35)))
	DeclareVarInst(stack, "float", fSlow36, CastInst("float", LoadVarInst(struct, fVslider36)))
	DeclareVarInst(stack, "float", fSlow37, CastInst("float", LoadVarInst(struct, fVslider37)))
	DeclareVarInst(stack, "float", fSlow38, CastInst("float", LoadVarInst(struct, fVslider38)))
	DeclareVarInst(stack, "float", fSlow39, CastInst("float", LoadVarInst(struct, fVslider39)))
	DeclareVarInst(stack, "float", fSlow40, CastInst("float", LoadVarInst(struct, fVslider40)))
	DeclareVarInst(stack, "int", iSlow41, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider41)))))))
	DeclareVarInst(stack, "float", fSlow42, CastInst("float", LoadVarInst(struct, fVslider42)))
	DeclareVarInst(stack, "float", fSlow43, CastInst("float", LoadVarInst(struct, fVslider43)))
	DeclareVarInst(stack, "float", fSlow44, CastInst("float", LoadVarInst(struct, fVslider44)))
	DeclareVarInst(stack, "float", fSlow45, CastInst("float", LoadVarInst(struct, fVslider45)))
	DeclareVarInst(stack, "float", fSlow46, CastInst("float", LoadVarInst(struct, fVslider46)))
	DeclareVarInst(stack, "float", fSlow47, CastInst("float", LoadVarInst(struct, fVslider47)))
	DeclareVarInst(stack, "float", fSlow48, CastInst("float", LoadVarInst(struct, fVslider48)))
	DeclareVarInst(stack, "float", fSlow49, CastInst("float", LoadVarInst(struct, fVslider49)))
	DeclareVarInst(stack, "float", fSlow50, CastInst("float", LoadVarInst(struct, fVslider50)))
	DeclareVarInst(stack, "int", iSlow51, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider51)))))))
	DeclareVarInst(stack, "float", fSlow52, CastInst("float", LoadVarInst(struct, fVslider52)))
	DeclareVarInst(stack, "float", fSlow53, CastInst("float", LoadVarInst(struct, fVslider53)))
	DeclareVarInst(stack, "float", fSlow54, CastInst("float", LoadVarInst(struct, fVslider54)))
	DeclareVarInst(stack, "float", fSlow55, CastInst("float", LoadVarInst(struct, fVslider55)))
	DeclareVarInst(stack, "float", fSlow56, CastInst("float", LoadVarInst(struct, fVslider56)))
	DeclareVarInst(stack, "float", fSlow57, CastInst("float", LoadVarInst(struct, fVslider57)))
	DeclareVarInst(stack, "float", fSlow58, CastInst("float", LoadVarInst(struct, fVslider58)))
	DeclareVarInst(stack, "float", fSlow59, CastInst("float", LoadVarInst(struct, fVslider59)))
	DeclareVarInst(stack, "float", fSlow60, CastInst("float", LoadVarInst(struct, fVslider60)))
	DeclareVarInst(stack, "int", iSlow61, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider61)))))))
	DeclareVarInst(stack, "float", fSlow62, CastInst("float", LoadVarInst(struct, fVslider62)))
	DeclareVarInst(stack, "float", fSlow63, CastInst("float", LoadVarInst(struct, fVslider63)))
	DeclareVarInst(stack, "float", fSlow64, CastInst("float", LoadVarInst(struct, fVslider64)))
	DeclareVarInst(stack, "float", fSlow65, CastInst("float", LoadVarInst(struct, fVslider65)))
	DeclareVarInst(stack, "float", fSlow66, CastInst("float", LoadVarInst(struct, fVslider66)))
	DeclareVarInst(stack, "float", fSlow67, CastInst("float", LoadVarInst(struct, fVslider67)))
	DeclareVarInst(stack, "float", fSlow68, CastInst("float", LoadVarInst(struct, fVslider68)))
	DeclareVarInst(stack, "float", fSlow69, CastInst("float", LoadVarInst(struct, fVslider69)))
	DeclareVarInst(stack, "float", fSlow70, CastInst("float", LoadVarInst(struct, fVslider70)))
	DeclareVarInst(stack, "float", fSlow71, CastInst("float", LoadVarInst(struct, fVslider71)))
	DeclareVarInst(stack, "float", fSlow72, CastInst("float", LoadVarInst(struct, fVslider72)))
	DeclareVarInst(stack, "float", fSlow73, CastInst("float", LoadVarInst(struct, fVslider73)))
	DeclareVarInst(stack, "float", fSlow74, CastInst("float", LoadVarInst(struct, fVslider74)))
	DeclareVarInst(stack, "float", fSlow75, CastInst("float", LoadVarInst(struct, fVslider75)))
	DeclareVarInst(stack, "float", fSlow76, CastInst("float", LoadVarInst(struct, fVslider76)))
	DeclareVarInst(stack, "float", fSlow77, CastInst("float", LoadVarInst(struct, fVslider77)))
	EndBlock

======= Compute DSP ==========

Instructions complexity
Load = 162
Store = 22
Binop = 137
Numbers = 21
Declare = 3
Cast = 4
Select = 0
Loop = 1
Funcall = 0

ForLoopInst 
	DeclareVarInst(loop, "int", i, Int32(0))
	BinopInst("<", LoadVarInst(loop, i), LoadVarInst(kFunArgs, count))
	StoreVarInst(loop, i, BinopInst("+", LoadVarInst(loop, i), Int32(1)))
	BlockInst 
		DeclareVarInst(stack, "float", fTemp0, CastInst("float", LoadVarInst(stack, input0[LoadVarInst(loop, i)])))
		DeclareVarInst(stack, "float", fTemp1, CastInst("float", LoadVarInst(stack, input1[LoadVarInst(loop, i)])))
		StoreVarInst(struct, fVec0[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow2), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow3), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow4), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow5), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow6), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow7), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow8), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow9), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow10), LoadVarInst(stack, fTemp1)))))
		StoreVarInst(struct, fRec0[Int32(0)], LoadVarInst(struct, fVec0[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow11)), Int32(1048575))]))
		StoreVarInst(struct, fVec1[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow12), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow13), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow14), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow15), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow16), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow17), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow18), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow19), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow20), LoadVarInst(stack, fTemp1)))))
		StoreVarInst(struct, fRec1[Int32(0)], LoadVarInst(struct, fVec1[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow21)), Int32(1048575))]))
		StoreVarInst(struct, fVec2[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow22), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow23), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow24), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow25), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow26), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow27), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow28), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow29), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow30), LoadVarInst(stack, fTemp1)))))
		StoreVarInst(struct, fRec2[Int32(0)], LoadVarInst(struct, fVec2[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow31)), Int32(1048575))]))
		StoreVarInst(struct, fVec3[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow32), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow33), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow34), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow35), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow36), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow37), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow38), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow39), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow40), LoadVarInst(stack, fTemp1)))))
		StoreVarInst(struct, fRec3[Int32(0)], LoadVarInst(struct, fVec3[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow41)), Int32(1048575))]))
		StoreVarInst(struct, fVec4[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow42), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow43), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow44), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow45), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow46), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow47), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow48), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow49), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow50), LoadVarInst(stack, fTemp1)))))
		StoreVarInst(struct, fRec4[Int32(0)], LoadVarInst(struct, fVec4[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow51)), Int32(1048575))]))
		StoreVarInst(struct, fVec5[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow52), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow53), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow54), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow55), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow56), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow57), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow58), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow59), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow60), LoadVarInst(stack, fTemp1)))))
		StoreVarInst(struct, fRec5[Int32(0)], LoadVarInst(struct, fVec5[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow61)), Int32(1048575))]))
		StoreVarInst(stack, output0[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("*", LoadVarInst(stack, fSlow0), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow1), LoadVarInst(struct, fRec0[Int32(0)])), BinopInst("*", LoadVarInst(stack, fSlow62), LoadVarInst(struct, fRec1[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow63), LoadVarInst(struct, fRec2[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow64), LoadVarInst(struct, fRec3[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow65), LoadVarInst(struct, fRec4[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow66), LoadVarInst(struct, fRec5[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow67), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow68), LoadVarInst(stack, fTemp1))))))
		StoreVarInst(stack, output1[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("*", LoadVarInst(stack, fSlow69), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow70), LoadVarInst(struct, fRec0[Int32(0)])), BinopInst("*", LoadVarInst(stack, fSlow71), LoadVarInst(struct, fRec1[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow72), LoadVarInst(struct, fRec2[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow73), LoadVarInst(struct, fRec3[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow74), LoadVarInst(struct, fRec4[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow75), LoadVarInst(struct, fRec5[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow76), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow77), LoadVarInst(stack, fTemp1))))))
		StoreVarInst(struct, IOTA, BinopInst("+", LoadVarInst(struct, IOTA), Int32(1)))
		StoreVarInst(struct, fRec0[Int32(1)], LoadVarInst(struct, fRec0[Int32(0)]))
		StoreVarInst(struct, fRec1[Int32(1)], LoadVarInst(struct, fRec1[Int32(0)]))
		StoreVarInst(struct, fRec2[Int32(1)], LoadVarInst(struct, fRec2[Int32(0)]))
		StoreVarInst(struct, fRec3[Int32(1)], LoadVarInst(struct, fRec3[Int32(0)]))
		StoreVarInst(struct, fRec4[Int32(1)], LoadVarInst(struct, fRec4[Int32(0)]))
		StoreVarInst(struct, fRec5[Int32(1)], LoadVarInst(struct, fRec5[Int32(0)]))
		EndBlock
	EndForLoop

======= Flatten FIR ==========

BlockInst 
	========== Declaration part ==========
	DeclareFunInst("float", "max_f", "float", dummy0, "float", dummy1)
	DeclareFunInst("float", "min_f", "float", dummy0, "float", dummy1)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider0)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider1)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider2)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider3)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider4)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider5)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider6)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider7)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider8)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider9)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider10)
	DeclareVarInst(struct, "int", IOTA)
	DeclareVarInst(struct, float, fVec0[1048576])
	DeclareVarInst(struct, "int", fSamplingFreq)
	DeclareVarInst(struct, "float", fConst0)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider11)
	DeclareVarInst(struct, float, fRec0[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider12)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider13)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider14)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider15)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider16)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider17)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider18)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider19)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider20)
	DeclareVarInst(struct, float, fVec1[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider21)
	DeclareVarInst(struct, float, fRec1[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider22)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider23)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider24)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider25)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider26)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider27)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider28)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider29)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider30)
	DeclareVarInst(struct, float, fVec2[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider31)
	DeclareVarInst(struct, float, fRec2[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider32)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider33)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider34)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider35)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider36)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider37)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider38)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider39)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider40)
	DeclareVarInst(struct, float, fVec3[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider41)
	DeclareVarInst(struct, float, fRec3[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider42)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider43)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider44)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider45)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider46)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider47)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider48)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider49)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider50)
	DeclareVarInst(struct, float, fVec4[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider51)
	DeclareVarInst(struct, float, fRec4[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider52)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider53)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider54)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider55)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider56)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider57)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider58)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider59)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider60)
	DeclareVarInst(struct, float, fVec5[1048576])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider61)
	DeclareVarInst(struct, float, fRec5[2])
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider62)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider63)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider64)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider65)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider66)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider67)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider68)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider69)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider70)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider71)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider72)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider73)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider74)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider75)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider76)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider77)
	========== Init method ==========
	StoreVarInst(struct, fSamplingFreq, LoadVarInst(kFunArgs, samplingFreq))
	StoreVarInst(struct, fConst0, FunCallInst("min_f", Float(192000.0f), FunCallInst("max_f", Float(1.0f), CastInst("float", LoadVarInst(struct, fSamplingFreq)))))
	StoreVarInst(struct, fVslider0, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider1, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider2, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider3, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider4, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider5, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider6, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider7, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider8, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider9, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider10, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider11, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider12, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider13, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider14, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider15, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider16, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider17, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider18, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider19, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider20, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider21, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider22, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider23, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider24, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider25, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider26, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider27, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider28, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider29, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider30, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider31, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider32, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider33, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider34, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider35, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider36, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider37, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider38, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider39, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider40, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider41, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider42, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider43, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider44, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider45, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider46, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider47, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider48, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider49, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider50, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider51, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider52, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider53, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider54, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider55, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider56, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider57, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider58, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider59, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider60, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider61, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider62, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider63, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider64, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider65, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider66, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider67, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider68, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider69, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider70, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider71, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider72, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider73, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider74, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider75, CastInst("FAUSTFLOAT", Double(0.0f)))
	StoreVarInst(struct, fVslider76, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, fVslider77, CastInst("FAUSTFLOAT", Double(1.0f)))
	StoreVarInst(struct, IOTA, Int32(0))
	ForLoopInst 
		DeclareVarInst(loop, "int", l0, Int32(0))
		BinopInst("<", LoadVarInst(loop, l0), Int32(1048576))
		StoreVarInst(loop, l0, BinopInst("+", LoadVarInst(loop, l0), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec0[LoadVarInst(loop, l0)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l1, Int32(0))
		BinopInst("<", LoadVarInst(loop, l1), Int32(2))
		StoreVarInst(loop, l1, BinopInst("+", LoadVarInst(loop, l1), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec0[LoadVarInst(loop, l1)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l2, Int32(0))
		BinopInst("<", LoadVarInst(loop, l2), Int32(1048576))
		StoreVarInst(loop, l2, BinopInst("+", LoadVarInst(loop, l2), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec1[LoadVarInst(loop, l2)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l3, Int32(0))
		BinopInst("<", LoadVarInst(loop, l3), Int32(2))
		StoreVarInst(loop, l3, BinopInst("+", LoadVarInst(loop, l3), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec1[LoadVarInst(loop, l3)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l4, Int32(0))
		BinopInst("<", LoadVarInst(loop, l4), Int32(1048576))
		StoreVarInst(loop, l4, BinopInst("+", LoadVarInst(loop, l4), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec2[LoadVarInst(loop, l4)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l5, Int32(0))
		BinopInst("<", LoadVarInst(loop, l5), Int32(2))
		StoreVarInst(loop, l5, BinopInst("+", LoadVarInst(loop, l5), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec2[LoadVarInst(loop, l5)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l6, Int32(0))
		BinopInst("<", LoadVarInst(loop, l6), Int32(1048576))
		StoreVarInst(loop, l6, BinopInst("+", LoadVarInst(loop, l6), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec3[LoadVarInst(loop, l6)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l7, Int32(0))
		BinopInst("<", LoadVarInst(loop, l7), Int32(2))
		StoreVarInst(loop, l7, BinopInst("+", LoadVarInst(loop, l7), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec3[LoadVarInst(loop, l7)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l8, Int32(0))
		BinopInst("<", LoadVarInst(loop, l8), Int32(1048576))
		StoreVarInst(loop, l8, BinopInst("+", LoadVarInst(loop, l8), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec4[LoadVarInst(loop, l8)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l9, Int32(0))
		BinopInst("<", LoadVarInst(loop, l9), Int32(2))
		StoreVarInst(loop, l9, BinopInst("+", LoadVarInst(loop, l9), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec4[LoadVarInst(loop, l9)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l10, Int32(0))
		BinopInst("<", LoadVarInst(loop, l10), Int32(1048576))
		StoreVarInst(loop, l10, BinopInst("+", LoadVarInst(loop, l10), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fVec5[LoadVarInst(loop, l10)], Float(0.0f))
			EndBlock
		EndForLoop
	ForLoopInst 
		DeclareVarInst(loop, "int", l11, Int32(0))
		BinopInst("<", LoadVarInst(loop, l11), Int32(2))
		StoreVarInst(loop, l11, BinopInst("+", LoadVarInst(loop, l11), Int32(1)))
		BlockInst 
			StoreVarInst(struct, fRec5[LoadVarInst(loop, l11)], Float(0.0f))
			EndBlock
		EndForLoop
	========== Static init method ==========
	========== Subcontainers ==========
	========== Compute control ==========
	DeclareVarInst(stack, FAUSTFLOAT*, input0, LoadVarInst(kFunArgs, inputs[Int32(0)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input1, LoadVarInst(kFunArgs, inputs[Int32(1)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output0, LoadVarInst(kFunArgs, outputs[Int32(0)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output1, LoadVarInst(kFunArgs, outputs[Int32(1)]))
	DeclareVarInst(stack, "float", fSlow0, CastInst("float", LoadVarInst(struct, fVslider0)))
	DeclareVarInst(stack, "float", fSlow1, CastInst("float", LoadVarInst(struct, fVslider1)))
	DeclareVarInst(stack, "float", fSlow2, CastInst("float", LoadVarInst(struct, fVslider2)))
	DeclareVarInst(stack, "float", fSlow3, CastInst("float", LoadVarInst(struct, fVslider3)))
	DeclareVarInst(stack, "float", fSlow4, CastInst("float", LoadVarInst(struct, fVslider4)))
	DeclareVarInst(stack, "float", fSlow5, CastInst("float", LoadVarInst(struct, fVslider5)))
	DeclareVarInst(stack, "float", fSlow6, CastInst("float", LoadVarInst(struct, fVslider6)))
	DeclareVarInst(stack, "float", fSlow7, CastInst("float", LoadVarInst(struct, fVslider7)))
	DeclareVarInst(stack, "float", fSlow8, CastInst("float", LoadVarInst(struct, fVslider8)))
	DeclareVarInst(stack, "float", fSlow9, CastInst("float", LoadVarInst(struct, fVslider9)))
	DeclareVarInst(stack, "float", fSlow10, CastInst("float", LoadVarInst(struct, fVslider10)))
	DeclareVarInst(stack, "int", iSlow11, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider11)))))))
	DeclareVarInst(stack, "float", fSlow12, CastInst("float", LoadVarInst(struct, fVslider12)))
	DeclareVarInst(stack, "float", fSlow13, CastInst("float", LoadVarInst(struct, fVslider13)))
	DeclareVarInst(stack, "float", fSlow14, CastInst("float", LoadVarInst(struct, fVslider14)))
	DeclareVarInst(stack, "float", fSlow15, CastInst("float", LoadVarInst(struct, fVslider15)))
	DeclareVarInst(stack, "float", fSlow16, CastInst("float", LoadVarInst(struct, fVslider16)))
	DeclareVarInst(stack, "float", fSlow17, CastInst("float", LoadVarInst(struct, fVslider17)))
	DeclareVarInst(stack, "float", fSlow18, CastInst("float", LoadVarInst(struct, fVslider18)))
	DeclareVarInst(stack, "float", fSlow19, CastInst("float", LoadVarInst(struct, fVslider19)))
	DeclareVarInst(stack, "float", fSlow20, CastInst("float", LoadVarInst(struct, fVslider20)))
	DeclareVarInst(stack, "int", iSlow21, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider21)))))))
	DeclareVarInst(stack, "float", fSlow22, CastInst("float", LoadVarInst(struct, fVslider22)))
	DeclareVarInst(stack, "float", fSlow23, CastInst("float", LoadVarInst(struct, fVslider23)))
	DeclareVarInst(stack, "float", fSlow24, CastInst("float", LoadVarInst(struct, fVslider24)))
	DeclareVarInst(stack, "float", fSlow25, CastInst("float", LoadVarInst(struct, fVslider25)))
	DeclareVarInst(stack, "float", fSlow26, CastInst("float", LoadVarInst(struct, fVslider26)))
	DeclareVarInst(stack, "float", fSlow27, CastInst("float", LoadVarInst(struct, fVslider27)))
	DeclareVarInst(stack, "float", fSlow28, CastInst("float", LoadVarInst(struct, fVslider28)))
	DeclareVarInst(stack, "float", fSlow29, CastInst("float", LoadVarInst(struct, fVslider29)))
	DeclareVarInst(stack, "float", fSlow30, CastInst("float", LoadVarInst(struct, fVslider30)))
	DeclareVarInst(stack, "int", iSlow31, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider31)))))))
	DeclareVarInst(stack, "float", fSlow32, CastInst("float", LoadVarInst(struct, fVslider32)))
	DeclareVarInst(stack, "float", fSlow33, CastInst("float", LoadVarInst(struct, fVslider33)))
	DeclareVarInst(stack, "float", fSlow34, CastInst("float", LoadVarInst(struct, fVslider34)))
	DeclareVarInst(stack, "float", fSlow35, CastInst("float", LoadVarInst(struct, fVslider35)))
	DeclareVarInst(stack, "float", fSlow36, CastInst("float", LoadVarInst(struct, fVslider36)))
	DeclareVarInst(stack, "float", fSlow37, CastInst("float", LoadVarInst(struct, fVslider37)))
	DeclareVarInst(stack, "float", fSlow38, CastInst("float", LoadVarInst(struct, fVslider38)))
	DeclareVarInst(stack, "float", fSlow39, CastInst("float", LoadVarInst(struct, fVslider39)))
	DeclareVarInst(stack, "float", fSlow40, CastInst("float", LoadVarInst(struct, fVslider40)))
	DeclareVarInst(stack, "int", iSlow41, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider41)))))))
	DeclareVarInst(stack, "float", fSlow42, CastInst("float", LoadVarInst(struct, fVslider42)))
	DeclareVarInst(stack, "float", fSlow43, CastInst("float", LoadVarInst(struct, fVslider43)))
	DeclareVarInst(stack, "float", fSlow44, CastInst("float", LoadVarInst(struct, fVslider44)))
	DeclareVarInst(stack, "float", fSlow45, CastInst("float", LoadVarInst(struct, fVslider45)))
	DeclareVarInst(stack, "float", fSlow46, CastInst("float", LoadVarInst(struct, fVslider46)))
	DeclareVarInst(stack, "float", fSlow47, CastInst("float", LoadVarInst(struct, fVslider47)))
	DeclareVarInst(stack, "float", fSlow48, CastInst("float", LoadVarInst(struct, fVslider48)))
	DeclareVarInst(stack, "float", fSlow49, CastInst("float", LoadVarInst(struct, fVslider49)))
	DeclareVarInst(stack, "float", fSlow50, CastInst("float", LoadVarInst(struct, fVslider50)))
	DeclareVarInst(stack, "int", iSlow51, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider51)))))))
	DeclareVarInst(stack, "float", fSlow52, CastInst("float", LoadVarInst(struct, fVslider52)))
	DeclareVarInst(stack, "float", fSlow53, CastInst("float", LoadVarInst(struct, fVslider53)))
	DeclareVarInst(stack, "float", fSlow54, CastInst("float", LoadVarInst(struct, fVslider54)))
	DeclareVarInst(stack, "float", fSlow55, CastInst("float", LoadVarInst(struct, fVslider55)))
	DeclareVarInst(stack, "float", fSlow56, CastInst("float", LoadVarInst(struct, fVslider56)))
	DeclareVarInst(stack, "float", fSlow57, CastInst("float", LoadVarInst(struct, fVslider57)))
	DeclareVarInst(stack, "float", fSlow58, CastInst("float", LoadVarInst(struct, fVslider58)))
	DeclareVarInst(stack, "float", fSlow59, CastInst("float", LoadVarInst(struct, fVslider59)))
	DeclareVarInst(stack, "float", fSlow60, CastInst("float", LoadVarInst(struct, fVslider60)))
	DeclareVarInst(stack, "int", iSlow61, CastInst("int", FunCallInst("min_f", Float(524288.0f), FunCallInst("max_f", Float(0.0f), BinopInst("*", LoadVarInst(struct, fConst0), CastInst("float", LoadVarInst(struct, fVslider61)))))))
	DeclareVarInst(stack, "float", fSlow62, CastInst("float", LoadVarInst(struct, fVslider62)))
	DeclareVarInst(stack, "float", fSlow63, CastInst("float", LoadVarInst(struct, fVslider63)))
	DeclareVarInst(stack, "float", fSlow64, CastInst("float", LoadVarInst(struct, fVslider64)))
	DeclareVarInst(stack, "float", fSlow65, CastInst("float", LoadVarInst(struct, fVslider65)))
	DeclareVarInst(stack, "float", fSlow66, CastInst("float", LoadVarInst(struct, fVslider66)))
	DeclareVarInst(stack, "float", fSlow67, CastInst("float", LoadVarInst(struct, fVslider67)))
	DeclareVarInst(stack, "float", fSlow68, CastInst("float", LoadVarInst(struct, fVslider68)))
	DeclareVarInst(stack, "float", fSlow69, CastInst("float", LoadVarInst(struct, fVslider69)))
	DeclareVarInst(stack, "float", fSlow70, CastInst("float", LoadVarInst(struct, fVslider70)))
	DeclareVarInst(stack, "float", fSlow71, CastInst("float", LoadVarInst(struct, fVslider71)))
	DeclareVarInst(stack, "float", fSlow72, CastInst("float", LoadVarInst(struct, fVslider72)))
	DeclareVarInst(stack, "float", fSlow73, CastInst("float", LoadVarInst(struct, fVslider73)))
	DeclareVarInst(stack, "float", fSlow74, CastInst("float", LoadVarInst(struct, fVslider74)))
	DeclareVarInst(stack, "float", fSlow75, CastInst("float", LoadVarInst(struct, fVslider75)))
	DeclareVarInst(stack, "float", fSlow76, CastInst("float", LoadVarInst(struct, fVslider76)))
	DeclareVarInst(stack, "float", fSlow77, CastInst("float", LoadVarInst(struct, fVslider77)))
	========== Compute DSP ==========
	ForLoopInst 
		DeclareVarInst(loop, "int", i, Int32(0))
		BinopInst("<", LoadVarInst(loop, i), LoadVarInst(kFunArgs, count))
		StoreVarInst(loop, i, BinopInst("+", LoadVarInst(loop, i), Int32(1)))
		BlockInst 
			DeclareVarInst(stack, "float", fTemp0, CastInst("float", LoadVarInst(stack, input0[LoadVarInst(loop, i)])))
			DeclareVarInst(stack, "float", fTemp1, CastInst("float", LoadVarInst(stack, input1[LoadVarInst(loop, i)])))
			StoreVarInst(struct, fVec0[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow2), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow3), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow4), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow5), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow6), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow7), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow8), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow9), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow10), LoadVarInst(stack, fTemp1)))))
			StoreVarInst(struct, fRec0[Int32(0)], LoadVarInst(struct, fVec0[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow11)), Int32(1048575))]))
			StoreVarInst(struct, fVec1[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow12), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow13), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow14), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow15), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow16), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow17), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow18), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow19), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow20), LoadVarInst(stack, fTemp1)))))
			StoreVarInst(struct, fRec1[Int32(0)], LoadVarInst(struct, fVec1[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow21)), Int32(1048575))]))
			StoreVarInst(struct, fVec2[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow22), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow23), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow24), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow25), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow26), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow27), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow28), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow29), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow30), LoadVarInst(stack, fTemp1)))))
			StoreVarInst(struct, fRec2[Int32(0)], LoadVarInst(struct, fVec2[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow31)), Int32(1048575))]))
			StoreVarInst(struct, fVec3[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow32), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow33), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow34), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow35), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow36), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow37), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow38), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow39), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow40), LoadVarInst(stack, fTemp1)))))
			StoreVarInst(struct, fRec3[Int32(0)], LoadVarInst(struct, fVec3[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow41)), Int32(1048575))]))
			StoreVarInst(struct, fVec4[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow42), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow43), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow44), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow45), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow46), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow47), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow48), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow49), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow50), LoadVarInst(stack, fTemp1)))))
			StoreVarInst(struct, fRec4[Int32(0)], LoadVarInst(struct, fVec4[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow51)), Int32(1048575))]))
			StoreVarInst(struct, fVec5[BinopInst("&", LoadVarInst(struct, IOTA), Int32(1048575))], BinopInst("*", LoadVarInst(stack, fSlow52), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow53), LoadVarInst(struct, fRec0[Int32(1)])), BinopInst("*", LoadVarInst(stack, fSlow54), LoadVarInst(struct, fRec1[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow55), LoadVarInst(struct, fRec2[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow56), LoadVarInst(struct, fRec3[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow57), LoadVarInst(struct, fRec4[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow58), LoadVarInst(struct, fRec5[Int32(1)]))), BinopInst("*", LoadVarInst(stack, fSlow59), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow60), LoadVarInst(stack, fTemp1)))))
			StoreVarInst(struct, fRec5[Int32(0)], LoadVarInst(struct, fVec5[BinopInst("&", BinopInst("-", LoadVarInst(struct, IOTA), LoadVarInst(stack, iSlow61)), Int32(1048575))]))
			StoreVarInst(stack, output0[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("*", LoadVarInst(stack, fSlow0), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow1), LoadVarInst(struct, fRec0[Int32(0)])), BinopInst("*", LoadVarInst(stack, fSlow62), LoadVarInst(struct, fRec1[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow63), LoadVarInst(struct, fRec2[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow64), LoadVarInst(struct, fRec3[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow65), LoadVarInst(struct, fRec4[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow66), LoadVarInst(struct, fRec5[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow67), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow68), LoadVarInst(stack, fTemp1))))))
			StoreVarInst(stack, output1[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("*", LoadVarInst(stack, fSlow69), BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow70), LoadVarInst(struct, fRec0[Int32(0)])), BinopInst("*", LoadVarInst(stack, fSlow71), LoadVarInst(struct, fRec1[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow72), LoadVarInst(struct, fRec2[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow73), LoadVarInst(struct, fRec3[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow74), LoadVarInst(struct, fRec4[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow75), LoadVarInst(struct, fRec5[Int32(0)]))), BinopInst("*", LoadVarInst(stack, fSlow76), LoadVarInst(stack, fTemp0))), BinopInst("*", LoadVarInst(stack, fSlow77), LoadVarInst(stack, fTemp1))))))
			StoreVarInst(struct, IOTA, BinopInst("+", LoadVarInst(struct, IOTA), Int32(1)))
			StoreVarInst(struct, fRec0[Int32(1)], LoadVarInst(struct, fRec0[Int32(0)]))
			StoreVarInst(struct, fRec1[Int32(1)], LoadVarInst(struct, fRec1[Int32(0)]))
			StoreVarInst(struct, fRec2[Int32(1)], LoadVarInst(struct, fRec2[Int32(0)]))
			StoreVarInst(struct, fRec3[Int32(1)], LoadVarInst(struct, fRec3[Int32(0)]))
			StoreVarInst(struct, fRec4[Int32(1)], LoadVarInst(struct, fRec4[Int32(0)]))
			StoreVarInst(struct, fRec5[Int32(1)], LoadVarInst(struct, fRec5[Int32(0)]))
			EndBlock
		EndForLoop
	EndBlock

======= Object memory footprint ==========

Heap size int = 8 bytes
Heap size int* = 0 bytes
Heap size real = 25166188 bytes
Heap size = 25166196 bytes
Stack size in compute = 344 bytes

