# ==============================================================================
# Faust to Mojo architecture file for PortAudio and custom proto GUI.
# Provides the definitons and the main entry point to make the DSP code
# generated by Faust interact with the PortAudio API and be controlled via
# basic proto user inputs for demo purposes.
# ==============================================================================
# First section of architecture provided code start.
# Imports the modules and the definitions of the architecture code.
# ==============================================================================

from conf import *
from help import *
from dsp import *
from gui import *
from meta import *
from audio.portaudio import *
from gui.proto import ProtoGui

# ==============================================================================
# First section of architecture provided code end.
# ==============================================================================
# Code generated with Faust 2.87.10 (https://faust.grame.fr)
# name: "apf"
# Compilation options: 
#   -a portaudio-proto.mojo -lang mojo -fpga-mem-th 4 -ct 1 -cn Test -es 1 
#   -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0
# ==============================================================================

comptime dreal = f64
comptime wreal = simd_width_of[dreal]()
comptime Real = Scalar[dreal]
comptime RVec = SIMD[dreal, simd_width_of[dreal]()]

@fieldwise_init
struct Test(FaustDsp):
    var null_val: FaustFloat
    var sample_rate: S32
    var const0: F64
    var hslider0: FaustFloat
    var hslider1: FaustFloat
    var rec0: Arr[F64, 3]

    @always_inline
    def __init__(out dsp):
        dsp.null_val = FaustFloat(0.0)
        dsp.sample_rate = 0
        dsp.const0 = 0.0
        dsp.hslider0 = 0.0
        dsp.hslider1 = 0.0
        dsp.rec0 = Arr[F64, 3](fill=0.0)

    @always_inline
    def get_sample_rate(imm dsp) -> S32:
        return dsp.sample_rate

    @always_inline
    def get_num_outputs(imm dsp) -> S32:
        return 1

    @always_inline
    def get_num_inputs(imm dsp) -> S32:
        return 1

    @always_inline
    def class_init(mut dsp, imm sample_rate: S32) -> None:
        pass

    @always_inline
    def instance_constants(mut dsp, imm sample_rate: S32) -> None:
        dsp.sample_rate = sample_rate
        dsp.const0 = (6.283185307179586) / (min(1.92e+05, max(1.0, F64(dsp.sample_rate))))

    @always_inline
    def instance_reset_user_interface(mut dsp) -> None:
        dsp.hslider0 = 1000.0
        dsp.hslider1 = 1.0

    @always_inline
    def instance_clear(mut dsp) -> None:
        var l0 = S32(0)
        while (l0) < (S32(3)): 
            dsp.rec0[l0] = 0.0
            l0 = (l0) + (S32(1))

    @always_inline
    def instance_init(mut dsp, imm sample_rate: S32) -> None:
        dsp.instance_constants(sample_rate)
        dsp.instance_reset_user_interface()
        dsp.instance_clear()

    @always_inline
    def init(mut dsp, imm sample_rate: S32) -> None:
        dsp.class_init(sample_rate)
        dsp.instance_init(sample_rate)

    @always_inline
    def get_json(imm dsp) -> String:
        return "{\"name\": \"apf\",\"filename\": \"apf.dsp\",\"version\": \"2.87.10\",\"compile_options\": \"-a portaudio-proto.mojo -lang mojo -fpga-mem-th 4 -ct 1 -cn Test -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0\",\"library_list\": [\"/usr/local/share/faust/maxmsp.lib\",\"/usr/local/share/faust/maths.lib\",\"/usr/local/share/faust/platform.lib\"],\"include_pathnames\": [\"/Users/manuelfarzini/Personal/dev/repo/faust/build/share/faust\",\"/Users/manuelfarzini/Personal/dev/repo/faust/build/bin//share/faust\",\"/usr/local/share/faust\",\"/usr/share/faust\",\"src\",\"/Users/manuelfarzini/Personal/dev/repo/faust/architecture/mojo/src\"],\"size\": 52,\"inputs\": 1,\"outputs\": 1,\"meta\": [ { \"compile_options\": \"-a portaudio-proto.mojo -lang mojo -fpga-mem-th 4 -ct 1 -cn Test -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0\" },{ \"filename\": \"apf.dsp\" },{ \"maths.lib/author\": \"GRAME\" },{ \"maths.lib/copyright\": \"GRAME\" },{ \"maths.lib/license\": \"LGPL with exception\" },{ \"maths.lib/name\": \"Faust Math Library\" },{ \"maths.lib/version\": \"2.9.0\" },{ \"maxmsp.lib/author\": \"GRAME\" },{ \"maxmsp.lib/copyright\": \"GRAME\" },{ \"maxmsp.lib/license\": \"LGPL with exception\" },{ \"maxmsp.lib/name\": \"MaxMSP compatibility Library\" },{ \"maxmsp.lib/version\": \"1.1.0\" },{ \"name\": \"apf\" },{ \"platform.lib/name\": \"Generic Platform Library\" },{ \"platform.lib/version\": \"1.3.0\" }],\"ui\": [ {\"type\": \"vgroup\",\"label\": \"apf\",\"items\": [ {\"type\": \"hslider\",\"label\": \"Freq\",\"varname\": \"fHslider0\",\"shortname\": \"Freq\",\"address\": \"/apf/Freq\",\"init\": 1000,\"min\": 100,\"max\": 10000,\"step\": 1},{\"type\": \"hslider\",\"label\": \"Q\",\"varname\": \"fHslider1\",\"shortname\": \"Q\",\"address\": \"/apf/Q\",\"init\": 1,\"min\": 0.01,\"max\": 100,\"step\": 0.01}]}]}"

    @always_inline
    def metadata(imm dsp, mut meta: Some[FaustMeta]) -> None:
        meta.declare("compile_options", "-a portaudio-proto.mojo -lang mojo -fpga-mem-th 4 -ct 1 -cn Test -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0")
        meta.declare("filename", "apf.dsp")
        meta.declare("maths.lib/author", "GRAME")
        meta.declare("maths.lib/copyright", "GRAME")
        meta.declare("maths.lib/license", "LGPL with exception")
        meta.declare("maths.lib/name", "Faust Math Library")
        meta.declare("maths.lib/version", "2.9.0")
        meta.declare("maxmsp.lib/author", "GRAME")
        meta.declare("maxmsp.lib/copyright", "GRAME")
        meta.declare("maxmsp.lib/license", "LGPL with exception")
        meta.declare("maxmsp.lib/name", "MaxMSP compatibility Library")
        meta.declare("maxmsp.lib/version", "1.1.0")
        meta.declare("name", "apf")
        meta.declare("platform.lib/name", "Generic Platform Library")
        meta.declare("platform.lib/version", "1.3.0")

    @always_inline
    def build_user_interface(mut dsp, mut ui: Some[FaustGui]) -> None:
        ui.open_vertical_box("apf")
        ui.add_horizontal_slider("Freq", dsp.hslider0, FaustFloat(1000.0), FaustFloat(100.0), FaustFloat(10000.0), FaustFloat(1.0))
        ui.add_horizontal_slider("Q", dsp.hslider1, FaustFloat(1.0), FaustFloat(0.01), FaustFloat(100.0), FaustFloat(0.01))
        ui.close_box()

    @always_inline
    def compute(mut dsp, var count: S32, var inputs: ImmStreams, var outputs: MutStreams) -> None:
        var input0 = inputs[unsafe_offset = S32(0)]
        var output0 = outputs[unsafe_offset = S32(0)]
        var slow0 = (dsp.const0) * (max(0.0, F64(dsp.hslider0)))
        var slow1 = (0.5) * ((sin(slow0)) / (max(0.001, F64(dsp.hslider1))))
        var slow2 = (1.0) / ((slow1) + (1.0))
        var slow3 = (1.0) - (slow1)
        var slow4 = (2.0) * (cos(slow0))
        for var i0 in range(S32(0), count):
            var temp0 = (slow4) * (dsp.rec0[S32(1)])
            dsp.rec0[S32(0)] = (F64(input0[unsafe_offset = i0])) - ((slow2) * (((slow3) * (dsp.rec0[S32(2)])) - (temp0)))
            output0[unsafe_offset = i0] = FaustFloat((dsp.rec0[S32(2)]) + ((slow2) * (((slow3) * (dsp.rec0[S32(0)])) - (temp0))))
            dsp.rec0[S32(2)] = dsp.rec0[S32(1)]
            dsp.rec0[S32(1)] = dsp.rec0[S32(0)]

# ==============================================================================
# Faust generated DSP code end.
# ==============================================================================
# Second section of architecture provided code start.
# Defines the main entry point of the application.
# Initializes the dsp object, the audio driver, and the gui, starts the audio
# thread and blocks the main thread with the gui to allow the audio thread run
# the DSP code and be controlled via the gui.
# ==============================================================================

def main() -> None:
    comptime assert dfaust == F32.dtype, "Expected 32 bit float driver precision."
    var dsp = unsafe_alloc[Test](1)
    dsp.unsafe_write(Test())
    dsp[].init(SAMP_RATE)
    var gui = ProtoGui()
    dsp[].build_user_interface(gui)
    var driver = PortAudio()
    var err = driver.init()
    if err:
        dsp.unsafe_free()
        print(err)
        return
    err = driver.start(dsp)
    if err:
        dsp.unsafe_free()
        print(err)
        return
    err = gui.run()
    if err:
        dsp.unsafe_free()
        print(err)
        return
    err = driver.stop()
    if err:
        dsp.unsafe_free()
        print(err)
        return
    dsp.unsafe_free()
    print("done")

# ==============================================================================
# Second section of architecture provided code end.
# ==============================================================================
