[workspace]
authors = ["Manuel Farzini <manuel.farzini@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=26.6.0.dev2026082405,<27"
mojo = ">=1.1.0.dev2026082405,<2"
