[workspace]
authors = ["Manuel Farzini <manuel.farzini@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=26.4.0.dev2026051106,<27"
mojo = ">=1.0.0b2.dev2026051106,<2"
