# ==============================================================================
# Faust to Mojo architecture file for PortAudio and custom terminal GUI.
# Provides the definitons and the main entry point to make the DSP code
# generated by Faust interact with the PortAudio API and be controlled via
# basic terminal user inputs for demo purposes.
# ==============================================================================
# First section of architecture provided code start.
# Imports the modules and the definitions of the architecture code.
# ==============================================================================

from conf import *
from help import *
from dsp import *
from gui import *
from meta import *
from audio.portaudio import *
from gui.terminal import TerminalGui

# ==============================================================================
# First section of architecture provided code end.
<<includeIntrinsic>>
<<includeclass>>
# ==============================================================================
# Faust generated DSP code end.
# ==============================================================================
# Second section of architecture provided code start.
# Defines the main entry point of the application.
# Initializes the dsp object, the audio driver, and the gui, starts the audio
# thread and blocks the main thread with the gui to allow the audio thread run
# the DSP code and be controlled via the gui.
# ==============================================================================

def main() -> None:
    comptime assert dfaust == F32.dtype, "Expected 32 bit float driver precision."
    var dsp = unsafe_alloc[mydsp](1)
    dsp[] = mydsp()
    dsp[].init(SAMP_RATE)
    var gui = TerminalGui[dfaust]()
    dsp[].build_user_interface(gui)
    var driver = PortAudio()
    err = driver.init()
    if err:
        dsp.unsafe_free()
        print(err)
        return
    err = driver.start(dsp)
    if err:
        dsp.unsafe_free()
        print(err)
        return
    err = gui.run()
    if err:
        dsp.unsafe_free()
        print(err)
        return
    err = driver.stop()
    if err:
        dsp.unsafe_free()
        print(err)
        return
    dsp.unsafe_free()
    print("done")

# ==============================================================================
# Second section of architecture provided code end.
# ==============================================================================
