# ==============================================================================
# Faust to Mojo audio architecture for PortAudio.
# Provides the definitions and the main entry point to make the DSP code
# generated by Faust interact with the PortAudio API.
# ==============================================================================
# First section of architecture provided code start.
# Imports the modules and the definitions of the architecture code.
# ==============================================================================

from conf import *
from help import *
from dsp import *
from gui import *
from meta import *
from audio.portaudio import *

# ==============================================================================
# First section of architecture provided code end.
<<includeIntrinsic>>
<<includeclass>>
# ==============================================================================
# Faust generated DSP code end.
# ==============================================================================
# Second section of architecture provided code start.
# Defines the main entry point of the application.
# Initializes the dsp object and the audio driver, starts the audio thread and
# blocks the main thread to allow the audio thread run the DSP code.
# ==============================================================================

def main() -> None:
    comptime assert dfaust == F32.dtype, "Expected 32 bit float driver precision."
    var dsp = unsafe_alloc[mydsp](1)
    dsp[] = mydsp()
    dsp[].init(SAMP_RATE)
    var driver = PortAudio()
    var err = driver.init()
    if err:
        print(err)
        dsp.unsafe_free()
        return
    err = driver.start(dsp)
    if err:
        print(err)
        dsp.unsafe_free()
        return
    try:
        _ = input()
    except e:
        print(e)
        return
    err = driver.stop()
    if err:
        print(err)
        dsp.unsafe_free()
        return
    dsp.unsafe_free()
    print("done")

# ==============================================================================
# Second section of architecture provided code end.
# ==============================================================================
