#!/bin/bash

#####################################################################
#                                                                   #
#                        faust2clap generator                       #
#               (c) GRAME & Facundo Franchino, 2025                 #
#                                                                   #
#####################################################################    

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
python3 ${SCRIPT_DIR}/faust2clap.py $@