#!/bin/bash

## exclusion list for faust errors
XLIST1="faust2md"

OSX="faust2au faust2caqt faust2csound faust2faustvst faust2jaqt faust2max6 faust2msp faust2puredata faust2supercollider faust2vst faust2vsti"

LINUX="faust2alqt faust2alsa faust2alsaconsole faust2android faust2asmjs faust2bela   faust2csound faust2dssi faust2eps faust2faustvst faust2firefox faust2graph faust2graphviewer  faust2jack faust2jackconsole faust2jackinternal faust2jackserver faust2jaqt faust2ladspa faust2lv2 faust2mathdoc  faust2md  faust2netjackconsole faust2netjackqt faust2octave faust2owl faust2paqt faust2pdf faust2plot faust2png faust2puredata faust2raqt faust2ros faust2rosgtk faust2rpialsaconsole faust2rpinetjackconsole faust2sig faust2sigviewer faust2supercollider faust2svg faust2w32max6 faust2w32msp faust2w32puredata faust2w32vst faust2webaudioasm"

## test exclusion : notinlist "toto" "a b c d e"
notinlist() {
  for word in $2; do
    if [ $word = $1 ]; then
        return 1
    fi
  done
  return 0
}

if [ "$1" = "osx" ]; then
	echo
	echo "Test $OSX"

	for scriptname in $OSX; do
    	($scriptname good.dsp &> LOG)&&(echo "OK: $scriptname succeeded !")||(echo "ERROR: $scriptname failed")
	done	
elif [ "$1" = "linux" ]; then
	echo
	echo "Test $LINUX"

	for scriptname in $LINUX; do
    	($scriptname good.dsp &> LOG)&&(echo "OK: $scriptname succeeded !")||(echo "ERROR: $scriptname failed")
	done	
else 
	echo
	echo "Test all Faust2xxx to work"
	echo
	for S in ../faust2*; do
		scriptname=`basename $S .in`
		if notinlist  $S "$XLIST1"; then
			($scriptname good.dsp &> LOG)&&(echo "OK: $scriptname succeeded !")||(echo "ERROR: $scriptname failed")
		fi
	done
fi
