
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"reverbTester\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"72\",\"inputs\":\"5\",\"outputs\":\"2\",\"meta\":[{\"author\":\"RM\"},{\"basics.lib/name\":\"Faust Basic Element Library\"},{\"basics.lib/version\":\"0.0\"},{\"description\":\"Handy test inputs for reverberator demos below.\"},{\"filters.lib/name\":\"Faust Filters Library\"},{\"filters.lib/version\":\"0.0\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"reverbTester\"},{\"noises.lib/name\":\"Faust Noise Generator Library\"},{\"noises.lib/version\":\"0.0\"},{\"version\":\"0.0\"}],\"ui\":[{\"type\":\"vgroup\",\"label\":\"reverbTester\",\"items\":[{\"type\":\"vgroup\",\"label\":\"Input Config\",\"meta\":[{\"1\":\"\"}],\"items\":[{\"type\":\"checkbox\",\"label\":\"Mute Ext Inputs\",\"address\":\"/reverbTester/Input_Config/Mute_Ext_Inputs\",\"index\":\"12\",\"meta\":[{\"1\":\"\"},{\"tooltip\":\"When this is checked, the stereo external audio inputs are   disabled (good for hearing the impulse response or pink-noise response alone)\"}]},{\"type\":\"checkbox\",\"label\":\"Pink Noise\",\"address\":\"/reverbTester/Input_Config/Pink_Noise\",\"index\":\"28\",\"meta\":[{\"2\":\"\"},{\"tooltip\":\"Pink Noise (or 1/f noise) is Constant-Q Noise (useful for adjusting   the EQ sections)\"}]}]},{\"type\":\"hgroup\",\"label\":\"Impulse Selection\",\"meta\":[{\"2\":\"\"}],\"items\":[{\"type\":\"button\",\"label\":\"Left\",\"address\":\"/reverbTester/Impulse_Selection/Left\",\"index\":\"16\",\"meta\":[{\"1\":\"\"},{\"tooltip\":\"Send impulse into LEFT channel\"}]},{\"type\":\"button\",\"label\":\"Center\",\"address\":\"/reverbTester/Impulse_Selection/Center\",\"index\":\"0\",\"meta\":[{\"2\":\"\"},{\"tooltip\":\"Send impulse into LEFT and RIGHT channels\"}]},{\"type\":\"button\",\"label\":\"Right\",\"address\":\"/reverbTester/Impulse_Selection/Right\",\"index\":\"56\",\"meta\":[{\"3\":\"\"},{\"tooltip\":\"Send impulse into RIGHT channel\"}]}]}]}]}";
}
