
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"moogVCF\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"160\",\"inputs\":\"1\",\"outputs\":\"1\",\"meta\":[{\"basics.lib/name\":\"Faust Basic Element Library\"},{\"basics.lib/version\":\"0.0\"},{\"description\":\"Exercise and compare three Moog VCF implementations\"},{\"filters.lib/name\":\"Faust Filters Library\"},{\"filters.lib/version\":\"0.0\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"moogVCF\"},{\"signals.lib/name\":\"Faust Signal Routing Library\"},{\"signals.lib/version\":\"0.0\"},{\"vaeffects.lib/name\":\"Faust Virtual Analog Filter Effect Library\"},{\"vaeffects.lib/version\":\"0.0\"}],\"ui\":[{\"type\":\"hgroup\",\"label\":\"MOOG VCF (Voltage Controlled Filter)\",\"meta\":[{\"tooltip\":\"See Faust's   vaeffects.lib for info and references\"}],\"items\":[{\"type\":\"hgroup\",\"label\":\"0x00\",\"meta\":[{\"0\":\"\"}],\"items\":[{\"type\":\"checkbox\",\"label\":\"Bypass\",\"address\":\"/MOOG_VCF_(Voltage_Controlled_Filter)/0x00/Bypass\",\"index\":\"0\",\"meta\":[{\"0\":\"\"},{\"tooltip\":\"When this is checked, the Moog VCF   has no effect\"}]},{\"type\":\"checkbox\",\"label\":\"Use Biquads\",\"address\":\"/MOOG_VCF_(Voltage_Controlled_Filter)/0x00/Use_Biquads\",\"index\":\"16\",\"meta\":[{\"1\":\"\"},{\"tooltip\":\"Select moog_vcf_2b (two-biquad)   implementation, instead of the default moog_vcf (analog style) implementation\"}]},{\"type\":\"checkbox\",\"label\":\"Normalized Ladders\",\"address\":\"/MOOG_VCF_(Voltage_Controlled_Filter)/0x00/Normalized_Ladders\",\"index\":\"88\",\"meta\":[{\"2\":\"\"},{\"tooltip\":\"If using biquads, make   them normalized ladders (moog_vcf_2bn)\"}]}]},{\"type\":\"hslider\",\"label\":\"Corner Frequency\",\"address\":\"/MOOG_VCF_(Voltage_Controlled_Filter)/Corner_Frequency\",\"index\":\"36\",\"meta\":[{\"1\":\"\"},{\"tooltip\":\"The VCF resonates   at the corner frequency (specified in PianoKey (PK) units, with A440 = 49 PK).   The VCF response is flat below the corner frequency, and rolls off -24 dB per   octave above.\"},{\"unit\":\"PK\"}],\"init\":\"25\",\"min\":\"1\",\"max\":\"88\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"Corner Resonance\",\"address\":\"/MOOG_VCF_(Voltage_Controlled_Filter)/Corner_Resonance\",\"index\":\"20\",\"meta\":[{\"2\":\"\"},{\"style\":\"knob\"},{\"tooltip\":\"Amount of   resonance near VCF corner frequency (specified between 0 and 1)\"}],\"init\":\"0.9\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"VCF Output Level\",\"address\":\"/MOOG_VCF_(Voltage_Controlled_Filter)/VCF_Output_Level\",\"index\":\"4\",\"meta\":[{\"3\":\"\"},{\"style\":\"knob\"},{\"tooltip\":\"output level in decibels\"},{\"unit\":\"dB\"}],\"init\":\"5\",\"min\":\"-60\",\"max\":\"20\",\"step\":\"0.1\"}]}]}";
}
