
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"Vocoder\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"1852\",\"inputs\":\"1\",\"outputs\":\"2\",\"meta\":[{\"analyzers.lib/name\":\"Faust Analyzer Library\"},{\"analyzers.lib/version\":\"0.0\"},{\"author\":\"RM\"},{\"basics.lib/name\":\"Faust Basic Element Library\"},{\"basics.lib/version\":\"0.0\"},{\"description\":\"Use example of the vocoder function where an impulse train is used as excitation.\"},{\"filters.lib/name\":\"Faust Filters Library\"},{\"filters.lib/version\":\"0.0\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"Vocoder\"},{\"oscillators.lib/name\":\"Faust Oscillator Library\"},{\"oscillators.lib/version\":\"0.0\"},{\"signals.lib/name\":\"Faust Signal Routing Library\"},{\"signals.lib/version\":\"0.0\"},{\"vaeffects.lib/name\":\"Faust Virtual Analog Filter Effect Library\"},{\"vaeffects.lib/version\":\"0.0\"},{\"version\":\"0.0\"}],\"ui\":[{\"type\":\"hgroup\",\"label\":\"My Vocoder\",\"items\":[{\"type\":\"vgroup\",\"label\":\"Excitation\",\"items\":[{\"type\":\"hslider\",\"label\":\"Freq\",\"address\":\"/My_Vocoder/Excitation/Freq\",\"index\":\"36\",\"meta\":[{\"0\":\"\"},{\"style\":\"knob\"}],\"init\":\"330\",\"min\":\"50\",\"max\":\"2000\",\"step\":\"0.1\"},{\"type\":\"vslider\",\"label\":\"Gain\",\"address\":\"/My_Vocoder/Excitation/Gain\",\"index\":\"20\",\"meta\":[{\"1\":\"\"}],\"init\":\"0.5\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"}]},{\"type\":\"vgroup\",\"label\":\"Vocoder\",\"items\":[{\"type\":\"hslider\",\"label\":\"Attack\",\"address\":\"/My_Vocoder/Vocoder/Attack\",\"index\":\"92\",\"meta\":[{\"0\":\"\"},{\"style\":\"knob\"},{\"tooltip\":\"Attack time in seconds\"}],\"init\":\"5\",\"min\":\"0.1\",\"max\":\"100\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"Release\",\"address\":\"/My_Vocoder/Vocoder/Release\",\"index\":\"96\",\"meta\":[{\"1\":\"\"},{\"style\":\"knob\"},{\"tooltip\":\"Release time in seconds\"}],\"init\":\"5\",\"min\":\"0.1\",\"max\":\"100\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"BW\",\"address\":\"/My_Vocoder/Vocoder/BW\",\"index\":\"16\",\"meta\":[{\"2\":\"\"},{\"style\":\"knob\"},{\"tooltip\":\"Coefficient to adjust the   bandwidth of each band\"}],\"init\":\"0.5\",\"min\":\"0.1\",\"max\":\"2\",\"step\":\"0.001\"}]}]}]}";
}
