/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust;

public class FaustJNI {
  public final static native String expandCDSPFromFile(String jarg1, int jarg2, long jarg3, String jarg4, String jarg5);
  public final static native String expandCDSPFromString(String jarg1, String jarg2, int jarg3, long jarg4, String jarg5, String jarg6);
  public final static native boolean generateCAuxFilesFromFile(String jarg1, int jarg2, long jarg3, String jarg4);
  public final static native boolean generateCAuxFilesFromString(String jarg1, String jarg2, int jarg3, long jarg4, String jarg5);
  public final static native void generateCSHA1(String jarg1, String jarg2);
  public final static native void freeCMemory(long jarg1);
  public final static native long new_llvm_dsp_factory();
  public final static native void delete_llvm_dsp_factory(long jarg1);
  public final static native long new_llvm_dsp();
  public final static native void delete_llvm_dsp(long jarg1);
  public final static native String getCLibFaustVersion();
  public final static native String getCDSPMachineTarget();
  public final static native long getCDSPFactoryFromSHAKey(String jarg1);
  public final static native long createCDSPFactoryFromFile(String jarg1, int jarg2, long jarg3, String jarg4, String jarg5, int jarg6);
  public final static native long createCDSPFactoryFromString(String jarg1, String jarg2, int jarg3, long jarg4, String jarg5, String jarg6, int jarg7);
  public final static native boolean deleteCDSPFactory(long jarg1, llvm_dsp_factory jarg1_);
  public final static native String getCName(long jarg1, llvm_dsp_factory jarg1_);
  public final static native String getCSHAKey(long jarg1, llvm_dsp_factory jarg1_);
  public final static native String getCDSPCode(long jarg1, llvm_dsp_factory jarg1_);
  public final static native String getCTarget(long jarg1, llvm_dsp_factory jarg1_);
  public final static native long getCDSPFactoryLibraryList(long jarg1, llvm_dsp_factory jarg1_);
  public final static native void deleteAllCDSPFactories();
  public final static native long getAllCDSPFactories();
  public final static native boolean startMTCDSPFactories();
  public final static native void stopMTCDSPFactories();
  public final static native long readCDSPFactoryFromBitcode(String jarg1, String jarg2, int jarg3);
  public final static native String writeCDSPFactoryToBitcode(long jarg1, llvm_dsp_factory jarg1_);
  public final static native long readCDSPFactoryFromBitcodeFile(String jarg1, String jarg2, int jarg3);
  public final static native void writeCDSPFactoryToBitcodeFile(long jarg1, llvm_dsp_factory jarg1_, String jarg2);
  public final static native long readCDSPFactoryFromIR(String jarg1, String jarg2, int jarg3);
  public final static native String writeCDSPFactoryToIR(long jarg1, llvm_dsp_factory jarg1_);
  public final static native long readCDSPFactoryFromIRFile(String jarg1, String jarg2, int jarg3);
  public final static native void writeCDSPFactoryToIRFile(long jarg1, llvm_dsp_factory jarg1_, String jarg2);
  public final static native long readCDSPFactoryFromMachine(String jarg1, String jarg2);
  public final static native String writeCDSPFactoryToMachine(long jarg1, llvm_dsp_factory jarg1_, String jarg2);
  public final static native long readCDSPFactoryFromMachineFile(String jarg1, String jarg2);
  public final static native void writeCDSPFactoryToMachineFile(long jarg1, llvm_dsp_factory jarg1_, String jarg2, String jarg3);
  public final static native int getNumInputsCDSPInstance(long jarg1, llvm_dsp jarg1_);
  public final static native int getNumOutputsCDSPInstance(long jarg1, llvm_dsp jarg1_);
  public final static native void buildUserInterfaceCDSPInstance(long jarg1, llvm_dsp jarg1_, long jarg2);
  public final static native int getSampleRateCDSPInstance(long jarg1, llvm_dsp jarg1_);
  public final static native void initCDSPInstance(long jarg1, llvm_dsp jarg1_, int jarg2);
  public final static native void instanceInitCDSPInstance(long jarg1, llvm_dsp jarg1_, int jarg2);
  public final static native void instanceConstantsCDSPInstance(long jarg1, llvm_dsp jarg1_, int jarg2);
  public final static native void instanceResetUserInterfaceCDSPInstance(long jarg1, llvm_dsp jarg1_);
  public final static native void instanceClearCDSPInstance(long jarg1, llvm_dsp jarg1_);
  public final static native long cloneCDSPInstance(long jarg1, llvm_dsp jarg1_);
  public final static native void metadataCDSPInstance(long jarg1, llvm_dsp jarg1_, long jarg2);
  public final static native void computeCDSPInstance(long jarg1, llvm_dsp jarg1_, int jarg2, long jarg3, long jarg4);
  public final static native void setCMemoryManager(long jarg1, llvm_dsp_factory jarg1_, long jarg2);
  public final static native long createCDSPInstance(long jarg1, llvm_dsp_factory jarg1_);
  public final static native void deleteCDSPInstance(long jarg1, llvm_dsp jarg1_);
  public final static native long createCDSPFactoryFromFileAux(String jarg1, String jarg2, String jarg3, int jarg4);
  public final static native long createCDSPFactoryFromStringAux(String jarg1, String jarg2, String jarg3, String jarg4, int jarg5);
  public final static native String getCDSPLastError();
}
