/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grame.faust;

public class FaustEngine implements FaustEngineConstants {
  public static String getLastError() {
    return FaustEngineJNI.getLastError();
  }

  public static dsp create1(String name_app, String dsp_content) {
    long cPtr = FaustEngineJNI.create1(name_app, dsp_content);
    return (cPtr == 0) ? null : new dsp(cPtr, false);
  }

  public static dsp create2(String name_app, String dsp_content, String argv, String target, int opt_level) {
    long cPtr = FaustEngineJNI.create2(name_app, dsp_content, argv, target, opt_level);
    return (cPtr == 0) ? null : new dsp(cPtr, false);
  }

  public static void destroy(dsp dsp) {
    FaustEngineJNI.destroy(dsp.getCPtr(dsp), dsp);
  }

  public static boolean init1(dsp dsp, String name) {
    return FaustEngineJNI.init1(dsp.getCPtr(dsp), dsp, name);
  }

  public static boolean init2(dsp dsp, String name, int renderer, int sr, int bsize) {
    return FaustEngineJNI.init2(dsp.getCPtr(dsp), dsp, name, renderer, sr, bsize);
  }

  public static boolean start(dsp dsp) {
    return FaustEngineJNI.start(dsp.getCPtr(dsp), dsp);
  }

  public static void stop(dsp dsp) {
    FaustEngineJNI.stop(dsp.getCPtr(dsp), dsp);
  }

  public static int getNumInputs(dsp dsp) {
    return FaustEngineJNI.getNumInputs(dsp.getCPtr(dsp), dsp);
  }

  public static int getNumOutputs(dsp dsp) {
    return FaustEngineJNI.getNumOutputs(dsp.getCPtr(dsp), dsp);
  }

  public static int getNumPhysicalInputs() {
    return FaustEngineJNI.getNumPhysicalInputs();
  }

  public static int getNumPhysicalOutputs() {
    return FaustEngineJNI.getNumPhysicalOutputs();
  }

  public static void connect(dsp dsp1, dsp dsp2, int src, int dst) {
    FaustEngineJNI.connect(dsp.getCPtr(dsp1), dsp1, dsp.getCPtr(dsp2), dsp2, src, dst);
  }

  public static void disconnect(dsp dsp1, dsp dsp2, int src, int dst) {
    FaustEngineJNI.disconnect(dsp.getCPtr(dsp1), dsp1, dsp.getCPtr(dsp2), dsp2, src, dst);
  }

  public static boolean isConnected(dsp dsp1, dsp dsp2, int src, int dst) {
    return FaustEngineJNI.isConnected(dsp.getCPtr(dsp1), dsp1, dsp.getCPtr(dsp2), dsp2, src, dst);
  }

  public static String getJSON(dsp dsp) {
    return FaustEngineJNI.getJSON(dsp.getCPtr(dsp), dsp);
  }

  public static int getParamsCount(dsp dsp) {
    return FaustEngineJNI.getParamsCount(dsp.getCPtr(dsp), dsp);
  }

  public static int getParamIndex(dsp dsp, String name) {
    return FaustEngineJNI.getParamIndex(dsp.getCPtr(dsp), dsp, name);
  }

  public static String getParamName(dsp dsp, int p) {
    return FaustEngineJNI.getParamName(dsp.getCPtr(dsp), dsp, p);
  }

  public static String getParamUnit(dsp dsp, int p) {
    return FaustEngineJNI.getParamUnit(dsp.getCPtr(dsp), dsp, p);
  }

  public static float getParamMin(dsp dsp, int p) {
    return FaustEngineJNI.getParamMin(dsp.getCPtr(dsp), dsp, p);
  }

  public static float getParamMax(dsp dsp, int p) {
    return FaustEngineJNI.getParamMax(dsp.getCPtr(dsp), dsp, p);
  }

  public static float getParamStep(dsp dsp, int p) {
    return FaustEngineJNI.getParamStep(dsp.getCPtr(dsp), dsp, p);
  }

  public static float getParamValue(dsp dsp, int p) {
    return FaustEngineJNI.getParamValue(dsp.getCPtr(dsp), dsp, p);
  }

  public static void setParamValue(dsp dsp, int p, float v) {
    FaustEngineJNI.setParamValue(dsp.getCPtr(dsp), dsp, p, v);
  }

  public static float getParamRatio(dsp dsp, int p) {
    return FaustEngineJNI.getParamRatio(dsp.getCPtr(dsp), dsp, p);
  }

  public static void setParamRatio(dsp dsp, int p, float v) {
    FaustEngineJNI.setParamRatio(dsp.getCPtr(dsp), dsp, p, v);
  }

  public static void propagateAccX(dsp dsp, float a) {
    FaustEngineJNI.propagateAccX(dsp.getCPtr(dsp), dsp, a);
  }

  public static void propagateAccY(dsp dsp, float a) {
    FaustEngineJNI.propagateAccY(dsp.getCPtr(dsp), dsp, a);
  }

  public static void propagateAccZ(dsp dsp, float a) {
    FaustEngineJNI.propagateAccZ(dsp.getCPtr(dsp), dsp, a);
  }

}
