[workspace]
authors = ["Manuel Farzini <manuel.farzini@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "_bench"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=26.6.0.dev2026082405,<27"
mojo = ">=1.1.0.dev2026082405,<2"
python = ">=3.14.7,<3.15"
matplotlib = ">=3.11.1,<4"
pandas = ">=3.0.5,<4"
