
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"fourSourcesToOcto\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"108\",\"inputs\":\"4\",\"outputs\":\"8\",\"meta\":[{\"author\":\"CICM\"},{\"basics.lib/name\":\"Faust Basic Element Library\"},{\"basics.lib/version\":\"0.0\"},{\"copyright\":\"(c)CICM 2013\"},{\"hoa.lib/author\":\"Pierre Guillot\"},{\"hoa.lib/copyright\":\"2012-2013 Guillot, Paris, Colafrancesco, CICM labex art H2H, U. Paris 8\"},{\"hoa.lib/name\":\"High Order Ambisonics library\"},{\"license\":\"BSD\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"fourSourcesToOcto\"},{\"routes.lib/name\":\"Faust Signal Routing Library\"},{\"routes.lib/version\":\"0.0\"},{\"signals.lib/name\":\"Faust Signal Routing Library\"},{\"signals.lib/version\":\"0.0\"},{\"version\":\"1.0\"}],\"ui\":[{\"type\":\"vgroup\",\"label\":\"fourSourcesToOcto\",\"items\":[{\"type\":\"hslider\",\"label\":\"Angle1\",\"address\":\"/fourSourcesToOcto/Angle1\",\"index\":\"60\",\"init\":\"0\",\"min\":\"-6.28319\",\"max\":\"6.28319\",\"step\":\"0.001\"},{\"type\":\"hslider\",\"label\":\"Angle2\",\"address\":\"/fourSourcesToOcto/Angle2\",\"index\":\"72\",\"init\":\"0\",\"min\":\"-6.28319\",\"max\":\"6.28319\",\"step\":\"0.001\"},{\"type\":\"hslider\",\"label\":\"Angle3\",\"address\":\"/fourSourcesToOcto/Angle3\",\"index\":\"84\",\"init\":\"0\",\"min\":\"-6.28319\",\"max\":\"6.28319\",\"step\":\"0.001\"},{\"type\":\"hslider\",\"label\":\"Angle4\",\"address\":\"/fourSourcesToOcto/Angle4\",\"index\":\"96\",\"init\":\"0\",\"min\":\"-6.28319\",\"max\":\"6.28319\",\"step\":\"0.001\"},{\"type\":\"hslider\",\"label\":\"Radius1\",\"address\":\"/fourSourcesToOcto/Radius1\",\"index\":\"12\",\"init\":\"1\",\"min\":\"0\",\"max\":\"5\",\"step\":\"0.001\"},{\"type\":\"hslider\",\"label\":\"Radius2\",\"address\":\"/fourSourcesToOcto/Radius2\",\"index\":\"24\",\"init\":\"1\",\"min\":\"0\",\"max\":\"5\",\"step\":\"0.001\"},{\"type\":\"hslider\",\"label\":\"Radius3\",\"address\":\"/fourSourcesToOcto/Radius3\",\"index\":\"36\",\"init\":\"1\",\"min\":\"0\",\"max\":\"5\",\"step\":\"0.001\"},{\"type\":\"hslider\",\"label\":\"Radius4\",\"address\":\"/fourSourcesToOcto/Radius4\",\"index\":\"48\",\"init\":\"1\",\"min\":\"0\",\"max\":\"5\",\"step\":\"0.001\"}]}]}";
}
