======= Container "mydsp" ==========

======= Sub container begin ==========

======= Sub container end ==========

======= User Interface ==========

BlockInst 
	OpenTabBox("Matrix 8 x 8")
	OpenHorizontalBox("Output 0")
	AddVerticalSlider("Input 0", fVslider0, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 1", fVslider1, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 2", fVslider2, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 3", fVslider3, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 4", fVslider4, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 5", fVslider5, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 6", fVslider6, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 7", fVslider7, -10.0f, -96.0f, 4.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Output 1")
	AddVerticalSlider("Input 0", fVslider8, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 1", fVslider9, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 2", fVslider10, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 3", fVslider11, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 4", fVslider12, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 5", fVslider13, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 6", fVslider14, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 7", fVslider15, -10.0f, -96.0f, 4.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Output 2")
	AddVerticalSlider("Input 0", fVslider16, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 1", fVslider17, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 2", fVslider18, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 3", fVslider19, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 4", fVslider20, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 5", fVslider21, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 6", fVslider22, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 7", fVslider23, -10.0f, -96.0f, 4.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Output 3")
	AddVerticalSlider("Input 0", fVslider24, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 1", fVslider25, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 2", fVslider26, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 3", fVslider27, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 4", fVslider28, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 5", fVslider29, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 6", fVslider30, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 7", fVslider31, -10.0f, -96.0f, 4.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Output 4")
	AddVerticalSlider("Input 0", fVslider32, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 1", fVslider33, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 2", fVslider34, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 3", fVslider35, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 4", fVslider36, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 5", fVslider37, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 6", fVslider38, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 7", fVslider39, -10.0f, -96.0f, 4.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Output 5")
	AddVerticalSlider("Input 0", fVslider40, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 1", fVslider41, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 2", fVslider42, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 3", fVslider43, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 4", fVslider44, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 5", fVslider45, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 6", fVslider46, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 7", fVslider47, -10.0f, -96.0f, 4.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Output 6")
	AddVerticalSlider("Input 0", fVslider48, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 1", fVslider49, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 2", fVslider50, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 3", fVslider51, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 4", fVslider52, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 5", fVslider53, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 6", fVslider54, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 7", fVslider55, -10.0f, -96.0f, 4.0f, 0.100000001f)
	CloseboxInst
	OpenHorizontalBox("Output 7")
	AddVerticalSlider("Input 0", fVslider56, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 1", fVslider57, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 2", fVslider58, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 3", fVslider59, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 4", fVslider60, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 5", fVslider61, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 6", fVslider62, -10.0f, -96.0f, 4.0f, 0.100000001f)
	AddVerticalSlider("Input 7", fVslider63, -10.0f, -96.0f, 4.0f, 0.100000001f)
	CloseboxInst
	CloseboxInst
	EndBlock

======= Global declarations ==========

BlockInst 
	DeclareFunInst("float", "powf", "float", dummy0, "float", dummy1)
	EndBlock

======= Declarations ==========

BlockInst 
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider0)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider1)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider2)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider3)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider4)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider5)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider6)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider7)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider8)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider9)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider10)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider11)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider12)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider13)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider14)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider15)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider16)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider17)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider18)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider19)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider20)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider21)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider22)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider23)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider24)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider25)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider26)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider27)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider28)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider29)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider30)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider31)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider32)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider33)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider34)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider35)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider36)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider37)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider38)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider39)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider40)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider41)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider42)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider43)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider44)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider45)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider46)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider47)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider48)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider49)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider50)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider51)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider52)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider53)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider54)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider55)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider56)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider57)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider58)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider59)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider60)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider61)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider62)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider63)
	DeclareVarInst(struct, "int", fSamplingFreq)
	EndBlock

DeclareFunInst("int", "getNumInputs")
	BlockInst 
		RetInst(Int32(8))
		EndBlock
	EndDeclare

DeclareFunInst("int", "getNumOutputs")
	BlockInst 
		RetInst(Int32(8))
		EndBlock
	EndDeclare

DeclareFunInst("int", "getInputRate", "int", channel)
	BlockInst 
		DeclareVarInst(stack, "int", rate)
		SwitchInst LoadVarInst(kFunArgs, channel)
			Case 0
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 1
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 2
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 3
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 4
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 5
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 6
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 7
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Default 
				BlockInst 
					StoreVarInst(stack, rate, Int32(-1))
					EndBlock
				EndCase
			EndSWitch
		RetInst(LoadVarInst(stack, rate))
		EndBlock
	EndDeclare

DeclareFunInst("int", "getOutputRate", "int", channel)
	BlockInst 
		DeclareVarInst(stack, "int", rate)
		SwitchInst LoadVarInst(kFunArgs, channel)
			Case 0
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 1
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 2
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 3
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 4
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 5
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 6
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Case 7
				BlockInst 
					StoreVarInst(stack, rate, Int32(1))
					EndBlock
				EndCase
			Default 
				BlockInst 
					StoreVarInst(stack, rate, Int32(-1))
					EndBlock
				EndCase
			EndSWitch
		RetInst(LoadVarInst(stack, rate))
		EndBlock
	EndDeclare

======= Init ==========

BlockInst 
	StoreVarInst(struct, fSamplingFreq, LoadVarInst(kFunArgs, samplingFreq))
	EndBlock

======= ResetUI ==========

BlockInst 
	StoreVarInst(struct, fVslider0, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider1, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider2, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider3, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider4, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider5, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider6, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider7, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider8, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider9, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider10, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider11, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider12, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider13, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider14, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider15, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider16, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider17, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider18, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider19, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider20, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider21, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider22, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider23, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider24, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider25, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider26, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider27, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider28, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider29, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider30, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider31, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider32, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider33, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider34, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider35, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider36, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider37, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider38, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider39, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider40, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider41, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider42, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider43, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider44, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider45, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider46, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider47, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider48, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider49, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider50, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider51, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider52, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider53, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider54, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider55, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider56, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider57, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider58, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider59, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider60, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider61, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider62, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider63, CastInst("FAUSTFLOAT", Double(-10.0f)))
	EndBlock

======= Compute control ==========

Instructions complexity
Load = 80
Store = 0
Binop = 64
Numbers = 128
Declare = 80
Cast = 64
Select = 0
Loop = 0
Funcall = 64

BlockInst 
	DeclareVarInst(stack, FAUSTFLOAT*, input0, LoadVarInst(kFunArgs, inputs[Int32(0)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input1, LoadVarInst(kFunArgs, inputs[Int32(1)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input2, LoadVarInst(kFunArgs, inputs[Int32(2)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input3, LoadVarInst(kFunArgs, inputs[Int32(3)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input4, LoadVarInst(kFunArgs, inputs[Int32(4)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input5, LoadVarInst(kFunArgs, inputs[Int32(5)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input6, LoadVarInst(kFunArgs, inputs[Int32(6)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input7, LoadVarInst(kFunArgs, inputs[Int32(7)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output0, LoadVarInst(kFunArgs, outputs[Int32(0)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output1, LoadVarInst(kFunArgs, outputs[Int32(1)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output2, LoadVarInst(kFunArgs, outputs[Int32(2)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output3, LoadVarInst(kFunArgs, outputs[Int32(3)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output4, LoadVarInst(kFunArgs, outputs[Int32(4)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output5, LoadVarInst(kFunArgs, outputs[Int32(5)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output6, LoadVarInst(kFunArgs, outputs[Int32(6)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output7, LoadVarInst(kFunArgs, outputs[Int32(7)]))
	DeclareVarInst(stack, "float", fSlow0, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider0)))))
	DeclareVarInst(stack, "float", fSlow1, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider1)))))
	DeclareVarInst(stack, "float", fSlow2, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider2)))))
	DeclareVarInst(stack, "float", fSlow3, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider3)))))
	DeclareVarInst(stack, "float", fSlow4, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider4)))))
	DeclareVarInst(stack, "float", fSlow5, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider5)))))
	DeclareVarInst(stack, "float", fSlow6, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider6)))))
	DeclareVarInst(stack, "float", fSlow7, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider7)))))
	DeclareVarInst(stack, "float", fSlow8, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider8)))))
	DeclareVarInst(stack, "float", fSlow9, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider9)))))
	DeclareVarInst(stack, "float", fSlow10, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider10)))))
	DeclareVarInst(stack, "float", fSlow11, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider11)))))
	DeclareVarInst(stack, "float", fSlow12, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider12)))))
	DeclareVarInst(stack, "float", fSlow13, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider13)))))
	DeclareVarInst(stack, "float", fSlow14, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider14)))))
	DeclareVarInst(stack, "float", fSlow15, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider15)))))
	DeclareVarInst(stack, "float", fSlow16, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider16)))))
	DeclareVarInst(stack, "float", fSlow17, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider17)))))
	DeclareVarInst(stack, "float", fSlow18, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider18)))))
	DeclareVarInst(stack, "float", fSlow19, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider19)))))
	DeclareVarInst(stack, "float", fSlow20, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider20)))))
	DeclareVarInst(stack, "float", fSlow21, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider21)))))
	DeclareVarInst(stack, "float", fSlow22, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider22)))))
	DeclareVarInst(stack, "float", fSlow23, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider23)))))
	DeclareVarInst(stack, "float", fSlow24, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider24)))))
	DeclareVarInst(stack, "float", fSlow25, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider25)))))
	DeclareVarInst(stack, "float", fSlow26, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider26)))))
	DeclareVarInst(stack, "float", fSlow27, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider27)))))
	DeclareVarInst(stack, "float", fSlow28, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider28)))))
	DeclareVarInst(stack, "float", fSlow29, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider29)))))
	DeclareVarInst(stack, "float", fSlow30, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider30)))))
	DeclareVarInst(stack, "float", fSlow31, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider31)))))
	DeclareVarInst(stack, "float", fSlow32, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider32)))))
	DeclareVarInst(stack, "float", fSlow33, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider33)))))
	DeclareVarInst(stack, "float", fSlow34, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider34)))))
	DeclareVarInst(stack, "float", fSlow35, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider35)))))
	DeclareVarInst(stack, "float", fSlow36, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider36)))))
	DeclareVarInst(stack, "float", fSlow37, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider37)))))
	DeclareVarInst(stack, "float", fSlow38, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider38)))))
	DeclareVarInst(stack, "float", fSlow39, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider39)))))
	DeclareVarInst(stack, "float", fSlow40, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider40)))))
	DeclareVarInst(stack, "float", fSlow41, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider41)))))
	DeclareVarInst(stack, "float", fSlow42, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider42)))))
	DeclareVarInst(stack, "float", fSlow43, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider43)))))
	DeclareVarInst(stack, "float", fSlow44, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider44)))))
	DeclareVarInst(stack, "float", fSlow45, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider45)))))
	DeclareVarInst(stack, "float", fSlow46, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider46)))))
	DeclareVarInst(stack, "float", fSlow47, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider47)))))
	DeclareVarInst(stack, "float", fSlow48, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider48)))))
	DeclareVarInst(stack, "float", fSlow49, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider49)))))
	DeclareVarInst(stack, "float", fSlow50, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider50)))))
	DeclareVarInst(stack, "float", fSlow51, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider51)))))
	DeclareVarInst(stack, "float", fSlow52, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider52)))))
	DeclareVarInst(stack, "float", fSlow53, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider53)))))
	DeclareVarInst(stack, "float", fSlow54, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider54)))))
	DeclareVarInst(stack, "float", fSlow55, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider55)))))
	DeclareVarInst(stack, "float", fSlow56, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider56)))))
	DeclareVarInst(stack, "float", fSlow57, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider57)))))
	DeclareVarInst(stack, "float", fSlow58, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider58)))))
	DeclareVarInst(stack, "float", fSlow59, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider59)))))
	DeclareVarInst(stack, "float", fSlow60, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider60)))))
	DeclareVarInst(stack, "float", fSlow61, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider61)))))
	DeclareVarInst(stack, "float", fSlow62, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider62)))))
	DeclareVarInst(stack, "float", fSlow63, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider63)))))
	EndBlock

======= Compute DSP ==========

Instructions complexity
Load = 147
Store = 9
Binop = 122
Numbers = 2
Declare = 9
Cast = 16
Select = 0
Loop = 1
Funcall = 0

ForLoopInst 
	DeclareVarInst(loop, "int", i, Int32(0))
	BinopInst("<", LoadVarInst(loop, i), LoadVarInst(kFunArgs, count))
	StoreVarInst(loop, i, BinopInst("+", LoadVarInst(loop, i), Int32(1)))
	BlockInst 
		DeclareVarInst(stack, "float", fTemp0, CastInst("float", LoadVarInst(stack, input0[LoadVarInst(loop, i)])))
		DeclareVarInst(stack, "float", fTemp1, CastInst("float", LoadVarInst(stack, input1[LoadVarInst(loop, i)])))
		DeclareVarInst(stack, "float", fTemp2, CastInst("float", LoadVarInst(stack, input2[LoadVarInst(loop, i)])))
		DeclareVarInst(stack, "float", fTemp3, CastInst("float", LoadVarInst(stack, input3[LoadVarInst(loop, i)])))
		DeclareVarInst(stack, "float", fTemp4, CastInst("float", LoadVarInst(stack, input4[LoadVarInst(loop, i)])))
		DeclareVarInst(stack, "float", fTemp5, CastInst("float", LoadVarInst(stack, input5[LoadVarInst(loop, i)])))
		DeclareVarInst(stack, "float", fTemp6, CastInst("float", LoadVarInst(stack, input6[LoadVarInst(loop, i)])))
		DeclareVarInst(stack, "float", fTemp7, CastInst("float", LoadVarInst(stack, input7[LoadVarInst(loop, i)])))
		StoreVarInst(stack, output0[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow0), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow1), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow2), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow3), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow4), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow5), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow6), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow7), LoadVarInst(stack, fTemp7)))))
		StoreVarInst(stack, output1[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow8), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow9), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow10), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow11), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow12), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow13), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow14), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow15), LoadVarInst(stack, fTemp7)))))
		StoreVarInst(stack, output2[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow16), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow17), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow18), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow19), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow20), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow21), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow22), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow23), LoadVarInst(stack, fTemp7)))))
		StoreVarInst(stack, output3[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow24), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow25), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow26), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow27), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow28), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow29), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow30), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow31), LoadVarInst(stack, fTemp7)))))
		StoreVarInst(stack, output4[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow32), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow33), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow34), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow35), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow36), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow37), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow38), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow39), LoadVarInst(stack, fTemp7)))))
		StoreVarInst(stack, output5[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow40), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow41), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow42), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow43), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow44), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow45), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow46), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow47), LoadVarInst(stack, fTemp7)))))
		StoreVarInst(stack, output6[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow48), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow49), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow50), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow51), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow52), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow53), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow54), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow55), LoadVarInst(stack, fTemp7)))))
		StoreVarInst(stack, output7[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow56), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow57), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow58), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow59), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow60), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow61), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow62), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow63), LoadVarInst(stack, fTemp7)))))
		EndBlock
	EndForLoop

======= Flatten FIR ==========

BlockInst 
	========== Declaration part ==========
	DeclareFunInst("float", "powf", "float", dummy0, "float", dummy1)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider0)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider1)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider2)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider3)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider4)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider5)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider6)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider7)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider8)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider9)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider10)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider11)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider12)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider13)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider14)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider15)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider16)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider17)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider18)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider19)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider20)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider21)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider22)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider23)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider24)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider25)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider26)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider27)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider28)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider29)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider30)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider31)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider32)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider33)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider34)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider35)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider36)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider37)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider38)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider39)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider40)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider41)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider42)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider43)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider44)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider45)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider46)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider47)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider48)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider49)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider50)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider51)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider52)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider53)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider54)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider55)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider56)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider57)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider58)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider59)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider60)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider61)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider62)
	DeclareVarInst(struct, "FAUSTFLOAT", fVslider63)
	DeclareVarInst(struct, "int", fSamplingFreq)
	========== Init method ==========
	StoreVarInst(struct, fSamplingFreq, LoadVarInst(kFunArgs, samplingFreq))
	StoreVarInst(struct, fVslider0, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider1, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider2, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider3, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider4, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider5, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider6, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider7, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider8, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider9, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider10, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider11, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider12, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider13, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider14, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider15, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider16, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider17, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider18, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider19, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider20, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider21, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider22, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider23, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider24, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider25, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider26, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider27, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider28, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider29, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider30, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider31, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider32, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider33, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider34, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider35, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider36, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider37, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider38, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider39, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider40, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider41, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider42, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider43, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider44, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider45, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider46, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider47, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider48, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider49, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider50, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider51, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider52, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider53, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider54, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider55, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider56, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider57, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider58, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider59, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider60, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider61, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider62, CastInst("FAUSTFLOAT", Double(-10.0f)))
	StoreVarInst(struct, fVslider63, CastInst("FAUSTFLOAT", Double(-10.0f)))
	========== Static init method ==========
	========== Subcontainers ==========
	========== Compute control ==========
	DeclareVarInst(stack, FAUSTFLOAT*, input0, LoadVarInst(kFunArgs, inputs[Int32(0)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input1, LoadVarInst(kFunArgs, inputs[Int32(1)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input2, LoadVarInst(kFunArgs, inputs[Int32(2)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input3, LoadVarInst(kFunArgs, inputs[Int32(3)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input4, LoadVarInst(kFunArgs, inputs[Int32(4)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input5, LoadVarInst(kFunArgs, inputs[Int32(5)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input6, LoadVarInst(kFunArgs, inputs[Int32(6)]))
	DeclareVarInst(stack, FAUSTFLOAT*, input7, LoadVarInst(kFunArgs, inputs[Int32(7)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output0, LoadVarInst(kFunArgs, outputs[Int32(0)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output1, LoadVarInst(kFunArgs, outputs[Int32(1)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output2, LoadVarInst(kFunArgs, outputs[Int32(2)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output3, LoadVarInst(kFunArgs, outputs[Int32(3)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output4, LoadVarInst(kFunArgs, outputs[Int32(4)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output5, LoadVarInst(kFunArgs, outputs[Int32(5)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output6, LoadVarInst(kFunArgs, outputs[Int32(6)]))
	DeclareVarInst(stack, FAUSTFLOAT*, output7, LoadVarInst(kFunArgs, outputs[Int32(7)]))
	DeclareVarInst(stack, "float", fSlow0, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider0)))))
	DeclareVarInst(stack, "float", fSlow1, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider1)))))
	DeclareVarInst(stack, "float", fSlow2, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider2)))))
	DeclareVarInst(stack, "float", fSlow3, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider3)))))
	DeclareVarInst(stack, "float", fSlow4, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider4)))))
	DeclareVarInst(stack, "float", fSlow5, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider5)))))
	DeclareVarInst(stack, "float", fSlow6, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider6)))))
	DeclareVarInst(stack, "float", fSlow7, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider7)))))
	DeclareVarInst(stack, "float", fSlow8, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider8)))))
	DeclareVarInst(stack, "float", fSlow9, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider9)))))
	DeclareVarInst(stack, "float", fSlow10, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider10)))))
	DeclareVarInst(stack, "float", fSlow11, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider11)))))
	DeclareVarInst(stack, "float", fSlow12, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider12)))))
	DeclareVarInst(stack, "float", fSlow13, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider13)))))
	DeclareVarInst(stack, "float", fSlow14, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider14)))))
	DeclareVarInst(stack, "float", fSlow15, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider15)))))
	DeclareVarInst(stack, "float", fSlow16, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider16)))))
	DeclareVarInst(stack, "float", fSlow17, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider17)))))
	DeclareVarInst(stack, "float", fSlow18, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider18)))))
	DeclareVarInst(stack, "float", fSlow19, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider19)))))
	DeclareVarInst(stack, "float", fSlow20, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider20)))))
	DeclareVarInst(stack, "float", fSlow21, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider21)))))
	DeclareVarInst(stack, "float", fSlow22, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider22)))))
	DeclareVarInst(stack, "float", fSlow23, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider23)))))
	DeclareVarInst(stack, "float", fSlow24, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider24)))))
	DeclareVarInst(stack, "float", fSlow25, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider25)))))
	DeclareVarInst(stack, "float", fSlow26, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider26)))))
	DeclareVarInst(stack, "float", fSlow27, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider27)))))
	DeclareVarInst(stack, "float", fSlow28, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider28)))))
	DeclareVarInst(stack, "float", fSlow29, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider29)))))
	DeclareVarInst(stack, "float", fSlow30, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider30)))))
	DeclareVarInst(stack, "float", fSlow31, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider31)))))
	DeclareVarInst(stack, "float", fSlow32, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider32)))))
	DeclareVarInst(stack, "float", fSlow33, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider33)))))
	DeclareVarInst(stack, "float", fSlow34, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider34)))))
	DeclareVarInst(stack, "float", fSlow35, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider35)))))
	DeclareVarInst(stack, "float", fSlow36, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider36)))))
	DeclareVarInst(stack, "float", fSlow37, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider37)))))
	DeclareVarInst(stack, "float", fSlow38, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider38)))))
	DeclareVarInst(stack, "float", fSlow39, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider39)))))
	DeclareVarInst(stack, "float", fSlow40, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider40)))))
	DeclareVarInst(stack, "float", fSlow41, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider41)))))
	DeclareVarInst(stack, "float", fSlow42, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider42)))))
	DeclareVarInst(stack, "float", fSlow43, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider43)))))
	DeclareVarInst(stack, "float", fSlow44, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider44)))))
	DeclareVarInst(stack, "float", fSlow45, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider45)))))
	DeclareVarInst(stack, "float", fSlow46, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider46)))))
	DeclareVarInst(stack, "float", fSlow47, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider47)))))
	DeclareVarInst(stack, "float", fSlow48, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider48)))))
	DeclareVarInst(stack, "float", fSlow49, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider49)))))
	DeclareVarInst(stack, "float", fSlow50, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider50)))))
	DeclareVarInst(stack, "float", fSlow51, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider51)))))
	DeclareVarInst(stack, "float", fSlow52, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider52)))))
	DeclareVarInst(stack, "float", fSlow53, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider53)))))
	DeclareVarInst(stack, "float", fSlow54, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider54)))))
	DeclareVarInst(stack, "float", fSlow55, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider55)))))
	DeclareVarInst(stack, "float", fSlow56, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider56)))))
	DeclareVarInst(stack, "float", fSlow57, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider57)))))
	DeclareVarInst(stack, "float", fSlow58, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider58)))))
	DeclareVarInst(stack, "float", fSlow59, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider59)))))
	DeclareVarInst(stack, "float", fSlow60, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider60)))))
	DeclareVarInst(stack, "float", fSlow61, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider61)))))
	DeclareVarInst(stack, "float", fSlow62, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider62)))))
	DeclareVarInst(stack, "float", fSlow63, FunCallInst("powf", Float(10.0f), BinopInst("*", Float(0.0500000007f), CastInst("float", LoadVarInst(struct, fVslider63)))))
	========== Compute DSP ==========
	ForLoopInst 
		DeclareVarInst(loop, "int", i, Int32(0))
		BinopInst("<", LoadVarInst(loop, i), LoadVarInst(kFunArgs, count))
		StoreVarInst(loop, i, BinopInst("+", LoadVarInst(loop, i), Int32(1)))
		BlockInst 
			DeclareVarInst(stack, "float", fTemp0, CastInst("float", LoadVarInst(stack, input0[LoadVarInst(loop, i)])))
			DeclareVarInst(stack, "float", fTemp1, CastInst("float", LoadVarInst(stack, input1[LoadVarInst(loop, i)])))
			DeclareVarInst(stack, "float", fTemp2, CastInst("float", LoadVarInst(stack, input2[LoadVarInst(loop, i)])))
			DeclareVarInst(stack, "float", fTemp3, CastInst("float", LoadVarInst(stack, input3[LoadVarInst(loop, i)])))
			DeclareVarInst(stack, "float", fTemp4, CastInst("float", LoadVarInst(stack, input4[LoadVarInst(loop, i)])))
			DeclareVarInst(stack, "float", fTemp5, CastInst("float", LoadVarInst(stack, input5[LoadVarInst(loop, i)])))
			DeclareVarInst(stack, "float", fTemp6, CastInst("float", LoadVarInst(stack, input6[LoadVarInst(loop, i)])))
			DeclareVarInst(stack, "float", fTemp7, CastInst("float", LoadVarInst(stack, input7[LoadVarInst(loop, i)])))
			StoreVarInst(stack, output0[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow0), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow1), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow2), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow3), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow4), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow5), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow6), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow7), LoadVarInst(stack, fTemp7)))))
			StoreVarInst(stack, output1[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow8), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow9), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow10), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow11), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow12), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow13), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow14), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow15), LoadVarInst(stack, fTemp7)))))
			StoreVarInst(stack, output2[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow16), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow17), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow18), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow19), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow20), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow21), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow22), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow23), LoadVarInst(stack, fTemp7)))))
			StoreVarInst(stack, output3[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow24), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow25), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow26), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow27), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow28), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow29), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow30), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow31), LoadVarInst(stack, fTemp7)))))
			StoreVarInst(stack, output4[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow32), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow33), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow34), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow35), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow36), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow37), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow38), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow39), LoadVarInst(stack, fTemp7)))))
			StoreVarInst(stack, output5[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow40), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow41), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow42), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow43), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow44), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow45), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow46), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow47), LoadVarInst(stack, fTemp7)))))
			StoreVarInst(stack, output6[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow48), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow49), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow50), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow51), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow52), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow53), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow54), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow55), LoadVarInst(stack, fTemp7)))))
			StoreVarInst(stack, output7[LoadVarInst(loop, i)], CastInst("FAUSTFLOAT", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("+", BinopInst("*", LoadVarInst(stack, fSlow56), LoadVarInst(stack, fTemp0)), BinopInst("*", LoadVarInst(stack, fSlow57), LoadVarInst(stack, fTemp1))), BinopInst("*", LoadVarInst(stack, fSlow58), LoadVarInst(stack, fTemp2))), BinopInst("*", LoadVarInst(stack, fSlow59), LoadVarInst(stack, fTemp3))), BinopInst("*", LoadVarInst(stack, fSlow60), LoadVarInst(stack, fTemp4))), BinopInst("*", LoadVarInst(stack, fSlow61), LoadVarInst(stack, fTemp5))), BinopInst("*", LoadVarInst(stack, fSlow62), LoadVarInst(stack, fTemp6))), BinopInst("*", LoadVarInst(stack, fSlow63), LoadVarInst(stack, fTemp7)))))
			EndBlock
		EndForLoop
	EndBlock

======= Object memory footprint ==========

Heap size int = 4 bytes
Heap size int* = 0 bytes
Heap size real = 256 bytes
Heap size = 260 bytes
Stack size in compute = 384 bytes

