## yann nina version 

dspsrc  := $(wildcard *.dsp)
cppsrc  := $(addprefix $(DEST), $(dspsrc:.dsp=.cpp))
appl 	:= $(addprefix $(DEST), $(dspsrc:.dsp=$(EXT)))

all :  $(appl)

$(DEST)% : %.dsp
	install -d $@
	cp -r /usr/local/lib/faust/iOS/* $@
	faust $(VEC) -a $(ARCH) $< -o $@/ios-faust.h
	xcodebuild -project $@/iOS.xcodeproj PRODUCT_NAME=$(<:.dsp=)
	cp -r $@/build/Release-iphoneos/$(<:.dsp=.app) $@/../

clean :
	rm -f $(DEST)
