dspsrc  := $(wildcard *.dsp)
cppsrc  := $(addprefix $(DEST), $(dspsrc:.dsp=.cpp))
appl 	:= $(addprefix $(DEST), $(dspsrc:.dsp=$(EXT)))


all :  $(appl)


$(DEST)%$(EXT) : %.dsp 
	faust -lang java -cn $(<:.dsp=) -a $(ARCH) $< -o $@
	javac $@
	cd $(DEST) && jar cvfe $(<:.dsp=).jar $(<:.dsp=) *.class && rm *.class	

clean :
	rm -f $(DEST)
