DEST	:= ladspadir/
dspsrc  := $(wildcard *.dsp)
cppsrc  := $(addprefix $(DEST), $(dspsrc:.dsp=.cpp))
modules	:= $(addprefix $(DEST),  $(dspsrc:%.dsp=%.so))
libs    := $(wildcard *.lib)

###allcpp: $(cppsrc)

allmodules: $(modules)

$(DEST)%.so: $(DEST)%.cpp
	$(CXX) -fPIC -shared -O3 $(CXXFLAGS) -Dmydsp=$(patsubst %.so,%,$(notdir $@)) $< -o $@

$(DEST)%.cpp: %.dsp *.lib
	faust $(VEC) -a ladspa.cpp $< -o $@

clean:
	rm -rf $(DEST)
