
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"filterOSC\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"68\",\"inputs\":\"0\",\"outputs\":\"1\",\"meta\":[{\"author\":\"JOS, revised by RM\"},{\"basics.lib/name\":\"Faust Basic Element Library\"},{\"basics.lib/version\":\"0.0\"},{\"description\":\"Simple application demoing filter based oscillators.\"},{\"filters.lib/name\":\"Faust Filters Library\"},{\"filters.lib/version\":\"0.0\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"filterOSC\"},{\"oscillators.lib/name\":\"Faust Oscillator Library\"},{\"oscillators.lib/version\":\"0.0\"},{\"signals.lib/name\":\"Faust Signal Routing Library\"},{\"signals.lib/version\":\"0.0\"},{\"version\":\"0.0\"}],\"ui\":[{\"type\":\"vgroup\",\"label\":\"SINE WAVE OSCILLATOR oscrs\",\"meta\":[{\"0\":\"\"},{\"tooltip\":\"Sine oscillator based   on 2D vector rotation\"}],\"items\":[{\"type\":\"hslider\",\"label\":\"Amplitude\",\"address\":\"/SINE_WAVE_OSCILLATOR_oscrs/Amplitude\",\"index\":\"0\",\"meta\":[{\"1\":\"\"},{\"tooltip\":\"Sawtooth waveform   amplitude\"},{\"unit\":\"dB\"}],\"init\":\"-20\",\"min\":\"-120\",\"max\":\"10\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"Frequency\",\"address\":\"/SINE_WAVE_OSCILLATOR_oscrs/Frequency\",\"index\":\"32\",\"meta\":[{\"2\":\"\"},{\"tooltip\":\"Sine wave frequency as a Piano Key (PK) number (A440 = 49 PK)\"},{\"unit\":\"PK\"}],\"init\":\"49\",\"min\":\"1\",\"max\":\"88\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"Portamento\",\"address\":\"/SINE_WAVE_OSCILLATOR_oscrs/Portamento\",\"index\":\"40\",\"meta\":[{\"3\":\"\"},{\"scale\":\"log\"},{\"tooltip\":\"Portamento (frequency-glide) time-constant in seconds\"},{\"unit\":\"sec\"}],\"init\":\"0.1\",\"min\":\"0.001\",\"max\":\"10\",\"step\":\"0.001\"}]}]}";
}
