faust-quick-reference.pdf : faust-quick-reference.tex 
	pdflatex faust-quick-reference.tex
	rail faust-quick-reference
	pdflatex faust-quick-reference.tex
	
clean :
	rm -f *.aux *.dvi *.rai *.rao *.log *~
	
	