#!/bin/bash

#####################################################################
#                                                                   #
#               Compiles Faust programs to impulse tests			#
#               (c) Grame, 2016                                     #
#                                                                   #
#####################################################################


#-------------------------------------------------------------------
# Analyze command arguments :
# faust options                 -> OPTIONS
# if -omp : -openmp or -fopenmp -> OPENMP
# existing *.dsp files          -> FILES
#

# PHASE 1 : Look for -icc option to force use of intel icc (actually icpc)
# without having to configure CXX and CXXFLAGS
for p in $@; do
	if [ "$p" = -icc ]; then
		CXX=icpc
		CXXFLAGS='-O3 -xT -ftz -fno-alias -fp-model fast=2'
    fi
done

mode="scal" # can be: scal, vec, sch, omp

#PHASE 2 : dispatch command arguments
for p in $@; do
    if [ "$p" = -omp ]; then
		mode="omp"
        if [[ $CXX == "icpc" ]]; then
            OMP="-openmp"
        else
            OMP="-fopenmp"
        fi
    elif [ "$p" = -vec ]; then
    	mode="vec"
		OPTIONS="$OPTIONS $p"
    elif [ "$p" = -sch ]; then
    	mode="sch"
		OPTIONS="$OPTIONS $p"
    elif [ "$p" = -scal ]; then
    	mode="scal"
    elif [ "$p" = -icc ]; then
    	ignore=" "
    elif [ ${p:0:1} = "-" ]; then
	    OPTIONS="$OPTIONS $p"
	elif [[ -f "$p" ]]; then
	    FILES="$FILES $p"
	else
	    OPTIONS="$OPTIONS $p"
	fi
done


#-------------------------------------------------------------------
# compile the *.dsp files

for f in $FILES; do

	# compile Faust to c++
    faust -lang c $OPTIONS -i -a impulsearch2.cpp "$f" -o "$f.cpp" || exit

	# compile c++ to binary
	(
		${CXX=g++} ${CXXFLAGS=-O3 -std=c++11 -pthread} $OMP "$f.cpp" -o "${f%.dsp}"
	) > /dev/null || exit

	# run the resulting binary to generate the impulse response
	./"${f%.dsp}" -n 60000

	# cleanup
    rm "${f%.dsp}" "$f.cpp"
done

