#! /bin/bash -e

#  usage : faust2graph foo.dsp        -> foo-sig.pdf
#  usage : faust2graph -svg foo.dsp   -> foo-sig.svg

. usage.sh

FILES=""
IGNORE=""
FORMAT="pdf"

# Analyze command line
for p in $@; do
     if [ $p = "-help" ] || [ $p = "-h" ]; then
        usage faust2graph "[options] <file.dsp>" to display the graph of tasks
        option "-svg" to display the SVG
        exit
    fi
    if [ "$p" = -svg ]; then
        FORMAT="svg"
    elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
        FILES="$FILES $p"
    else
        IGNORE="$IGNORE $p"
    fi
done

for f in $FILES; do
    faust -vec -tg $f -o /dev/null || exit
    dot -T$FORMAT $f.dot -o $f.graph.$FORMAT || exit
    rm $f.dot
done
