#!/bin/bash

#####################################################################
#                                                                   #
#               Cross-compiles Faust programs to Max/MSP            #
#			from 	: Linux or OSX			    #
#			to	: Windows 32			    #
#               (c) Grame, 2011                                     #
#                                                                   #
#####################################################################

#------------------------------------------------------------------------------
# 1/ MAX/MSP SDK Should be installed somewhere
MAXSDK=/usr/local/include/c74support
. faustpath
EXT="~.mxe"

if [ ! -d "${MAXSDK}" ]; then
 	echo "Unable to locate Max/Msp SDK: MAXSDK=${MAXSDK}" 1>&2
 	exit 1
fi

#------------------------------------------------------------------------------
# 2/ mingw crosscompiler should be installed ('mingw32' package on Ubuntu)
# It must be in the PATH and the exact prefix should be specified in
# the environment variable MINGWPREFIX

: ${MINGWPREFIX="i686-w64-mingw32-"}
CXX="${MINGWPREFIX}g++"
(which "$CXX" >/dev/null) || (echo "MingW compiler $CXX not found"; exit 1)
DLLWRAP="${MINGWPREFIX}dllwrap --target=i686-w64-mingw32"
STRIP="${MINGWPREFIX}strip"


#-----------------------------------------------------------------------------
# Compilation flags
LIBS="$MAXSDK/max-includes/MaxAPI.lib  $MAXSDK/msp-includes/MaxAudio.lib"
CXXINCS="-I$MAXSDK/max-includes -I$MAXSDK/msp-includes "
CXXFLAGS="-DWIN_VERSION -DWIN_EXT_VERSION"

#-------------------------------------------------------------------
# Set Faust include path

if [ -f $FAUST_LIB_PATH/music.lib ]
then
    FAUSTLIB=$FAUST_LIB_PATH
elif [ -f /usr/local/share/faust/music.lib ]
then
    FAUSTLIB=/usr/local/share/faust
elif [ -f /usr/share/faust/music.lib ]
then
    FAUSTLIB=/usr/share/faust
else
    echo "ERROR : $0 cannot find Faust library dir (usually /usr/local/share/faust)"
fi

#-------------------------------------------------------------------
# Analyze command arguments :
# faust options                 -> OPTIONS
# if -omp : -openmp or -fopenmp -> OPENMP
# existing *.dsp files          -> FILES
#


#PHASE 2 : dispatch command arguments
for p in $@; do
    if [ "$p" = -omp ]; then
        if [[ $CXX == "icpc" ]]; then
            OMP="-openmp"
        else
            OMP="-fopenmp"
        fi
    fi

    if [ "$p" = -icc ]; then
    	ignore=" "
    elif [ ${p:0:1} = "-" ]; then
	    OPTIONS="$OPTIONS $p"
	elif [[ -e "$p" ]]; then
	    FILES="$FILES $p"
	else
	    OPTIONS="$OPTIONS $p"
	fi
done

BINARIES=""

#PHASE 3 : Compile each dsp files in $FILES
for p in $FILES; do

    CUR=$(pwd)
    f=$(basename "$p")
	SRCDIR=$(dirname "$p")

    # creates a temporary dir
    TDR=$(mktemp -d faust.XXX)
	TMP="$TDR/${f%.dsp}"
    mkdir "$TMP"

    # compile faust to c++
	faust -i -a $FAUSTLIB/max-msp/max-msp.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp" || exit

    # compile c++ to binary
    (
		cd "$TMP"
		echo "TMP=$TMP"

		# we need to create the .def file needed to generate the .dll
		echo "LIBRARY     ${f%.dsp}~" 						 > ${f%.dsp}.def
		echo "DESCRIPTION 'Faust generated MAX plugin'" 	>> ${f%.dsp}.def
		echo "EXPORTS     main" 							>> ${f%.dsp}.def

		$CXX $CXXINCS $CXXFLAGS -c "${f%.dsp}.cpp" -o "${f%.dsp}.o"
		$DLLWRAP --driver-name $CXX --def ${f%.dsp}.def *.o  $LIBS -static-libstdc++ -static-libgcc -o "${f%.dsp}$EXT"
		$STRIP "${f%.dsp}$EXT"
    ) > /dev/null || exit

	cp "$TMP/${f%.dsp}$EXT" "$SRCDIR"

    # remove temporary directory
    rm -rf "$TDR"

    # collect binary file name for FaustWorks
    BINARIES="$BINARIES$SRCDIR/${f%.dsp}$EXT;"
done

echo "$BINARIES"
