#!/bin/bash

#####################################################################
#                                                                   #
#               Compiles Faust programs to core audio-qt            #
#               (c) Grame, 2009                                     #
#                                                                   #
#####################################################################
PATH=$PATH:/usr/local/bin
FAUST=faust

OSCINC=""
QTDEFS=""
OSCLIB=""
HTTPDINC=""
QTDEFS=""
HTTPDLIB=""


#-------------------------------------------------------------------
# Analyze command arguments :
# faust options                 -> OPTIONS
# if -omp : -openmp or -fopenmp -> OPENMP
# existing *.dsp files          -> FILES
#

# PHASE 1 : Look for -icc option to force use of intel icc (actually icpc)
# without having to configure CXX and CXXFLAGS
for p in $@; do
	if [ "$p" = "-icc" ]; then
		CXX=icpc
		CXXFLAGS='-O3 -xT -ftz -fno-alias -fp-model fast=2'
    fi
done

#PHASE 2 : dispatch command arguments
for p in $@; do
    if [ "$p" = -omp ]; then
        if [[ $CXX == "icpc" ]]; then
            OMP="-openmp"
        else
            OMP="-fopenmp"
        fi
    elif [ "$p" = -icc ]; then
    	ignore=" "
	elif [ "$p" = "-osc" ]; then
		#OSCINC="INCLUDEPATH+=/usr/local/include"
		QTDEFS="DEFINES += OSCCTRL"
		OSCLIB="-L/usr/local/lib/faust/ -lOSCFaust -loscpack"
	elif [ "$p" = "-httpd" ]; then
		HTTPDINC="INCLUDEPATH+=/usr/local/lib/faust/httpdlib"
		QTDEFS="DEFINES += HTTPCTRL"
		HTTPDLIB="-lmicrohttpd -L/usr/local/lib/faust/ -lHTTPDFaust"
    elif [ ${p:0:1} = "-" ]; then
	    OPTIONS="$OPTIONS $p"
	elif [[ -e "$p" ]]; then
	    FILES="$FILES $p"
	else
	    OPTIONS="$OPTIONS $p"        
	fi
done



#-------------------------------------------------------------------
# Check darwin specifics
#
if [[ $(uname) == Darwin ]]; then
    SPEC="-spec macx-g++ -Wnone"
    EXT=".app"
fi

#-------------------------------------------------------------------
# compile the *.dsp files
#
for p in $FILES; do

    CUR=$(pwd)
    f=$(basename "$p")
	SRCDIR=$(dirname "$p")

    # creates a temporary dir 
    TDR=$(mktemp -d faust.XXX)
	TMP="$TDR/${f%.dsp}"
    mkdir "$TMP"

    # compile faust to c++
	$FAUST -i -a ca-qt.cpp $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}.cpp"

    # compile c++ to binary
    (
	    cd "$TMP"
		qmake -project "INCLUDEPATH+=/usr/local/include/" "$HTTPDINC" "LIBS+=-framework CoreAudio -framework AudioUnit -framework CoreServices $OSCLIB $HTTPDLIB" "HEADERS+=/usr/local/include/faust/gui/faustqt.h" "$QTDEFS"
		qmake $SPEC
        make
    ) > /dev/null #2>/dev/null

    rm -rf "$SRCDIR/${f%.dsp}$EXT"
    cp -r "$TMP/${f%.dsp}$EXT" "$SRCDIR/${f%.dsp}$EXT"
    rm -rf "$TDR"

    # collect binary file name for FaustGIDE
    BINARIES="$BINARIES$SRCDIR/${f%.dsp}$EXT;"
done

echo $BINARIES


