#!/bin/bash

#####################################################################
#                                                                   #
#                        faust2wwise generator                      #
#                          (c) Grame, 2025                          #
#                                                                   #
#####################################################################    

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
python ${SCRIPT_DIR}/faust2wwise.py $@