#!/bin/sh

#####################################################################
#                                                                   
#               Compiles Faust programs to Audio Unit       	      
#               (c) Grame 2013                           	               
#                                                                   
#####################################################################

ARCHFILE="au-instrument.cpp"
AUTYPE=aumu
FAUSTAU_CLASS=FaustAUInstrument
COMPTYPE=kAudioUnitType_MusicDevice

#call faust2au with the following parameters an passing all the input arguments
export ARCHFILE
export AUTYPE
export FAUSTAU_CLASS
export COMPTYPE
sh faust2au $@