#! /bin/bash -e

#####################################################################
#                                                                   #
#               Compiles Faust programs to JACK and Rust binary     #
#               (c) Grame, 2017                                     #
#                                                                   #
#####################################################################

. faustpath
. faustoptflags

#PHASE 2 : dispatch command arguments
while [ $1 ]
do
    p=$1

    if [ $p = "-help" ] || [ $p = "-h" ]; then
        echo "faust2jackrust <file.dsp>"
    fi
    
    if [ ${p:0:1} = "-" ]; then
        OPTIONS="$OPTIONS $p"
    elif [[ -f "$p" ]]; then
        FILES="$FILES $p"
    else
        OPTIONS="$OPTIONS $p"
    fi

shift

done


#-------------------------------------------------------------------
# compile the *.dsp files
#

for p in $FILES; do

    f=$(basename "$p")
    SRCDIR=$(dirname "$p")

    # creates the dir
    dspName="${f%.dsp}-rust"
    rm -rf "$SRCDIR/$dspName"

    # create rust project
    cargo new $dspName --bin

    # compile Faust DSP and put in the cargo folder
    faust -a "$FAUSTLIB/minimal-jack.rs" -lang rust "$SRCDIR/$f" -o "$SRCDIR/$dspName/src/main.rs"

    # add JACK dependency
    echo "jack = \"0.5.3\"" >> "$SRCDIR/$dspName/Cargo.toml"

    # build the project
    cd "$SRCDIR/$dspName"
    cargo build --release
    cargo build

done


