#!/bin/bash
if [[ $(uname) == Darwin ]]; then
	APPL='open -a Safari'
else
	APPL=xdg-open
fi

faust2svg $@
$APPL ${1%.dsp}-svg/process.svg&
shift
for f in $@; do
    sleep 1
    $APPL ${f%.dsp}-svg/process.svg&
done

