#!/bin/bash

#-------------------------------------------------------------------
# Set Faust include path

if [ -f $FAUST_LIB_PATH/music.lib ]
then
  FAUSTLIB=$FAUST_LIB_PATH
elif [ -f /usr/local/lib/faust/music.lib ]
then
  FAUSTLIB=/usr/local/lib/faust/
elif [ -f /usr/lib/faust/music.lib ]
then
  FAUSTLIB=/usr/lib/faust/
else
  error "$0: Cannot find Faust library dir (usually /usr/local/lib/faust)"
fi


#-------------------------------------------------------------------
# Analyze command arguments :
# faust options                 -> OPTIONS
# existing *.dsp files          -> FILES
#

for p in $@; do
    if [ $p = "-osc" ]; then
	 OSCDEFS="-DOSCCTRL -L$FAUSTLIB -lOSCFaust -loscpack"
    elif [ $p = "-httpd" ]; then
	 HTTPDEFS="-DHTTPCTRL -L$FAUSTLIB -lHTTPDFaust -lmicrohttpd"
    elif [ ${p:0:1} = "-" ]; then
	    OPTIONS="$OPTIONS $p"
	elif [[ -e "$p" ]]; then
	    FILES="$FILES $p"
	else
	    OPTIONS="$OPTIONS $p"        
	fi
done


#-------------------------------------------------------------------
# compile the *.dsp files
#
for f in $FILES; do
    name=${f%.dsp}
    
    # compile the C++ code
    faust -a $FAUSTLIB/webaudio/webaudio-asm.cpp -i -uim -cn $name $OPTIONS $f -o $name.cpp
    
    # compile the C++ code to asm.js
    emcc -O2 $name.cpp -s TOTAL_STACK=20971520 -s TOTAL_MEMORY=41943040 --pre-js $FAUSTLIB/js/jsscripts.js --pre-js $FAUSTLIB/webaudio/webaudio-asm-header.js --post-js $FAUSTLIB/webaudio/webaudio-asm-footer.js -o $name-temp.js \
        -s EXPORTED_FUNCTIONS="['_"$name"_constructor','_"$name"_destructor','_"$name"_compute', '_"$name"_getNumInputs', '_"$name"_getNumOutputs', '_"$name"_setValue', '_"$name"_getValue', '_"$name"_getJSON', '_"$name"_poly_constructor','_"$name"_poly_destructor','_"$name"_poly_compute', '_"$name"_poly_getNumInputs', '_"$name"_poly_getNumOutputs', '_"$name"_poly_setValue', '_"$name"_poly_getValue', '_"$name"_poly_getJSON', '_"$name"_poly_noteOn', '_"$name"_poly_noteOff']"
    
    # compose the self-contained HTML page
    echo "<html>" > $name.html
    echo "<head>" >> $name.html
    echo "<meta charset=\"UTF-8\">" >> $name.html
    echo "<style type=\"text/css\">" >> $name.html
    cat $FAUSTLIB/js/stylesheet.js >> $name.html
    echo "</style>" >> $name.html
    echo "<script type=\"text/javascript\">" >> $name.html
    sed -e "s/DSP/"$name"/g" $name-temp.js >> $name.html
    echo "</script>" >> $name.html 
    echo "</head>" >> $name.html
    sed -e "s/DSP/"$name"/g" $FAUSTLIB/webaudio/webaudio-asm-footer-links.html >> $name.html
    
    rm $name-temp.js
    rm $name.cpp

	# generate svg
	faust2svg $f
done
