#!/bin/bash

#####################################################################
#                                                                   #
#               Search where Faust is installed                  #
#               (c) Grame, 2009                                     #
#                                                                   #
#####################################################################

#-------------------------------------------------------------------------------
# Search where Faust is installed. Store '.../lib/faust/' in $FAUSTLIB
# and '.../include/(faust)' in $FAUSTINC 
#
# USAGE :
# add line << . faustpath >> to your script
# and use -L$FAUSTLIB and -I$FAUSTINC where needed


FAUSTLIB=""; FAUSTINC=""; 
FPATH="$FAUST_INSTALL /usr/local /usr /opt /opt/local"; # <- where to search
for f in $FPATH; do
	if [ -e $f/lib/faust ]; 	then FAUSTLIB=$f/lib/faust;	fi
	if [ -e $f/include/faust ];	then FAUSTINC=$f/include/; fi
done
if [ -z "$FAUSTLIB" -o -z "$FAUSTINC" ]; then 
	echo "ERROR : $0 cannot find Faust directories (normally /usr/local/include/faust and /usr/local/lib/faust)"; 
	exit 1;
fi
