#! /bin/bash -e

#####################################################################
#                                                                   #
#  Compiles Faust programs to Unity audio plugins (OSX)	            #
#                                                                   #
#  (see https://docs.unity3d.com/Manual/Audio.html					#
#  and https://bitbucket.org/Unity-Technologies/nativeaudioplugins)	#
#                                                                   #
#  (c) Grame, 2017                                                  #
#                                                                   #
#####################################################################
#
# Structure of a plugin for OSX
#--------------------------------
# AudioPluginFoo.bundle/
#	Contents/
#		MacOS/
#			AudioPluginFoo
#		Info.plist
#

CXXFLAGS="-I. -O2 -fPIC -arch i386 -arch x86_64"
LDFLAGS="-bundle"
CXX="c++"


createInfoPList() {
cat > "$2" << DELIM
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>16D32</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>$1</string>
	<key>CFBundleIdentifier</key>
	<string>com.yourcompany.$1</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$1</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>CFPlugInDynamicRegisterFunction</key>
	<string></string>
	<key>CFPlugInDynamicRegistration</key>
	<string>NO</string>
	<key>CFPlugInFactories</key>
	<dict>
		<key>00000000-0000-0000-0000-000000000000</key>
		<string>MyFactoryFunction</string>
	</dict>
	<key>CFPlugInTypes</key>
	<dict>
		<key>00000000-0000-0000-0000-000000000000</key>
		<array>
			<string>00000000-0000-0000-0000-000000000000</string>
		</array>
	</dict>
	<key>CFPlugInUnloadFunction</key>
	<string></string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>8C1002</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>16C58</string>
	<key>DTSDKName</key>
	<string>macosx10.12</string>
	<key>DTXcode</key>
	<string>0821</string>
	<key>DTXcodeBuild</key>
	<string>8C1002</string>
</dict>
</plist>
DELIM
}

CUR=$(pwd)

for p in $@; do

    if [ $p = "-help" ] || [ $p = "-h" ]; then
        echo "faust2osxiosunity [-ios] <file1.dsp> [<file2.dsp>]"
        echo "Use '-ios' to create an iOS static library"
        echo "Use 'faust2unity -osx -ios' to also create the c# and JSON files"
        echo "See architecture/unity/README.md for more info"
        exit
    fi

    if [ $p = "-ios" ]; then
        IOS=1
        CXXFLAGS="-arch armv7 -arch armv7s -arch arm64 -pipe -O3 -gdwarf-2"
    elif [ ${p:0:1} = "-" ]; then
        OPTIONS="$OPTIONS $p"
    elif [[ -f "$p" ]]; then
        FILES="$FILES $p"
    else
        OPTIONS="$OPTIONS $p"
    fi

done

for f in $FILES; do
    SRCDIR=$(dirname "$f")
    FNAME=$(basename "$f")
    NAME=${FNAME%.dsp}

    if [ "$IOS" = "1" ]; then

        DIR=$SRCDIR/FaustPlugin_iOS_$NAME
        if [ -d "$DIR" ]; then
            rm -rf "$DIR"
        fi
        mkdir "$DIR"

        # compiles faust to c++
        faust -i -a unity/unityplugin.cpp "$SRCDIR/$NAME.dsp" -o $NAME.cpp || (echo "$FNAME : Faust to C++ compilation failed in faust2osxiosunity -ios"; exit 1)


        $CXX $CXXFLAGS -DAPPLE -fembed-bitcode -DPLUGINNAME="libFaustPlugin_$NAME" -std=c++11 -stdlib=libc++ -c -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk $NAME.cpp -o $NAME.o || (echo "$FNAME : C++ to iOS library compilation failed in faust2osxiosunity -ios"; exit 1)
        libtool $NAME.o -o libFaustPlugin_$NAME.a
        rm $NAME.o $NAME.cpp
        mv libFaustPlugin_$NAME.a $DIR/libFaustPlugin_$NAME.a
        echo "$FNAME : iOS compilation completed"

    else

        BNAME=libFaustPlugin_${NAME} # should be capitalize

        # creates a temporary dir
        TDR=$(mktemp -d faust.XXX)

        # creates the bundle inside
        BNDL="$TDR/$BNAME.bundle"
        MOS="$BNDL/Contents/MacOS/"
        mkdir -p "$MOS"

        # creates final dir
        DIR=$SRCDIR/FaustPlugin_OSX_$NAME
        if [ -d "$DIR" ]; then
            rm -rf "$DIR"
        fi
        mkdir "$DIR"

        # compile faust to c++
        faust -i -a unity/unityplugin.cpp "$SRCDIR/$NAME.dsp" -o "$MOS/$NAME.cpp" || (echo "$FNAME : Faust to C++ compilation failed in faust2osxiosunity"; exit 1)

        $CXX $CXXFLAGS $LDFLAGS -DAPPLE -DPLUGINNAME="$NAME" "$MOS/$NAME.cpp" -o "$MOS/$BNAME" || (echo "$FNAME : C++ to OSX library compilation failed in faust2osxiosunity"; exit 1)
        rm "$MOS/$NAME.cpp"
        createInfoPList "$BNAME" "$BNDL/Contents/Info.plist" || (echo "$FNAME : Info.plist gerenation failed in faust2osxiosunity"; exit 1)

        rm -rf "$SRCDIR/$BNAME.bundle"
        mv "$BNDL" "$SRCDIR/$DIR/"
        rm -rf $TDR

        echo "$FNAME : OSX compilation completed"

    fi

done
