#! /bin/bash -e

#####################################################################
#                                                                   #
#               Search where Faust is installed and defines   		#
#				$FAUSTLIB and $FAUSTINC so that we can use			#
#				-L$FAUSTLIB and -I$FAUSTINC where needed.			#
#               (c) Grame, 2013                                    #
#                                                                   #
#####################################################################

#-------------------------------------------------------------------------------
# Search where Faust is installed. Store '.../share/faust/' in $FAUSTLIB
# and '.../include/(faust)' in $FAUSTINC 
#
# USAGE :
# add line << . faustpath >> to your script
# and use -L$FAUSTLIB and -I$FAUSTINC where needed

FAUSTLIB=""; FAUSTINC=""; 
FPATH="$FAUST_INSTALL /usr/local /usr /opt /opt/local"; # <- where to search
for f in $FPATH; do
	if [ -e $f/share/faust ]; 	then FAUSTLIB=$f/share/faust;	fi
	if [ -e $f/include/faust ];	then FAUSTINC=$f/include/; fi
done
for f in $FPATH; do
	if [ -e $f/lib/libmicrohttpd.a ]; 	then HTTPLIB=$f/share/faust;	fi
done

if [ -e /etc/faust/faustpath ]; then
 . /etc/faust/faustpath
fi
if [ -e ${HOME}/.faust/faustpath ]; then
 . ${HOME}/.faust/faustpath
fi

if [ -z "$FAUSTLIB" -o -z "$FAUSTINC" ]; then 
	echo "ERROR : $0 cannot find Faust directories (normally /usr/local/include/faust and /usr/local/share/faust)"; 
	exit 1;
fi
