#! /bin/sh -e
if [ "x$(uname -s)" = "xDarwin" ]; then
	APPL='open -a Safari'
else
	APPL=xdg-open
fi

faust2svg $@ || exit
$APPL ${1%.dsp}-svg/process.svg&
shift
for f in $@; do
    sleep 1
    $APPL ${f%.dsp}-svg/process.svg&
done

