#!/bin/bash

if [[ $(uname) == Darwin ]]; then
	#On Darwin build a CoreAudio QT4 application using g++
	for f in $@; do
	
		CUR=$(pwd)
		TMP=/var/tmp/${f%.dsp}
	
		rm -rf $TMP
		install -d $TMP

		faust -a ca-qt.cpp $f -o $TMP/${f%.dsp}.cpp
		
		cd $TMP; qmake -project "INCLUDEPATH+=/usr/local/lib/faust/" "LIBS+=-framework CoreAudio -framework AudioUnit" "HEADERS+=/usr/local/lib/faust/faustqt.h" 
		cd $TMP; qmake -spec macx-g++
		cd $TMP; make 
		cd $CUR; rm -rf ${f%.dsp}.app
		cd $CUR; mv $TMP/${f%.dsp}.app $CUR
		rm -rf $TMP
		echo  ${f%.dsp}.app
	done


else
	echo "$0 is written for Mac OS X ('Darwin') only"

fi

