#!/bin/bash

#####################################################################
#                                                                   #
#        Compiles a Faust program into an alsa-gtk application      #
#               (c) Grame, 2009                                     #
#                                                                   #
#####################################################################


#-------------------------------------------------------------------
# Analyze command arguments :
# faust options                 -> OPTIONS
# if -omp : -openmp or -fopenmp -> OPENMP
# existing *.dsp files          -> FILES
#
for p in $@; do
    if [ "$p" = -omp ]; then
        if [[ $CXX == "icpc" ]]; then
            OMP="-openmp"
        else
            OMP="-fopenmp"
        fi
    fi

    if [ ${p:0:1} = "-" ]; then
        OPTIONS="$OPTIONS $p"
    elif [[ -e "$p" ]]; then
        FILES="$FILES $p"
    else
        OPTIONS="$OPTIONS $p"        
    fi
done


#-------------------------------------------------------------------
# compile the *.dsp files
#
for SRC in $FILES; do
    faust -a alsa-gtk.cpp $OPTIONS "$SRC" -o "$SRC.cpp"
    ${CXX=g++} ${CXXFLAGS=-O3} $OMP `pkg-config --cflags --libs alsa gtk+-2.0` "$SRC.cpp" -o "${SRC%.dsp}"
    rm "$SRC.cpp"
    BINARIES="$BINARIES${SRC%.dsp};"
done

# return the binaries names
echo "$BINARIES"
