#! /bin/bash -e
set -e
#set -x

#####################################################################
#                                                                   #
#               Compiles Faust programs to CoreAudio and QT         #
#               (c) Grame, 2012-2018                                #
#                                                                   #
#####################################################################

. faustpath
. faustoptflags
. usage.sh

CXXFLAGS+=" $MYGCCFLAGS"  # So that additional CXXFLAGS can be used

ARCHFILE=$FAUSTARCH/ca-qt.cpp

[ -d /opt/local/lib ] && OPTLIB=-L/opt/local/lib
ARCHLIB="-L$FAUSTLDDIR -L/usr/local/lib $OPTLIB -framework CoreAudio -framework AudioUnit -framework CoreServices -framework CoreMIDI -framework CoreFoundation"
DEBUG=false

#-------------------------------------------------------------------
#PHASE 1 : dispatch command arguments
#-------------------------------------------------------------------

OSCDEFS=""
OSCLIB=""
POLY="POLY"
DEPLOY="yes"
EFFECT=""
PRESETDIR="auto"
PRESETDEFS=""
NVOICES=-1
ADDEDINCLUDES=""
SOUNDFILE="0"
SOUNDFILEDEFS=""
SOUNDFILEINC=""
SOUNDFILELIBS=""
SAMPLERATEDEFS=""
SAMPLERATELIBS=""
OPT=""

echoHelp() 
{
    usage faust2caqt "[options] [Faust options] <file.dsp>"
    platform MacOS
    require QT
    echo "Compiles Faust programs to CoreAudio and QT"
    option
    options -httpd -osc -midi -qrcode -soundfile
    option "-opt native' to activate the best compilation options for the native CPU"
    option "-opt generic' to activate the best compilation options for a generic CPU"
    option "-nvoices <num>"
    option -resample "to resample soundfiles to the audio driver sample rate"
    option "-effect <effect.dsp>"
    option "-effect auto"
    option "-preset <directory>" "add a preset manager on top of GUI and save the preset files in the given directory"
    option "-preset auto" "add a preset manager on top of GUI and save the preset files in a system temporary directory"
    option -me "to catch math computation exceptions (floating point exceptions and integer div-by-zero or overflow)"
    option -debug "to print all the build steps"
    option -nodeploy
    option "-I include-path" "add an include-directory to the generated Qt project for finding ffunction headers and such"
    option "Faust options"
    exit
}

if [ "$#" -eq 0 ]; then
    echo 'Please, provide a Faust file to process !'
    echo ''
    echoHelp
fi

# dispatch command arguments

while [ $1 ]
do
    p=$1

    if [ $p = "-help" ] || [ $p = "-h" ]; then
        echoHelp
    elif [ "$p" = -debug ]; then
        DEBUG=true
    elif [ $p = "-opt" ]; then
        shift
        OPT=$1
    elif [ $p = "-nodeploy" ]; then
        DEPLOY="no"
    elif [ "$p" = "-icc" ]; then
        ignore=" "
    elif [ "$p" = "-me" ]; then
        MATHDEFS="DEFINES += HAS_MATH_EXCEPTION"
    elif [ $p = "-nvoices" ]; then
        POLYDEFS="DEFINES += POLY"
        shift
        NVOICES=$1
        if [ $NVOICES -ge 0 ]; then
            CXXFLAGS="$CXXFLAGS -DNVOICES=$NVOICES"
        fi
    elif [ $p = "-effect" ]; then
        POLYDEFS="DEFINES += POLY2"
        POLY="POLY2"
        shift
        EFFECT=$1
    elif [ $p = "-midi" ]; then
        MIDIDEFS="DEFINES += MIDICTRL"
    elif [ $p = "-I" ]; then
        shift
        ADDEDINCLUDES+=" INCLUDEPATH+=$1"
    elif [ $p = "-soundfile" ]; then
        SOUNDFILE="1"
        SOUNDFILEDEFS="DEFINES += SOUNDFILE"
        SOUNDFILEINC=$(pkg-config --cflags sndfile | cut -c 3-)
        SOUNDFILELIBS=`pkg-config --static --libs sndfile`
    elif [ $p = "-resample" ]; then
        SAMPLERATEDEFS="DEFINES += SAMPLERATE"
        SAMPLERATELIBS=`pkg-config --cflags --static --libs samplerate`
    elif [ $p = "-osc" ]; then
        OSCDEFS="DEFINES += OSCCTRL"
        OSCLIBS="-lOSCFaust"
    elif [ "$p" = "-httpd" ]; then
        HTTPDEFS="DEFINES += HTTPCTRL"
        HTTPLIBS="-lHTTPDFaust"
        HTTPLIBS1=`pkg-config --cflags --libs libmicrohttpd`
    elif [ "$p" = "-preset" ]; then
        PRESETDEFS="DEFINES += PRESETUI"
        shift
        PRESETDIR=$1
    elif [ "$p" = "-qrcode" ]; then # requires -httpd
        QRDEFS="DEFINES += QRCODECTRL"
    elif [ ${p:0:1} = "-" ]; then
        OPTIONS="$OPTIONS $p"
    elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
        FILES="$FILES $p"
    else
        OPTIONS="$OPTIONS $p"
    fi

shift

done

#-------------------------------------------------------------------
# Check darwin specifics
#-------------------------------------------------------------------

if [[ $(uname) == Darwin ]]; then
    SYS_VERSION=$(uname -v | cut -d : -f1 | cut -d. -f1 | cut -d' ' -f4)
    if [ $SYS_VERSION -ge 13 ]
    then
        SPEC="-spec macx-clang"
        CLANGOPT="QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.15"
        CXXFLAGS="$CXXFLAGS -mmacosx-version-min=10.15"
    else
        SPEC="-spec macx-g++"
        CLANGOPT=""
    fi
    EXT=".app"
fi

#-------------------------------------------------------------------
# compile the *.dsp files
#-------------------------------------------------------------------

for p in $FILES; do

    CUR=$(pwd)
    f=$(basename "$p")
    SRCDIR=$(dirname "$p")

    # creates a temporary dir
    TDR=$(mktemp -d faust.XXXXXX)
    TMP="$TDR/${f%.dsp}"
    mkdir "$TMP"

    # discover best compilation options
    if [ "$OPT" = "generic" ]; then
        echo "Look for best compilation options in 'generic' mode..."
        OPTIONS="$OPTIONS $(faustbench-llvm -notrace -generic $OPTIONS $f)"
        echo $OPTIONS
    elif [ "$OPT" = "native" ]; then
        echo "Look for best compilation options in 'native' mode..."
        OPTIONS="$OPTIONS $(faustbench-llvm -notrace $OPTIONS $f)"
        echo $OPTIONS
    fi

    # compile faust to c++
    if [ $POLY = "POLY2" ]; then
        if [ $EFFECT = "auto" ]; then
            cat > $TMP/effect.dsp << EndOfCode
            adapt(1,1) = _;
            adapt(2,2) = _,_;
            adapt(1,2) = _ <: _,_;
            adapt(2,1) = _,_ :> _;
            adaptor(F,G) = adapt(outputs(F),inputs(G));
            process = adaptor(library("$SRCDIR/$f").process, library("$SRCDIR/$f").effect) : library("$SRCDIR/$f").effect;
EndOfCode
            faust -i -json -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}_tmp.cpp" || exit
            faust -i -cn effect -a minimal-effect.cpp "$TMP/effect.dsp" -o "$TMP/effect.h" || exit
            rm "$TMP/effect.dsp"
        else
            faust -i -json -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}_tmp.cpp" || exit
            faust -i -cn effect -a minimal-effect.cpp "$SRCDIR/$EFFECT" -o "$TMP/effect.h" || exit
        fi
    else
        faust -i -json -a $ARCHFILE $OPTIONS "$SRCDIR/$f" -o "$TMP/${f%.dsp}_tmp.cpp" || exit
    fi

    # add preset management
    if [ $PRESETDIR = "auto" ]; then
        PRESETFILE=`mktemp -t preset.XXXXXXXXXX.cpp` || exit 1
        echo "#define PRESETDIR \"/var/tmp/\"" > "$PRESETFILE"
    else
        PRESETFILE=`mktemp -t preset.XXXXXXXXXX.cpp` || exit 1
        echo "#define PRESETDIR \"$PRESETDIR\"" > "$PRESETFILE"
    fi
    cat "$PRESETFILE" "$TMP/${f%.dsp}_tmp.cpp" > "$TMP/${f%.dsp}.cpp"
    rm "$PRESETFILE" "$TMP/${f%.dsp}_tmp.cpp"

    # compile c++ to binary
    (
        cd "$TMP"
        qmake -project "QT += widgets printsupport network" "CONFIG+=warn_off" "$CLANGOPT" "INCLUDEPATH+=$FAUSTINC" $ADDEDINCLUDES "INCLUDEPATH+=$SOUNDFILEINC" "QMAKE_CXXFLAGS= $CXXFLAGS -Wno-unused-parameter $FAUSTTOOLSFLAGS" "QMAKE_INFO_PLIST=$FAUSTARCH/Info.plist" "LIBS+=$ARCHLIB $SOUNDFILELIBS $SAMPLERATELIBS $OSCLIBS $HTTPLIBS $HTTPLIBS1" "HEADERS+=$FAUSTINC/faust/gui/QTUI.h" "RESOURCES+= $FAUSTINC/faust/gui/Styles/Grey.qrc" "$OSCDEFS" "$HTTPDEFS" "$QRDEFS" "$POLYDEFS" "$MIDIDEFS" "$SOUNDFILEDEFS" "$MATHDEFS" "$SAMPLERATEDEFS" "$PRESETDEFS"
        qmake $SPEC
        make
    ) > /dev/null || exit

    if [ "$SOUNDFILE" = "1" ]; then
        echo $p.json
        # get all soundfiles from the JSON file
        cat $p.json | awk '
            BEGIN { FS=":"; SOFI=0; }
                /"soundfile"/ { SOFI=1; }
                /"url"/ {
                if (SOFI) {
                    match($2, /"[^"]*/);
                    split(substr($2, RSTART+2, RLENGTH-3), res, ";");
                    for (x in res) print substr(res[x], 2, length(res[x])-2);
                    SOFI=0;
                }
            }
        ' > $p-tmp.txt
        # copy found soundfiles in the final binary
        for snd in $(cat $p-tmp.txt); do
            if [ -f $snd ]; then
                if [ ${snd:0:1} = "/" ]; then
                    echo "Warning: soundfile with absolute path is not copied !"
                else
                    # create destination path and possibly create directory
                    sfpath="$TMP/${f%.dsp}$EXT/Contents/Resources/$(dirname $snd)/"
                    if ! [ -d $sfpath ]; then
                        echo "Create $sfpath"
                        mkdir $sfpath
                    fi
                    echo "Copy $snd in ${f%.dsp}$EXT"
                    cp $snd $sfpath
                fi
            else
                echo "Error: file $snd not found !"
            fi
        done
        rm $p-tmp.txt
    fi

    # on Mac add the QT libraries to the bundle
    if [[ $(uname) == Darwin ]]; then
        if [ "$DEPLOY" = "yes" ]; then
            macdeployqt "$TMP/${f%.dsp}$EXT" || exit
        fi
    fi

    rm -rf "$SRCDIR/${f%.dsp}$EXT"
    rm $p.json

    cp -a "$TMP/${f%.dsp}$EXT" "$SRCDIR/${f%.dsp}$EXT"
    if [[ $(uname) == Darwin ]];  then
        codesign --sign - --deep --force "$SRCDIR/${f%.dsp}$EXT"
    fi
    RMTMP=true
    if $DEBUG;
    then
        echo "====> delete temporary folder $TDR ? [Y/n]"
        read DEL
        [ $DEL == "n" ] && RMTMP=false
    fi
    [ $RMTMP == true ] && rm -rf "$TDR"

    # collect binary file name for FaustGIDE
    BINARIES="$BINARIES$SRCDIR/${f%.dsp}$EXT;"
done

echo $BINARIES
