#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Error, this script needs one .dsp file as argument !"
  exit 1
fi 

if [ ! -e $1 ]
then
    echo "Error, the file $1 doesn't exist !"
    exit 1
fi

faust -ig $1 -o /dev/null && dot -Tpdf $1-ins.dot -o $1-ins.pdf && echo "$1-ins.pdf;"
