#!/bin/bash
if [[ $(uname) == Darwin ]]; then
	APPL='open -a Safari'
else
	APPL=firefox
fi

faust2svg $@
$APPL $1-svg/process.svg&
shift
for f in $@; do
    sleep 1
    $APPL $f-svg/process.svg&
done

