prefix := /usr/local

install:
	install faust2jack $(prefix)/bin
	install faust2jaqt $(prefix)/bin
	install faust2alsa $(prefix)/bin
	install faust2plot $(prefix)/bin
	install faust2svg $(prefix)/bin
	install faust2png $(prefix)/bin
	install faust2eps $(prefix)/bin
	install faust2octave $(prefix)/bin
	install faust2firefox $(prefix)/bin
	install faust2jackinternal $(prefix)/bin
	install faust2jackserver $(prefix)/bin
	install faust2coreaudio $(prefix)/bin
	install faust2puredata $(prefix)/bin
	install faust2math $(prefix)/bin

