
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"path1\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"36\",\"inputs\":\"4\",\"outputs\":\"4\",\"meta\":[{\"name\":\"path1\"}],\"ui\":[{\"type\":\"tgroup\",\"label\":\"toto\",\"items\":[{\"type\":\"vgroup\",\"label\":\"foo 0\",\"items\":[{\"type\":\"hslider\",\"label\":\"slid1\",\"address\":\"/toto/foo_0/slid1\",\"index\":\"0\",\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"slid2\",\"address\":\"/toto/foo_0/slid2\",\"index\":\"4\",\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.1\"}]},{\"type\":\"vgroup\",\"label\":\"foo 1\",\"items\":[{\"type\":\"hslider\",\"label\":\"slid1\",\"address\":\"/toto/foo_1/slid1\",\"index\":\"8\",\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"slid2\",\"address\":\"/toto/foo_1/slid2\",\"index\":\"12\",\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.1\"}]},{\"type\":\"vgroup\",\"label\":\"foo 2\",\"items\":[{\"type\":\"hslider\",\"label\":\"slid1\",\"address\":\"/toto/foo_2/slid1\",\"index\":\"16\",\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"slid2\",\"address\":\"/toto/foo_2/slid2\",\"index\":\"20\",\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.1\"}]},{\"type\":\"vgroup\",\"label\":\"foo 3\",\"items\":[{\"type\":\"hslider\",\"label\":\"slid1\",\"address\":\"/toto/foo_3/slid1\",\"index\":\"24\",\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"slid2\",\"address\":\"/toto/foo_3/slid2\",\"index\":\"28\",\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.1\"}]}]}]}";
}
