#!/bin/bash
# Generate synthetic_tests.dsp : one definition per (family, x, y), named
# <family><x><y> like the m<S><P> filter matrices of the benchtool, so that
# every test is one entry point of the same file : faust -pn r23 ...
#
# Every definition has no input, so that the print architecture runs it as
# is : the networks (m, r, d) are excited by a structure-free impulse train
# (their output is an impulse response), the tables (t) and the integer
# generators (w) are their own source. The families :
#
#   m<S><P>  the original matrix : S resonlp filters in sequence, P sequences
#            in parallel, coefficients depending on (i, j)
#   r<D><K>  feedback network : a chain of D one-pole filters in the loop of
#            a delay read through K taps (delays 1..K) -- the normal form
#            dissolves the aliases, so the recursive members read each other
#            at the current tick, and the delayed compounds are deferred
#            line writes (fdnrev0 and greyhole shapes)
#   d<N><V>  delays : N delay lines in series in a feedback loop, V the kind
#            of delay : 1 constant, 2 modulated (fdelay4 + oscrc),
#            3 modulated into a crossfading sdelay, 4 fractional lti,
#            5 select2 between two delays
#   t<N><Z>  tables and latches : N table readers (osc tables) whose outputs
#            are combined and read at delay Z-1 (Z=1 : delay 0), latched
#            by an oscillator whose period is not an integer sample count
#   w<B><L>  integer arithmetic on overflow : B LCG noise generators summed
#            (the n-ary int Sum path), each a chain of L multiply-adds
#            (the binary path) -- bit-exact only with wrapping semantics
set -eu
cd "$(dirname "$0")"
OUT=synthetic_tests.dsp
{
echo '// GENERATED by gen.sh -- do not edit ; regenerate with ./gen.sh'
echo 'import("stdfaust.lib");'
echo
echo '// the excitation of the networks : an impulse every 4096 frames, no table,'
echo '// no oscillator, no real arithmetic -- a counter and a comparison -- so that'
echo '// the output is the impulse response of the structure under test alone'
echo 'pulse = (ba.time % 4096) == 0;'
echo
echo '// m<S><P> : the filter matrix'
echo 'mF(i,j) = fi.resonlp(30+500*i+50*j,5,1);'
for S in $(seq 1 9); do for P in $(seq 1 9); do
  echo "m$S$P = par(j, $P, pulse : seq(i, $S, mF(i,j)));"
done; done
echo
echo '// r<D><K> : feedback network, D one-pole stages in the loop, K delayed taps'
echo 'rChain(d) = seq(i, d, fi.lowpass(1, 1000 + 300*i));'
echo 'rTaps(k) = _ <: par(i, k, @(37 + 11*i)) :> /(k);'
for D in $(seq 1 9); do for K in $(seq 1 9); do
  echo "r$D$K = pulse : (+ : rChain($D)) ~ (rTaps($K) : *(0.5));"
done; done
echo
echo '// d<N><V> : N delays of kind V in series in a feedback loop'
echo 'dKind(1, i) = de.delay(512, 40 + 7*i);'
echo 'dKind(2, i) = de.fdelay4(512, 35 + 5*i + 25*os.oscrc(0.7 + 0.3*i));'
echo 'dKind(3, i) = de.fdelay4(512, 35 + 5*i + 25*os.oscrc(0.7 + 0.3*i)) : de.sdelay(4096, 1024, 500 + 100*i);'
echo 'dKind(4, i) = de.fdelaylti(3, 512, 40.5 + 3*i);'
echo 'dKind(5, i) = _ <: select2(os.lf_squarewave(1 + i) > 0, de.delay(512, 40 + 7*i), de.delay(512, 53 + 5*i));'
for N in $(seq 1 9); do for V in 1 2 3 4 5; do
  echo "d$N$V = pulse : + ~ (seq(i, $N, dKind($V, i)) : *(0.4));"
done; done
echo
echo '// t<N><Z> : N table readers combined, read at delay Z-1, latched on a non-integer period'
echo 'tRead(i) = os.osc(110 + 33*i);'
for N in $(seq 1 9); do for Z in $(seq 1 9); do
  echo "t$N$Z = (par(i, $N, tRead(i)) :> /($N)) <: _, (@($((Z-1))) : ba.latch(os.oscrs(10.1))) :> _;"
done; done
echo
echo '// w<B><L> : B LCG generators summed, each a chain of L multiply-adds'
echo 'wLcg(l) = (+(12345) : *(1103515245)) ~ (seq(i, l, +(12345 + i) : *(1103515245)));'
for B in $(seq 1 9); do for L in $(seq 1 9); do
  echo "w$B$L = par(i, $B, wLcg($L) : +(i)) :> _ : *(4.656612875245797e-10);"
done; done
} > $OUT
echo "generated $(grep -c '^[a-z][0-9][0-9] = ' $OUT) definitions in $OUT"
