
/*
Code generated with Faust version 2.5.15
Compilation options: wast-i, -double -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"dbmeter\",\"version\":\"2.5.15\",\"options\":\"wast-i, -double -ftz 0\",\"size\":\"272\",\"inputs\":\"8\",\"outputs\":\"8\",\"meta\":[{\"author\":\"Grame\"},{\"copyright\":\"(c)GRAME 2006\"},{\"license\":\"BSD\"},{\"math.lib/author\":\"GRAME\"},{\"math.lib/copyright\":\"GRAME\"},{\"math.lib/deprecated\":\"This library is deprecated and is not maintained anymore. It will be removed in August 2017.\"},{\"math.lib/license\":\"LGPL with exception\"},{\"math.lib/name\":\"Math Library\"},{\"math.lib/version\":\"1.0\"},{\"music.lib/author\":\"GRAME\"},{\"music.lib/copyright\":\"GRAME\"},{\"music.lib/license\":\"LGPL with exception\"},{\"music.lib/name\":\"Music Library\"},{\"music.lib/version\":\"1.0\"},{\"name\":\"dbmeter\"},{\"version\":\"1.0\"}],\"ui\":[{\"type\":\"hgroup\",\"label\":\"8 channels dB meter\",\"items\":[{\"type\":\"vgroup\",\"label\":\"0\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7f825172a070\",\"address\":\"/8_channels_dB_meter/0/0x7f825172a070\",\"index\":\"32\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"1\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7f825172e7a0\",\"address\":\"/8_channels_dB_meter/1/0x7f825172e7a0\",\"index\":\"64\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"2\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7f8251732eb0\",\"address\":\"/8_channels_dB_meter/2/0x7f8251732eb0\",\"index\":\"96\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"3\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7f8251737670\",\"address\":\"/8_channels_dB_meter/3/0x7f8251737670\",\"index\":\"128\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"4\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7f825173bee0\",\"address\":\"/8_channels_dB_meter/4/0x7f825173bee0\",\"index\":\"160\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"5\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7f8251740800\",\"address\":\"/8_channels_dB_meter/5/0x7f8251740800\",\"index\":\"192\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"6\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7f82517451d0\",\"address\":\"/8_channels_dB_meter/6/0x7f82517451d0\",\"index\":\"224\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]},{\"type\":\"vgroup\",\"label\":\"7\",\"items\":[{\"type\":\"vbargraph\",\"label\":\"0x7f8251749c50\",\"address\":\"/8_channels_dB_meter/7/0x7f8251749c50\",\"index\":\"256\",\"meta\":[{\"unit\":\"dB\"}],\"min\":\"-70\",\"max\":\"10\"}]}]}]}";
}
