
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"Brass\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"16600\",\"inputs\":\"0\",\"outputs\":\"2\",\"meta\":[{\"copyright\":\"(c)Romain Michon, CCRMA (Stanford University), GRAME\"},{\"delays.lib/name\":\"Faust Delay Library\"},{\"delays.lib/version\":\"0.0\"},{\"description\":\"Simple brass instrument physical model with physical parameters.\"},{\"filters.lib/name\":\"Faust Filters Library\"},{\"filters.lib/version\":\"0.0\"},{\"license\":\"MIT\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"Brass\"},{\"noises.lib/name\":\"Faust Noise Generator Library\"},{\"noises.lib/version\":\"0.0\"},{\"oscillators.lib/name\":\"Faust Oscillator Library\"},{\"oscillators.lib/version\":\"0.0\"},{\"routes.lib/name\":\"Faust Signal Routing Library\"},{\"routes.lib/version\":\"0.0\"},{\"signals.lib/name\":\"Faust Signal Routing Library\"},{\"signals.lib/version\":\"0.0\"}],\"ui\":[{\"type\":\"hgroup\",\"label\":\"brass\",\"items\":[{\"type\":\"vgroup\",\"label\":\"blower\",\"items\":[{\"type\":\"hslider\",\"label\":\"pressure\",\"address\":\"/brass/blower/pressure\",\"index\":\"80\",\"meta\":[{\"0\":\"\"}],\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"breathGain\",\"address\":\"/brass/blower/breathGain\",\"index\":\"92\",\"meta\":[{\"1\":\"\"}],\"init\":\"0.1\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"breathCutoff\",\"address\":\"/brass/blower/breathCutoff\",\"index\":\"100\",\"meta\":[{\"2\":\"\"}],\"init\":\"2000\",\"min\":\"20\",\"max\":\"20000\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"vibratoFreq\",\"address\":\"/brass/blower/vibratoFreq\",\"index\":\"60\",\"meta\":[{\"3\":\"\"}],\"init\":\"5\",\"min\":\"0.1\",\"max\":\"10\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"vibratoGain\",\"address\":\"/brass/blower/vibratoGain\",\"index\":\"44\",\"meta\":[{\"4\":\"\"}],\"init\":\"0.25\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"}]},{\"type\":\"vgroup\",\"label\":\"brassModel\",\"items\":[{\"type\":\"hslider\",\"label\":\"tubeLength\",\"address\":\"/brass/brassModel/tubeLength\",\"index\":\"140\",\"meta\":[{\"1\":\"\"}],\"init\":\"0.5\",\"min\":\"0.01\",\"max\":\"2.5\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"lipsTension\",\"address\":\"/brass/brassModel/lipsTension\",\"index\":\"128\",\"meta\":[{\"2\":\"\"}],\"init\":\"0.5\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"mute\",\"address\":\"/brass/brassModel/mute\",\"index\":\"8\",\"meta\":[{\"3\":\"\"}],\"init\":\"0.5\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"}]}]}]}";
}
