
/*
Code generated with Faust version 2.5.15
Compilation options: wast/wasm, -scal -ftz 0
*/

function getJSONmydsp() {
	return "{\"name\":\"Flute\",\"version\":\"2.5.15\",\"options\":\"wast/wasm, -scal -ftz 0\",\"size\":\"32976\",\"inputs\":\"0\",\"outputs\":\"2\",\"meta\":[{\"copyright\":\"(c)Romain Michon, CCRMA (Stanford University), GRAME\"},{\"delays.lib/name\":\"Faust Delay Library\"},{\"delays.lib/version\":\"0.0\"},{\"description\":\"Simple flute physical model with physical parameters.\"},{\"filters.lib/name\":\"Faust Filters Library\"},{\"filters.lib/version\":\"0.0\"},{\"license\":\"MIT\"},{\"maths.lib/author\":\"GRAME\"},{\"maths.lib/copyright\":\"GRAME\"},{\"maths.lib/license\":\"LGPL with exception\"},{\"maths.lib/name\":\"Faust Math Library\"},{\"maths.lib/version\":\"2.1\"},{\"name\":\"Flute\"},{\"noises.lib/name\":\"Faust Noise Generator Library\"},{\"noises.lib/version\":\"0.0\"},{\"oscillators.lib/name\":\"Faust Oscillator Library\"},{\"oscillators.lib/version\":\"0.0\"},{\"routes.lib/name\":\"Faust Signal Routing Library\"},{\"routes.lib/version\":\"0.0\"},{\"signals.lib/name\":\"Faust Signal Routing Library\"},{\"signals.lib/version\":\"0.0\"}],\"ui\":[{\"type\":\"hgroup\",\"label\":\"flute\",\"items\":[{\"type\":\"vgroup\",\"label\":\"blower\",\"items\":[{\"type\":\"hslider\",\"label\":\"pressure\",\"address\":\"/flute/blower/pressure\",\"index\":\"64\",\"meta\":[{\"0\":\"\"}],\"init\":\"0\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"breathGain\",\"address\":\"/flute/blower/breathGain\",\"index\":\"76\",\"meta\":[{\"1\":\"\"}],\"init\":\"0.1\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"breathCutoff\",\"address\":\"/flute/blower/breathCutoff\",\"index\":\"84\",\"meta\":[{\"2\":\"\"}],\"init\":\"2000\",\"min\":\"20\",\"max\":\"20000\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"vibratoFreq\",\"address\":\"/flute/blower/vibratoFreq\",\"index\":\"44\",\"meta\":[{\"3\":\"\"}],\"init\":\"5\",\"min\":\"0.1\",\"max\":\"10\",\"step\":\"0.1\"},{\"type\":\"hslider\",\"label\":\"vibratoGain\",\"address\":\"/flute/blower/vibratoGain\",\"index\":\"28\",\"meta\":[{\"4\":\"\"}],\"init\":\"0.25\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"}]},{\"type\":\"vgroup\",\"label\":\"fluteModel\",\"items\":[{\"type\":\"hslider\",\"label\":\"tubeLength\",\"address\":\"/flute/fluteModel/tubeLength\",\"index\":\"8320\",\"meta\":[{\"0\":\"\"}],\"init\":\"0.8\",\"min\":\"0.01\",\"max\":\"3\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"mouthPosition\",\"address\":\"/flute/fluteModel/mouthPosition\",\"index\":\"8332\",\"meta\":[{\"1\":\"\"}],\"init\":\"0.5\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"},{\"type\":\"hslider\",\"label\":\"outGain\",\"address\":\"/flute/fluteModel/outGain\",\"index\":\"0\",\"meta\":[{\"2\":\"\"}],\"init\":\"0.5\",\"min\":\"0\",\"max\":\"1\",\"step\":\"0.01\"}]}]}]}";
}
